### ISSUE TITLE
Unknown library type "protozoa"

### ISSUE THREAD

**Issue by tseemann** [DerrickWood/kraken2#10]
The `protozoa)` case is missing from the download script:

https://github.com/DerrickWood/kraken2/blob/master/scripts/download_genomic_library.sh

```
kraken2-build --db mydb --download-library protozoa

Unknown library type "protozoa"

Usage: kraken2-build [task option] [options]

Task options (exactly one must be selected):
  --download-taxonomy        Download NCBI taxonomic information
  --download-library TYPE    Download partial library
                             (TYPE = one of "archaea", "bacteria", "plasmid",
                             "viral", "human", "fungi", "plant", "protozoa",
                             "nr", "nt", "env_nr", "env_nt", "UniVec",
                             "UniVec_Core")
```

**Comment by jianglikun** [comment]
In the main script “kraken2-build”，line 34，

my @VALID_LIBRARY_TYPES = qw/archaea bacteria plasmid viral plant
                             fungi human nr nt env_nr env_nt
                             UniVec UniVec_Core/;

protozoa is missed！

**Comment by DerrickWood** [comment]
@jianglikun Thanks - that is indeed the problem. `kraken2-build` just needed to believe in itself a bit more - fixed in https://github.com/DerrickWood/kraken2/commit/93c328b2706b1b020cf3d38faf3d2b6fae7ded04
