### ISSUE TITLE
new NCBI taxonomy repository

### ISSUE THREAD

**Issue by kevinVervier** [DerrickWood/kraken2#101]
Hi and thank for the amazing tool that is Kraken.
I tried to build a new database this morning and ran into the following error:

No such file ‘gi_taxid_nucl.dmp.gz’.
Command: kraken-build --download-taxonomy --db mydb 
when looking at NCBI ftp (ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy) it looks like they changed the name of the corresponding file today.
Could you help fixing this issue?
best,
Kevin

**Comment by aguang** [comment]
I have a similar issue, I am getting the error:

```
kraken2-build --standard --db standard_kraken2
Downloading nucleotide est accession to taxon map...rsync: link_stat "/taxonomy/accession2taxid/nucl_est.accession2taxid.gz" (in pub) failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1659) [Receiver=3.1.3]
```

when I try to build the standard database. At [ftp://ftp.ncbi.nih.gov/pub/taxonomy/accession2taxid](ftp://ftp.ncbi.nih.gov/pub/taxonomy/accession2taxid) there does not appear to be a file called `nucl_est_accession2taxid.gz`. Took a look at the source code, it appears to be due to line 35 in `scripts/download_taxonomy.sh` when iterating thru est gb gss wgs.

**Comment by kevinVervier** [comment]
I got answer from the NCBI Help Desk:
'The Taxonomy gi_taxid_nucl.dmp.gz FTP file (and others) are not currently available due to a software bug found in the file.
I do not have an estimate of when the files will be back.'

So apparently the missing files should be back 'soon'.

**Comment by jenniferlu717** [comment]
I contacted NCBI and they made some changes to the files so we will make changes to the code ASAP to download the right files.

**Comment by SamStudio8** [comment]
This also seems to fail silently if you use the --use-ftp flag

**Comment by Toliman06** [comment]
Official explanation is here:
Upcoming Changes to EST and GSS Databases
https://ncbiinsights.ncbi.nlm.nih.gov/2018/07/30/upcoming-changes-est-gss-databases/

**Comment by alducluzeau** [comment]
Can we use a taxonomy folder downloaded before NCBI made these changes? I've got one that is just 6 days old...

**Comment by SamStudio8** [comment]
Worked for me, I used one from last week.

**Comment by kanchond** [comment]
Until code changes are made to Kraken2 to download the correct file, does anyone know where one can download the old nucl_est_accession2taxid.gz file from?

**Comment by SamStudio8** [comment]
@kanchond I'm hosting a copy that I grabbed on April 9th [here](http://refdb.s3.climb.ac.uk/k2_taxonomy_20190409/nucl_est.accession2taxid).

**Comment by alducluzeau** [comment]
@SamStudio8: using the taxonomy folder I downloaded for Plant db worked great to build a custom db yesterday, as you said. But I just used the --clean command and sent it to hell. :((((
Would you have any advice?

**Comment by SamLambrechtsUGent** [comment]
What about the `nucl_gss.accession2taxid.gz` file that has gone missing too. Is anybody perhaps hosting a copy of that one? @SamStudio8 you don't happen to have a copy? Or does anybody know where we can find it?

**Comment by SamStudio8** [comment]
Hi folks,
I'm hosting a copy of my `taxonomy` folder from April 9th: [http://refdb.s3.climb.ac.uk/k2_taxonomy_20190409.tar.gz
](http://refdb.s3.climb.ac.uk/k2_taxonomy_20190409.tar.gz
).

**Comment by MaryoHg** [comment]
Thanks @SamStudio8.

**Comment by jenniferlu717** [comment]
Hi all, the code has been updated to reflect the NCBI changes.

nucl_est and nucl_gss are now combined into a single file in the provided taxonomy 

the download scripts for kraken should work now but let me know if it doesnt!

**Comment by fetyj** [comment]
Hi, 
I've updated from git master but still got the error message 
```Downloading nucleotide est accession to taxon map...rsync: link_stat "/taxonomy/accession2taxid/nucl_est.accession2taxid.gz" (in pub) failed: No such file or directory (2) rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1655) [Receiver=3.1.1]```
Regards,

Fety

**Comment by jenniferlu717** [comment]
How did you update from git master/reinstall kraken2? I looked at the download script and it does no longer include the nucl_est download.

**Comment by fetyj** [comment]
I did the ```git pull``` command fromage git folder, it takes the change you've made to ```download_taxonomy.sh``` but can't get it working

**Comment by jenniferlu717** [comment]
You need to rerun install_kraken2.sh. I would suggest deleting the previous installation.

**Comment by fetyj** [comment]
Got it, thanks for your help.
Regards,

Fety

**Comment by nick-youngblut** [comment]
Any timeline on when the [kraken2 bioconda recipe](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/kraken2) will be updated? `kraken-build --download-taxonomy` is broken on the current version of the recipe (`kraken2    2.0.7_beta      pl526h6bb024c_3    bioconda`)

**Comment by kopardev** [comment]
> Hi folks,
> I'm hosting a copy of my `taxonomy/` folder from April 9th: [http://refdb.s3.climb.ac.uk/k2_taxonomy_20190409.tar.gz ](http://refdb.s3.climb.ac.uk/k2_taxonomy_20190409.tar.gz)

Thank you so much.
