### ISSUE TITLE
Can I reuse taxonomy files when building a new database?

### ISSUE THREAD

**Issue by bioinformatist** [DerrickWood/kraken2#102]
Hi,
Does kraken2 use exactly same taxonomy information when building different reference libraries?
Since the downloading step takes too long time in China, I wanna play some tricks here.
For instance, I have built a `viral` database named as `virus`, and now when I try build another database named as `all` with `bacteria` + `archaea` + `viral`, I just copy the directory recursively from the existed one like this:

```bash
cp -R /home/ysun/viral_blast/bracken/virus/taxonomy all/
```

When I try call `kraken2-build --threads 56 --download-taxonomy --db all` for downloading taxonomy information, it finishes immediately with nothing to STDOUT.

How does kraken2 check that if it's necessary to download again? I mean that if the version of genomic reference is different from taxonomy information, there may be some mistakes when during classification.

Thank you in advance.

**Comment by jenniferlu717** [comment]
Kraken2 only checks to make sure the taxonomy folder is present. You can reuse the taxonomy as long as the new genomes/taxids are in the taxonomy. 

During building, missing taxids will cause an error message.
