### ISSUE TITLE
estimate capacity command not found 

### ISSUE THREAD

**Issue by AgustoLuz** [DerrickWood/kraken2#105]
Dear all I am trying to install the bacteria  NCBI, but in the last step of the creation of the DB I get this error xargs: cat: terminated by signal 13 when building library with kraken2, estimate_capacity: command not found something like that, please can you help me

**Comment by ebagrenrut** [comment]
estimate_capacity is a script in the directory to which you install kraken2. estimate_capacity will also need to be in your PATH so that build_kraken2_db.sh can run it.

**Comment by jenniferlu717** [comment]
You should first run `sh build_kraken2_db.sh DIR` before trying to run any kraken2 command.

**Comment by Scott-0208** [comment]
> estimate_capacity

Hi, is the DIR in this command "sh build_kraken2_db.sh DIR" refers to the directory where I want to run it?
