### ISSUE TITLE
Kraken2 not recognizing Fungi being added to standard library?

### ISSUE THREAD

**Issue by Justinwright973** [DerrickWood/kraken2#106]
Hello Kraken2 team,

I'm having trouble attempting to add the "fungi" to the standard kraken db.

I had no issue building the standard kraken db which worked fantastically. However, after building I realized that fungi are not included, so I ran the following command to access the fungi to my standard db library:

_"kraken2-build --download-library fungi --db standard_db"_

It appears this works, as I now see a "fungi" folder within my library:

_"ls"
"archaea/  bacteria/  fungi/  human/  UniVec_Core/  viral/"_

It also appears that masking has run fine, everything that I need appears to be in place. 

After making this observation, I then re-ran the build script to incorporate these new fungal sequences into my hash table/kraken2db:

_"kraken2-build --build --db standard_db"_

Interestingly, this again runs with **no error**...however I have confirmed via the --inspect command as well as running kraken2 while reporting zero counts, that these fungal organisms are **not being incorporated into the final db**. Any reasoning as to what I am doing wrong or why is is occurring? If a work around could be suggested it would be greatly appreciated!

Thank you.

**Comment by DerrickWood** [comment]
Once you've successfully built a database using `kraken2-build`, you can't simply download more data into the reference set and build again. You'll need to delete the database files that are created by `kraken2-build` (specifically, those made by the `build_kraken2_db.sh` script) before invoking `kraken2-build --build` again. Something like this should work:

    rm standard_db/*.k2d standard_db/seqid2taxid.map
    kraken2-build --db standard_db --build

You can also add things like `--threads 16` to the build command to make it a bit faster.

**Comment by jenniferlu717** [comment]
Given the age of this thread, I'm going to close this issue. If you continue to have issues, please open a new issue. Thank you!
