### ISSUE TITLE
"Possible unintended interpolation of @2" When kraken2 installed in Galaxy through conda

### ISSUE THREAD

**Issue by dfornika** [DerrickWood/kraken2#109]
I'm seeing the following message in error logs when running kraken2 in galaxy:

```
Possible unintended interpolation of @2 in string at /opt/galaxy/tool_dependencies/_conda/envs/__kraken2@2.0.8_beta/bin/kraken2 line 16.
```
The first 16 lines of my installed `kraken2` executable script look like:

```
#!/usr/bin/env perl

# Copyright 2013-2019, Derrick Wood <dwood@cs.jhu.edu>
#
# This file is part of the Kraken 2 taxonomic sequence classification system.

# Wrapper for Kraken's classifier

use strict;
use warnings;
use Fcntl;
use File::Basename;
use Getopt::Long;

my $PROG = basename $0;
my $KRAKEN2_DIR = "/opt/galaxy/tool_dependencies/_conda/envs/__kraken2@2.0.8_beta/libexec";
```
It looks like perl doesn't like that `@` symbol in the middle of the `$KRAKEN2_DIR` path. It's been a while since I wrote perl, but I think I recall that using single-quotes would prevent the string from being interpolated. Would that be an appropriate fix?

**Comment by zburcham** [comment]
I went into the kraken2 and kraken2-build files and added a forward slash before the @ and it fixed it for me. So \@

**Comment by dfornika** [comment]
Good suggestion @zburcham but that would need to be done post-installation after the `#####=KRAKEN2_DIR=#####` is substituted out on this line:

https://github.com/DerrickWood/kraken2/blob/4f73d69e75088e0e39021d1c6ab214a3c7b409ca/scripts/kraken2#L16

...which is done in the install script here:

https://github.com/DerrickWood/kraken2/blob/4f73d69e75088e0e39021d1c6ab214a3c7b409ca/install_kraken2.sh#L32

My thinking is that the value of `$KRAKEN2_DIR` should be essentially an immutable string anyways, so there shouldn't be any interpolation going on there. So it seems that it would be appropriate to use single-quotes, which prevents interpolation.
