### ISSUE TITLE
Is --input-fastq obsolete?

### ISSUE THREAD

**Issue by zburcham** [DerrickWood/kraken2#112]
Hello,

I am running the current version of kraken2 and ran my sequences as fastq files. According to the manual I need to put the option --fastq-input in my command, but the output says "unknown option: fastq-input". Is this command no longer available? And if so, does kraken2 automatically detect fastq vs fasta?

**Comment by DerrickWood** [comment]
Yes, that option is no longer available as Kraken 2 does automatically detect fastq vs. fasta - that will need to be changed in the manual. Sorry about the oversight there.
