### ISSUE TITLE
Cannot download plant kraken database

### ISSUE THREAD

**Issue by Anuravi123** [DerrickWood/kraken2#113]
Hello,
I am trying to download the kraken2 database for plants but I get this error:

Step 1/2: Performing rsync file transfer of requested files
rsync: link_stat "/all/GCF/004/193/775/GCF_004193775.1_ASM419377v2/GCF_004193775.1_ASM419377v2_genomic.fna.gz" (in genomes) failed: No such file or directory (2) 

rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1655) [generator=3.1.1]
rsync_from_ncbi.pl: rsync error, exiting: 5888

Could you please help me with this!

Thanks!

**Comment by Anuravi123** [comment]
I rectified this error by adding --use-ftp and it worked! However, I have another issue during the building of the database :(

I used this command: ./kraken2/scripts/kraken2-build --build --db kraken2 --threads 64

I get this error:

Creating sequence ID to taxonomy ID map (step 1)...
Sequence ID to taxonomy ID map already present, skipping map creation.
Estimating required capacity (step 2)...
/home/ubuntu/volume1/chick_genome/kraken2/scripts/build_kraken2_db.sh: line 101: estimate_capacity: command not found
xargs: cat: terminated by signal 13

Could you help me with this. 

Thanks!

**Comment by jenniferlu717** [comment]
Did you install kraken or are you running the scripts directly from the downloaded Kraken2 git repository? 

When you run `sh install_kraken.sh KRAKEN_DIR`, all of the required executables will be placed in KRAKEN_DIR. When running `KRAKEN_DIR/kraken-build`, it will be able to access all other executables, including the `estimate_capacity` executable.
