### ISSUE TITLE
Kraken2 output to Kronagram?

### ISSUE THREAD

**Issue by wolfgangrumpf** [DerrickWood/kraken2#114]
Does anyone know of a way to take kraken2 output and generate a proper kronagram using kronatools?  I know I can do this with kraken1 output, but I can't seem to figure out how to do it with kraken2...

**Comment by khyox** [comment]
Hi Wolfgang. [Recentrifuge](http://www.recentrifuge.org) is able to process kraken2 output and generate score-oriented, krona-like plots (see [Recentrifuge's wiki page for processing Kraken data](https://github.com/khyox/recentrifuge/wiki/Running-recentrifuge-for-Kraken)). Maybe  Recentrifuge works for your needs!

**Comment by jenniferlu717** [comment]
Script has been written and will be provided soon. Ideally within the next week.

**Comment by rizkg** [comment]
Hello, if that may be of any help, I am using this to visualize the output of the kraken2 sample report in a krona graph.  

You just need to install the krona tools https://github.com/marbl/Krona/wiki/Installing  and then : 

```
cut -f3,5 kraken2.out > krona.in

ktImportTaxonomy krona.in -o krona.html -t 2 -m 1
```

I am not sure if that is the best way to do it, but seems to be working fine in my case.

**Comment by jenniferlu717** [comment]
Script (alongside other postprocessing scripts) is at https://github.com/jenniferlu717/KrakenTools

**Comment by rizkg** [comment]
great, thank you !
