### ISSUE TITLE
No dustmasker in path

### ISSUE THREAD

**Issue by sofiamurga** [DerrickWood/kraken2#116]
Hello, 
I've compiled Kraken2-2.0.8 version and  wanted to build the Standard DataBase, but I did not succeeded. This error message appeared:
Unable to find dustmasker in path, can't mask low-complexity sequences

```
Masking low-complexity regions of downloaded library...which: no dustmasker in (/var/lib/condor/execute/slot1/dir_34598/kraken2-2.0.8:/var/lib/condor/execute/slot1/dir_34598/kraken2-2.0.8:/var/lib/condor/execute/slot1/dir_34598/kraken2-2.0.8:/usr/local/bin:/usr/bin)
```

I'm running this through a remote server so is there any independent command I should add to the path?

**Comment by sofiamurga** [comment]
Found this already and succeeded:
https://github.com/DerrickWood/kraken2/blob/master/docs/MANUAL.markdown#masking-of-low-complexity-sequences

ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ncbi-blast-2.9.0+-x64-linux.tar.gz

**Comment by yezhengli-Mr9** [comment]
> Found this already and succeeded:
> https://github.com/DerrickWood/kraken2/blob/master/docs/MANUAL.markdown#masking-of-low-complexity-sequences
> 
> ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ncbi-blast-2.9.0+-x64-linux.tar.gz

How do you "suceeded"?
