### ISSUE TITLE
libexec/classify: invalid option -- 'H'

### ISSUE THREAD

**Issue by ciemanek** [DerrickWood/kraken2#118]
I tried to re-run my pipeline which is using Kraken2 (I ran it as near as last week on the same data and it was working fine), however I got a following error:

`libexec/classify: invalid option -- 'H'`

As you can see below, my command does not include an --H option, so I wonder what might cause this error.

`kraken2 --threads 1 --db $DB_PATH --output $OUTPUT --use-names --report $REPORT $FASTQ`

**Comment by ciemanek** [comment]
The problem was that after installing Bracken, Kraken version 1.1.1 was installed, which was causing confusion. Installing Kraken2 solved an issue.

**Comment by ChaoChangmicro** [comment]
> The problem was that after installing Bracken, Kraken version 1.1.1 was installed, which was causing confusion. Installing Kraken2 solved an issue.

thanks!
