### ISSUE TITLE
how memory-mapping work?

### ISSUE THREAD

**Issue by seahurt** [DerrickWood/kraken2#120]
I may be misunderstand the meaning of memory-mapping at first, so I move the database(3 *.k2d file) to /dev/shm, then link back.  After that,  running  kraken2 with --memory-mapping options became very efficient, every task finished within 1 min.

But when I learned that memory-mapping should use mmap function, and the software itself will handle it.  I run kraken2 with --memory-mapping while put database on disk. The task runs very very slow, not finished  after two hour.

When I run without memory-mapping option, the task finished within 2 min.

So what is the real trick of memory mapping in kraken2?

**Comment by bangbangphil** [comment]
For me letting the OS do the swapping is more efficient than using option --memory-mapping. See  #[100].

**Comment by seahurt** [comment]
@bangbangphil When running one task, without --memory-mapping option is good enough. But it spends 2min to  load the database, while classification only need 1min. My project need to run 100+ samples, so I think it is not good enough. Runing multiple task at a time should Be the purpose of memory-mapping, like bowtie2 does. But kraken seems not be able to do that.

**Comment by seahurt** [comment]
bowtie2 also fails me with memory-mapping...MayBe I misunderstand the purpose of memory-mapping from day one...

**Comment by seahurt** [comment]
I found this in kraken's usage output:
```
 --memory-mapping        Avoids loading database into RAM
```
So I know how my problem appeared.

With this option, kraken2 will mmap the  file in database as memory space.
So when I put my db to /dev/shm, kraken2 will still read from memory, all process read from the same address of memory with no duplication.

This is awesome!!
