### ISSUE TITLE
Download database

### ISSUE THREAD

**Issue by jfourquet2** [DerrickWood/kraken2#121]
Hi,
I have one question about database: when we build a database with kraken2-2.0.8-beta, is the tool download database from ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/ and download only bacteria (kraken2-build --threads 24 --download-library bacteria --db db_name) , archaea (kraken2-build --threads 24 --download-library archaea --db db_name) and viral (kraken2-build --threads 24 --download-library viral--db db_name) ?
Thanks a lot in advance !

**Comment by jenniferlu717** [comment]
The --download-library functions for bacteria, archaea, and viral downloads only complete genomes from refseq.

**Comment by jfourquet2** [comment]
Ok, thanks a lot !
