### ISSUE TITLE
different bacteria read counts

### ISSUE THREAD

**Issue by bangbangphil** [DerrickWood/kraken2#122]
Hi,

I did two classification tasks on the same sample: one using the standard database which includes homo sapiens, and the other using a custom database that doesn't contains homo sapiens. Of the 29 millions reads, I get 16k reads on bacteria when using the standard database (with HS). When using the custom database without HS I get 1.06 million reads on bacteria.

My question is: what should I believe? There is clearly a human contamination in the sample, but when I ignore it in classification I get much more bacterial reads, and much more diversity too. But I am tempted to put my money on the classification using bacteria and human, as for me the read count difference must come from some sequence homology between human and bacteria, where some reads are favored to human when both targets are available.

What do you think? Does my impression fits with kraken's internal alignment algorithm?

thanks!

Phil

**Comment by Yiheng323** [comment]
Hi Phil,
I think the answer might depend on how was the data prepared, and what 'custom database' you used.
I experienced some ligation errors from my nanopore sequencing library which some DNA got mis-ligated together so it might be half human and half bacteria from that read. Also the difference in the database could also affect the result. I have a fungal dataset that I classified using kraken2 against nt database and Refseq_fungi database. Only 58% overlap in phylum level and 50% overlap in species level. (overlap% = # of overlapped reads/# of reads that classified against either databases)

**Comment by bangbangphil** [comment]
@Yiheng323 Thanks for the reply. The custom database was built using kraken2-build bacteria, archaea, plasmid, viral and fungal libraries. I was wondering about reads that are classifying against bacteria when human not present, and against human when it is present. For example in std database with human:
`C   NB502083:48:HKTMTAFXY:1:11101:19388:1052    Homo sapiens (taxid 9606)   76|76   9606:3 131567:5 9606:1 131567:1 9606:5 131567:3 9606:24 |:| 9606:21 2759:5 9606:5 2759:6 9606:5`
Same read in custom database without human:
`C   NB502083:48:HKTMTAFXY:1:11101:19388:1052    1280    76|76   0:3 1280:5 0:1 1280:1 0:5 1280:3 0:24 |:| 0:3 1280:5 0:1 1280:1 0:5 1280:3 0:24`
taxon 1280 is Staphylococcus aureus, but there are many kmer not in database '0:'. Taking a closer look at the output I see that to be unclassified both reads must be completely absent from kmer db. I guess from this observation that one is better with the most complete kmer database. Or is there a way to filter or control classification with respect to the number of kmer not found in database?

**Comment by jenniferlu717** [comment]
Generally, we suggest including human in any database. We have found that in many samples **and** even in reference genomes, human contamination is common.

For instance, this recent paper from our lab shows human contamination in many bacterial genomes, including completed ones. https://genome.cshlp.org/content/early/2019/05/07/gr.245373.118.abstract
