### ISSUE TITLE
Classified with many kmers not in database

### ISSUE THREAD

**Issue by bangbangphil** [DerrickWood/kraken2#123]
Hi,
In my classification output file I have many hits that present much more kmers not in database than kmer on selected taxon. Here are some examples :  

`C       NB502083:48:HKTMTAFXY:1:21207:14088:14959       573     76|76   0:20 573:2 0:20 |:| 0:20 573:2 0:20`
`C       NB502083:48:HKTMTAFXY:1:21210:10228:15535       573     76|76   0:35 573:1 0:6 |:| 0:35 573:1 0:6`
`C       NB502083:48:HKTMTAFXY:1:21212:24148:13783       573     76|76   0:1 573:3 0:38 |:| 0:1 573:3 0:38`
`C       NB502083:48:HKTMTAFXY:1:21302:1329:12912        573     75|75   0:26 573:5 0:10 |:| 0:26 573:5 0:10`

Is there a reason to classify to a taxon when the majority of kmers are not found in database?

thanks for your help

Phil

**Comment by jenniferlu717** [comment]
Unclassified kmers do not affect the final classification unless you specify a confidence threshold that requires a certain portion of kmers to be classified. The default does not specify any threshold so I would suggest using a threshold of --confidence 0.9 at least.
