### ISSUE TITLE
kraken2-build --build cat:  broken pipe

### ISSUE THREAD

**Issue by hqtdave** [DerrickWood/kraken2#125]
Hi all,

I'm trying to build a custom database but I got this issue during --build step. 

![image](https://user-images.githubusercontent.com/45283242/58541583-679d9d80-822e-11e9-8600-f75681d28ced.png)

**Comment by philDTU** [comment]
Did you modify the taxonomy?
nodes.dmp
names.dmp

**Comment by gkarthik** [comment]
@hqtdave Were you able to resolve this issue?
I get the same error. I am trying to build the standard bacteria database along with a few new genomes added using `kraken2-build --add-to-library`.

**Comment by gkarthik** [comment]
Resolved. Problem was on my end. I didn't modify the taxonomy map after adding the new sequences.
Running `kraken2-build --download-taxonomy` resolved this issue.
