### ISSUE TITLE
Cropped text on your homepage due to a styling issue

### ISSUE THREAD

**Issue by ExplodingCabbage** [DerrickWood/kraken2#127]
This is how https://ccb.jhu.edu/software/kraken2/ looks to me:

![image](https://user-images.githubusercontent.com/2358339/58804673-57106d00-860a-11e9-9e8b-e6701c0b7abb.png)

Unfortunately I can't open a PR to fix it for you because the web page code doesn't seem to be on GitHub anywhere?

**Comment by jenniferlu717** [comment]
Thanks for letting me know. I just fixed/updated the website.
