### ISSUE TITLE
Can't find taxonomy/ subdirectory in database directory, exiting.

### ISSUE THREAD

**Issue by Bchristiaansen** [DerrickWood/kraken2#128]
Hi,

I managed to download the refseq library for bacteria with following command:
"$ kraken2-build --download-library bacteria --db refseq_bacteria"
But when I try to build the database with "$ kraken2-build --build --db . --threads 20"
I get following message: "Can't find taxonomy/ subdirectory in database directory, exiting."

Any ideas what might by causing this?

Thanks in advance,

Bart

**Comment by Bchristiaansen** [comment]
Nevermind, I forgot to do "$ kraken2-build --download-taxonomy --db $DBNAME"

**Comment by KHNAHTOE** [comment]
Thank you very much!
