### ISSUE TITLE
Kraken2 database RefSeq genome requirements 

### ISSUE THREAD

**Issue by tomdeman-bio** [DerrickWood/kraken2#131]
I have a question about the Kraken2 standard database built using: **kraken2-build --standard --db $DBNAME**

Is it true that only RefSeq genomes with a complete genome assembly level status (as listed in $DBNAME/library/bacteria/assembly_summary.txt), rather than with a contig or scaffold status, are included in the Kraken database?
Reason I'm asking is because I see certain taxa (dolosigranulum pigrum) in RefSeq but those taxa are absent from the Kraken2 database.

Thanks for your help,

**Comment by jenniferlu717** [comment]
Yes this is correct. In our experience, complete or chromosome level genomes are included as contig/scaffold genomes may contain contamination. You can modify the download script to include contigs/scaffolds but this may/probably will increase false positives.
