### ISSUE TITLE
How can I install it?

### ISSUE THREAD

**Issue by Cuppaaaa** [DerrickWood/kraken2#132]
When I used "unzip kraken2-master", it would have a file folder named "kraken2-master", but when I used "./install_kraken2.sh", it won't work...
![image](https://user-images.githubusercontent.com/50099338/59832425-6d425b00-9376-11e9-9628-b7cf04099dbf.png)

**Comment by edawine** [comment]
@Cuppaaaa you need at least GCC 4.8.1 to install
