### ISSUE TITLE
kraken2 databases

### ISSUE THREAD

**Issue by golden75** [DerrickWood/kraken2#133]
it seems the ftp site for downloading the databases for kraken2 is not working.
ftp://ftp.ccb.jhu.edu/pub/data/kraken2_dbs/minikraken2_v1_8GB_201904_UPDATE.tgz

or any other links for downloading is not working

**Comment by jenniferlu717** [comment]
I just checked and they seem to be working? How are you accessing them?

**Comment by golden75** [comment]
I used `wget` to download the databases the other day, and only i could download the version 2 after lot of tries.
I tried today and it seems to be working. 
Thank you very much.
