### ISSUE TITLE
creating the standard database

### ISSUE THREAD

**Issue by golden75** [DerrickWood/kraken2#134]
Hi,
I have used the `kraken2-build` command to download the standard database using:  
`kraken2-build --standard --threads 8 --db standard`   

Which downloaded the following libraries 
```standard/library/
├── archaea
├── bacteria
├── human
├── UniVec_Core
└── viral
``` 

As it downloaded the UniVec_Core library, and according to the manual it says when you download the **UniVec_Core** it says its incomplete with out the `--protein` option.  

So my question is when I use the command `kraken2-build --standard --threads 8 --db standard` is this incompete since i did not use the `--protein` option ?  (since I am intending to create the genome database using the `--standard` option.) . 

Thanks

**Comment by jenniferlu717** [comment]
The manual says that they are incompatible, not incomplete (as in the UniVec Core library cannot be used with the protein option) So you should be fine.
