### ISSUE TITLE
Fungi database problems

### ISSUE THREAD

**Issue by mdtorohernando** [DerrickWood/kraken2#137]
Dear developer, I'm trying to build the fungi database. I've downloaded files from 

`kraken2-build --download-library fungi --db fungi
`
But when I performed `kraken2-build --build --db fungi ` it appears an error: 

> Can't find taxonomy/ subdirectory in database directory, exiting.

The tree file is the following one: 

fungi/
└── library
    └── fungi
        ├── assembly_summary.txt
        ├── library.fna
        ├── library.fna.masked
        ├── manifest.txt
        └── prelim_map.txt

Thanks in advance

**Comment by mdtorohernando** [comment]
I found my mistake of not downloading NCBI taxonomy with this
`kraken2-build --download-taxonomy --db viral
`
but I find a new problem 

> Downloading nucleotide est accession to taxon map...rsync: link_stat "/taxonomy/accession2taxid/nucl_est.accession2taxid.gz" (in pub) failed: No such file or directory (2)
> rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1655) [Receiver=3.1.1]

**Comment by mkazanov** [comment]
I had the same problem with `rsync`.
Tried --use-ftp options, but it does not works for me:
https://github.com/DerrickWood/kraken2/issues/136

**Comment by mlf290** [comment]
I am also getting this same error. I can download kraken1 database without issue using a similar command. Is this a known bug?

**Comment by jenniferlu717** [comment]
If you can download the taxonomy using kraken 1's code, you can build with kraken2 without a problem. Try downloading the taxonomy with kraken 1?

**Comment by mdtorohernando** [comment]
It works in that way. Thanks!
