### ISSUE TITLE
Missing annotations when using pre-compiled database

### ISSUE THREAD

**Issue by UriaMorP** [DerrickWood/kraken2#138]
Hey,
After reading [this](https://www.biorxiv.org/content/10.1101/712166v1) work by Méric et al, I referred their github page and download the pre-compiled NCBI_r88_Human17k DB for kraken2 (https://monash.figshare.com/projects/Metagenomics_Index_Correction/65534).

When I tried to run kraken2 command to classify reads using this reference db, I got this rather strange mpa-style report, here are few lines of it:
```
d__|p__|c__|o__|f__     105114
d__|p__|c__|o__|f__|g__ 105105
d__|p__|c__|o__|f__|g__|s__     104267
d__|p__|c__|o__|f__|g__|s__     79
d__|p__|c__|o__|f__|g__|s__     12
d__|p__|c__|o__|f__|g__|s__     7
d__|p__|c__|o__|f__|g__|s__     6
d__|p__|c__|o__|f__|g__|s__     6
d__|p__|c__|o__|f__|g__|s__     6
d__|p__|c__|o__|f__|g__|s__     5
```

It occurred using both 2.0.8 and 2.0.7 kraken2 versions. The command for classification was:
```
kraken2 --db [path_to_NCBI_r88_Human17k] --output [kraken_output_path] --report [report_path] --use-names --use-mpa-style [fastq.gz]
```

I don't know if this is a reference issue, i.e, something wrong with the compilation of the DB, or a kraken2 issue, so I also raised this issue in the [publication's repo issues page](https://github.com/rrwick/Metagenomics-Index-Correction/issues/1#issue-473357100).

Is there anything I can do in order for this to work?

**Comment by tseemann** [comment]
This is not an error, these are the way names are used by GTDB https://gtdb.ecogenomic.org/

**Comment by jenniferlu717** [comment]
I am assuming this has to do with either GTDB and not a kraken2 issue, so I will close this issue for now.
