### ISSUE TITLE
kraken2_threading_error

### ISSUE THREAD

**Issue by NikZemp2** [DerrickWood/kraken2#139]
Hi Derrick,
I have an issue regarding multiple threading in kraken2. We could successfully installed the current git hub version on our cluster (gcc/4.8.2, CentOS Linux release 7.5.1804 ). We then tried to use multiple threads for building the database, however, I get an the following error massage:
…..
build_db: OMP only wants you to use 1 threads
xargs: cat: terminated by signal 13

Everything works fine If I use 1 CPU or if I use multiple CPUs on our old linux server. 
Do you know what could be the problem? 

Many thanks for your help in advance. 
Nik

**Comment by bishopia** [comment]
I get the same error, assigning 36 threads:

```
Building database files (step 3)...
build_db: OMP only wants you to use 3 threads
xargs: cat: terminated by signal 13
```

Also, if there is an easy way to fix this, is there a way to implement it w/o having to download libraries and taxonomy again? currently i'm running the following:

```
$KRAKEN/kraken2-build --standard --threads $THREADS --db standard_db
```

**Comment by jenniferlu717** [comment]
The program is detecting that the computer you are running on only has 1 thread so you cannot specify more than one.

**Comment by mohhefny** [comment]
Dear all,
I am sure that I have many threads and I still get the same error message! Is there a solution for this?

**Comment by callamartyn** [comment]
I am also getting this error and am sure I have many threads available. Any workaround?

**Comment by mohhefny** [comment]
> I am also getting this error and am sure I have many threads available. Any workaround?

You may try to add this line to the job script

`export OMP_NUM_THREADS= XXXX` 

replace XXXX with the number of threads
