### ISSUE TITLE
Custom databases: lookup_accession_numbers.pl very slow

### ISSUE THREAD

**Issue by thbtmntgn** [DerrickWood/kraken2#14]
I'm currently trying to build a custom database but the `lookup_accession_numbers.pl` script seems to take a very long time to retrieve taxids.

I looked at the `lookup_accession_numbers.pl` code and it seems the problem is similar to the one I had with the `lookup_accession_numbers.pl` script in Kraken [#94](https://github.com/DerrickWood/kraken/issues/94)

Currently you are:
**1)** Adding each accession number from the lookup list to a Perl hash
**2)** Reading each *.accession2taxid NCBI file line by line and extract taxids if corresponding accession numbers are in the hash build in **1)**

**Do you think doing the opposite can be faster?**
**1)** Creating a Perl hash based on each *.accession2taxid NCBI file
**2)** Reading the accession number lookup list line by line and extract corresponding taxids in the hash build in **1)**

There is currently 674 511 357 entries in the *.accession2taxid NCBI files (downloaded with `kraken2-build --taxonomy --db krakendb` today) and it guess that the lookup list will always be smaller right?

**Comment by DerrickWood** [comment]
I think the issue may be related to me doing something stupid on line 44 of that script: https://github.com/DerrickWood/kraken2/blob/d6ecc5c43fc7a6aa0061cafe016764dae5a21ce0/scripts/lookup_accession_numbers.pl#L44

If you replace that line of code with `if (exists $target_lists{$accession}) {`, do you see things speed up appreciably?

To answer your question directly, though, I don't believe that the opposite method would speed things up - that would be creating an even larger hash table, much of which won't be needed.

**Comment by thbtmntgn** [comment]
I just tested your idea, but results seems to be the same as you mentioned in your EDIT.

Good point, much of the hash won't be needed in the opposite method but in the current way, *.accession2taxid NCBI files will be read line by line until the last accession number is found and it seems to be very slow when you have a lot of accession number to look up.

I tried to build a custom database with 15 000 000 accession numbers yesterday and only 1 000 000 taxids were retrieved after after 24h.

*Is using a hash reference can be solution ?*

**Comment by DerrickWood** [comment]
I don't think that a hash reference would change anything here. This could be an argument for rewriting this in C++ and memory mapping, though, instead of using Perl for this script.

**Comment by DerrickWood** [comment]
I've just committed code (https://github.com/DerrickWood/kraken2/commit/80a87a9fb7ccc278cb8368a31c08a9dfa044afa4) that should help speed things up by converting the script to a C++ program; my tests show it working several times faster, but that's on a few toy examples and on my laptop. I'd appreciate you trying it out and hearing how it works for you.

**Comment by DerrickWood** [comment]
I've silenced most of the progress messages in the situation where you're redirecting STDERR to a file in https://github.com/DerrickWood/kraken2/commit/06370061f672237f1c07e5896f5050800df0339b
