### ISSUE TITLE
how to add new genome data to an existed database

### ISSUE THREAD

**Issue by yjk555** [DerrickWood/kraken2#143]
I have done the work of taxonomy download as well as add-to-library, and then I run the code to build the kraken2 database. The question is does this operation correct? Besides, how to check whether the new genomic data were added into the existed database?

**Comment by jenniferlu717** [comment]
Yes this is correct. you can check by simply trying to classify your genome against the database (kraken2 --db MYDB MYGENOME > TESTING.KRAKEN2)

**Comment by yjk555** [comment]
Great! I will have a try right now, thank you very much.
Cheers,
Jiangkun
