### ISSUE TITLE
Wrong path in cp command in docs/MANUAL.html

### ISSUE THREAD

**Issue by Aya-S** [DerrickWood/kraken2#147]
running 
`./install_kraken2.sh $KRAKEN2_DIR
`
Installed the files under $KRAKEN2_DIR directly and not in a bin folder so
`cp $KRAKEN2_DIR/bin/kraken2{,-build,-inspect} $HOME/bin
`
didn't work but 
`cp $KRAKEN2_DIR/kraken2{,-build,-inspect} $HOME/bin
`
did
so seems like the path in the manual needs adjustment

**Comment by jenniferlu717** [comment]
Thanks for noticing the issue. We'll make the change ASAP.

**Comment by DerrickWood** [comment]
Thanks, fixed in https://github.com/DerrickWood/kraken2/commit/e0d4fb0652a0d81e75396216be6d6f1673cca810
