### ISSUE TITLE
kraken2-build error

### ISSUE THREAD

**Issue by fengtong2018** [DerrickWood/kraken2#149]
when i use:
`kraken2-build --standard --db ~/software_database/kraken_db`
 i got error :
`software/conda2/libexec/standard_installation.sh: line 28: KRAKEN_WORK_ON_DISK: unbound variable`
i don't know what the problem is.

**Comment by jenniferlu717** [comment]
This might be more of a conda issue than a Kraken2 issue. We don't maintain the conda version of Kraken2 unfortunately.

**Comment by fengtong2018** [comment]
yes, you're right . 
it works when i install with the source.
thank you ~
