### ISSUE TITLE
Use local RefSeq to build database

### ISSUE THREAD

**Issue by ZeweiSong** [DerrickWood/kraken2#153]
Hi, 

If I have alread download the RefSeq data, is there a way I can skip the download part and go to build instead?

Thanks!

Zewei

**Comment by jenniferlu717** [comment]
If you already have the taxonomy, and all the refseq genomes in genomes/ 

`find genomes/ -name '*.fa' -print0 | xargs -0 -I{} -n1 kraken2-build --add-to-library {} --db $DBNAME`

or 

`for file in chr*.fa
do
    kraken2-build --add-to-library $file --db $DBNAME
done`
