### ISSUE TITLE
Match only to custom database and not NCBI taxonomy

### ISSUE THREAD

**Issue by KadenKing** [DerrickWood/kraken2#154]
Hello,

I'm trying to use Kraken2 with a custom database and somehow classify based on the sequence IDs of my custom database. The sequences in my database do not necessarily correspond to anything on NCBI, so the NCBI taxonomy is not helpful for my use case. 

I have tried annotating my custom database using my own tax ID using the `>sequence16|kraken:taxid|32630 ` syntax however that does not seem to give the desired result and it is still classifying sequences as a different tax id. 

Is there any documentation on creating a taxonomy that would allow me to classify input to sequence Ids in my database rather than NCBI tax ids? 

For further clarification:
If in my input database I have the sequence ID  `>sequence1|kraken:taxid|#` where there is no # on NCBI that exists for what I am trying to classify, would it be possible for the classification to point me to sequence1 instead of something on NCBI? Is it possible to create a custom taxonomy that would use the sequence IDs of our database instead of what is on NCBI?

**Comment by DerrickWood** [comment]
To create a custom taxonomy, you'll want to create `nodes.dmp` and `names.dmp` files in the database's `taxonomy/` subdirectory. They should be formatted in the same way that the various `build_*_taxonomy.sh` scripts create these files, with ID 1 being the root of the taxonomy, and ensuring that the nodes you put in the taxonomy form a tree. You'll also want to be sure that the taxids you assign to your sequences are within the taxonomy you've set up.

If you just want to add a little to the existing NCBI taxonomy, you could do that as well, by adding lines to the two `.dmp` files. You would just need to be sure you're still maintaining a tree structure as you do that.

**Comment by KadenKing** [comment]
Perfect thank you!
