### ISSUE TITLE
Bugs for downloading standard database with others database

### ISSUE THREAD

**Issue by Chiongchih** [DerrickWood/kraken2#155]
For building the standard database of kraken2: ./kraken2-build --standard --threads 24 --db...
Only Archaea is downloaded while other branches, such as bacterial, failed by output:
rsync: link_stat "/all/GCF/002/214/225/GCF_002214225.1_ASM221422v1/GCF_002214225.1_ASM221422v1_genomic.fna.gz" (in genomes) failed: No such file or directory (2)
Please help us to fix it, the standard database is crucial for kraken2. Thank you very much.

**Comment by jenniferlu717** [comment]
I'm not sure how recent this issue is, but the last time I tried downloading the standard, I did not get these errors. If they persist, please open another issue.
