### ISSUE TITLE
How to join the Kraken2 google group?

### ISSUE THREAD

**Issue by BioinformaticsBro** [DerrickWood/kraken2#157]
How can I get an invite from one of the admins? I can't join by myself.

**Comment by tseemann** [comment]
I didn't even know there was a google group. Can you link to the details you found?

**Comment by BioinformaticsBro** [comment]
https://groups.google.com/forum/#!topic/kraken-users/tPNkSwFRMX4

Or is this kraken totally unrelated?

**Comment by jenniferlu717** [comment]
We have decided not to continue responding to questions on the google group as its just easier to address/respond to issues on each github page. Thanks for the interest though

**Comment by nick-youngblut** [comment]
>We have decided not to continue responding to questions on the google group 

The manual still states:

>MacOS NOTE: MacOS and other non-Linux operating systems are not explicitly supported by the developers, and MacOS users should refer to the Kraken-users group for support in installing the appropriate utilities to allow for full operation of Kraken 2
