### ISSUE TITLE
Performance variations when running with memory-mapping option

### ISSUE THREAD

**Issue by clanzett** [DerrickWood/kraken2#158]
Hi,

i am running kraken with the memory-mapping option and am experiencing strange (at least for me) performance differences. The first run on a fresh booted machine takes about 3 minutes on a testfile with 20k reads. Running another testfile in a second run on the same machine, without having rebootet, the turnaround time keeps under 2 seconds! After a reboot the run takes again about 3 minutes. I am running on a machine with 8 Cores and 16 threads and my whole systems seems not to be stressed for 95% of the time. I am also using NVMe SSD storage and iostat is not showing a high load. In my opinion the reason is something inside the "Loading database" routine. 

Any suggestions?

**Comment by karolisr** [comment]
I am not associated with the project, but I took a glance at the code and may have the answer, authors may correct me if this is wrong:

>The first run on a fresh booted machine takes about 3 minutes on a testfile with 20k reads. Running another testfile in a second run on the same machine, without having rebootet, the turnaround time keeps under 2 seconds!

Based on this comment: https://github.com/DerrickWood/kraken2/blob/4f752ce909836de2a0bc098e568a598e5baaa3ed/src/mmap_file.cc#L64

Using the memory-mapping option, will use less memory by not loading the database into RAM. Instead the database is written to OS cache. This write operation will take time (the three minutes for you). When you run Kraken 2 without restarting your machine, since the database is already in OS cache, the write operation does not need to happen.

Which database are you loading? It's probably one of the larger ones if it takes three minutes on the machine with your specs.

**Comment by clanzett** [comment]
Yes i was/am looking at the same direction, but i dont know if there is a way to speed this up. 

I am using a custom database of about 40GB. Loading the database into RAM is not an option either, because this takes even longer. I need to find a way to make the first run faster.

**Comment by karolisr** [comment]
Hmm. It will be hard without using RAM. Is there a particular reason the first run needs to be fast? It seems like this would scale well if you keep reusing the same database.

**Comment by clanzett** [comment]
I am trying to run kraken as part of an autoscaling group which spins up new instances if i need to run more kraken jobs. But this leads to the problem that every first run on a fresh instance will be much slower and makes it difficult to scale the amount of instances according to the jobs in queue.

**Comment by karolisr** [comment]
It should be possible to create a VM image with pre-cached databases.

**Comment by clanzett** [comment]
In theory yes, but i dont know a way to create that image including the os caches.

**Comment by clanzett** [comment]
I could of course run a sample right after the new instance has come up, but this would also mean a  rather long spinup time for the new instance. (approx. 5mins)

**Comment by karolisr** [comment]
I don't know what setup you are using, but a snapshot of the OS file system could work as long as the snapshot is atomic (like ZFS does). This must be a solved problem, pre-caching happens in all sorts of situations. I just have never dealt with it.

**Comment by clanzett** [comment]
I will rethink my problem here, but thank you so much for your input!!!!

**Comment by yesimon** [comment]
You cannot snapshot/load the OS mmap cache because DRAM is volatile and does not get persisted anywhere. The networked EBS disk performance on AWS is poor compared to physical hardware, and takes a very long time to load the database the first time.

**Comment by clanzett** [comment]
No solution till now. Still working on it.

**Comment by joelwebb** [comment]
@clanzett  --- trying to solve a similar issue but just came across https://arxiv.org/pdf/2106.08150.pdf --- maybe this will be the solution to our problems?

**Comment by clanzett** [comment]
@joelwebb : thx, i will definitely take a look at it!
