### ISSUE TITLE
Taxonomy issues: Kraken2 mpa format vs Kraken2 format 

### ISSUE THREAD

**Issue by HitMonk** [DerrickWood/kraken2#159]
Hello,
So i was trying to use kraken2 on a bunch of demultiplexed paired end fastq files. I made a custom database comprising of the RDP database and the sequences from the [targeted loci database](https://www.ncbi.nlm.nih.gov/nuccore?term=33175%5BBioProject%5D+OR+33317%5BBioProject%5D). Everything worked well until i tried to match taxonomy to the OTU ids from the report. 

I am unable to match the OTU ids when using the --use-mpa-style flag. Is there anyway i can get a complete taxonomy? I have attached additional information below:

Report file results for Kraken2 classification:
fr_38.rep:  0.16         30       11      F       654               Oxalobacteraceae
fr_39.rep:  1.30        408     184     F       654               Oxalobacteraceae

Match in database using usual 
**COMMAND: kraken2-inspect  --db /exports/watson/Prateek/dbs/refseq_16s/16s_rdp+refseq/  | grep "654"**
0.34  128807  12764   F       654               Oxalobacteraceae

Match in database using --use-mpa-style
**COMMAND: kraken2-inspect --use-mpa-style  --db /exports/watson/Prateek/dbs/refseq_16s/16s_rdp+refseq/  | grep "654"**
d__Bacteria|p__"Proteobacteria"|c__Alphaproteobacteria|o__Rhodobacterales|f__Rhodobacteraceae|g__Loktanella     5654
d__Bacteria|p__"Proteobacteria"|c__Betaproteobacteria|o__Nitrosomonadales|f__Nitrosomonadaceae  34654
d__Bacteria|p__Firmicutes|c__Clostridia|o__Thermoanaerobacterales|f__Thermodesulfobiaceae       6549
d__Bacteria|p__Firmicutes|c__Bacilli|o__Bacillales|f__Planococcaceae|g__Kurthia 1654
d__Bacteria|p__"Bacteroidetes"|c__Cytophagia|o__Cytophagales|f__Cytophagaceae|g__Pontibacter    6548

Any advice from your end is highly appreciated to convert OTU identifiers into complete taxonomic records (as used in mpa format) from Kraken2 report.

**Comment by jenniferlu717** [comment]
I believe that the mpa style is only giving read counts per taxonomy, not taxids per taxonomy. 

However, this is something I will keep in mind as I'm developing the KrakenTools post-processing scripts.

**Comment by HitMonk** [comment]
Ah! Thank you! for the confirmation. Looking forward to using the post processing scripts!
