### ISSUE TITLE
Collapsing to species level?

### ISSUE THREAD

**Issue by tseemann** [DerrickWood/kraken2#16]
For Kraken 1 "classic" i asked if collapsing taxids to species level would save space (like centrifuge?). The answer was no. Is this still true for Kraken 2?

If no, is there any existing code to collapse a `--report` to `S` level ?

**Comment by DerrickWood** [comment]
Kraken 2 is similar to Kraken 1 in this respect; similar stretches of genomic sequence in two genomes will share the same minimizers and so no large space savings would be had. There might be occasional small differences in sister strains that would be collapsed away and save space there, but that's a lossy savings (i.e., an actual loss of sensitivity, not merely moving a minimizer's associated taxid up the tree).

Not sure how you'd want that collapse of the reports to go; something like this, maybe?

    perl -F"\t" -anle '$F[2] = $F[1] if $F[3] eq "S"; print join("\t", @F) if $F[3] !~ /S\d/' report.txt

That would silence the sub-species lines and treat the clade counts as taxon counts for species.
