### ISSUE TITLE
kraken 2 downloading database failed

### ISSUE THREAD

**Issue by jhcaddisfly** [DerrickWood/kraken2#161]
Hello,

I installed kraken 2 with bioconda and tried to download the standard database like this:
(kraken2) bash-4.2$ kraken2-build --standard --threads 64 --use-ftp  --db kraken_db

However, the command created a directory "kraken_db" with two subdirectories:
library and taxonomy
within library there are only two directories "bacteria" and "archae".
I got the following error message:

Step 1/2: Performing ftp file transfer of requested files
Step 2/2: Assigning taxonomic IDs to sequences
Processed 324 projects (513 sequences, 832.95 Mbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library... done.
Step 1/2: Performing ftp file transfer of requested files
Step 2/2: Assigning taxonomic IDs to sequences
Processed 16396 projects (35495 sequences, 65.85 Gbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library.../fslhome/fslcollab226/miniconda3/envs/kraken2/libexec/mask_low_complexity.sh: line 27: 48969 Killed                  $MASKER -in $file -outfmt fasta
     48971 Done                    | sed -e '/^>/!s/[a-z]/x/g' > "$file.tmp"

What can I do?

Thanks in advance!

**Comment by ym-chen** [comment]
Hello,
I met a similar error. The database download interrupted. The command line I used is:
kraken2-build --standard --threads 4 --use-ftp --db kraken_standard_DB

**Comment by 7670367** [comment]
I'm trying to build the kraken database using similar code, but I'm getting a different error. My code is: 
```
kraken2-build --standard --db test
```
and my error is:
```
Downloading nucleotide est accession to taxon map...rsync: link_stat "/taxonomy/accession2taxid/nucl_est.accession2taxid.gz" (in pub) failed: No such file or directory (2)
```
Issue #101 seems related, but I think the NCBI update is completed. Do you know how I can fix this? Thanks.

**Comment by AlBaarS** [comment]
Hello,

I am building a database and am experiencing (I think) the same issue;
`kraken2-build --download-taxonomy --db microbial-homemade/`
Output:
`Downloading nucleotide est accession to taxon map...rsync: link_stat "/taxonomy/accession2taxid/nucl_est.accession2taxid.gz" (in pub) failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1668) [Receiver=3.1.2]`
I have succesfully downloaded the referense sequences (using `--download-library`) earlier today and added them with `--add-to-library`. But downloading the taxonomy is giving me issues.

If it helps, I downloaded the bacterial, viral, archaeal, fungal and protozoal libraries.

**Comment by jenniferlu717** [comment]
The newest code should have fixed these issues. If there continues to be a problem, please open a new issue and provide the errors/code.
