### ISSUE TITLE
kmer size does not seem to be changing

### ISSUE THREAD

**Issue by mbhall88** [DerrickWood/kraken2#162]
Hi,

I am trying to build a 16S `--special silva` database with a kmer size of 21 but it does not seem to be building with the kmer size I set.

Example of how I build the database

```sh
kraken2-build --db data/kraken2_16s_db_k21 \
    --special silva \            
    --threads 16 \
    --kmer-len 21 \                            
    --minimizer-len 17 \                                      
    --minimizer-spaces 4 
```

However when I inspect the database it says that the kmer and minimizer lengths are k=35 and l=31

```sh
kraken2-inspect --db data/kraken2_16s_db_k21/ | head
# Database options: nucleotide db, k = 35, l = 31
# Spaced mask = 11111111111111111111111111111111111111110011001100110011001100
# Toggle mask = 1110001101111110001010001100010000100111000110110101101000101101
# Total taxonomy nodes: 13528
# Table size: 26477334
# Table capacity: 37889828
# Min clear hash value = 0
```

**Comment by mbhall88** [comment]
Ah, digging into this it seems that when you build a silva special database the kmer size from the build script does not get passed onto the actual build call

https://github.com/DerrickWood/kraken2/blob/376dcb0b7b1d9ebcd4e0113d1d908280578aeb82/scripts/16S_silva_installation.sh#L35

and therefore the default is being used.

**Comment by jenniferlu717** [comment]
Just by the way, we are aware of this issue and are looking to fix it in a more comprehensive manner across the scripts.

**Comment by DerrickWood** [comment]
This should be fixed as of commit https://github.com/DerrickWood/kraken2/commit/cb113f68cf3e78663eadcefc503633aed69c451c
