### ISSUE TITLE
potential code problems

### ISSUE THREAD

**Issue by rzolau** [DerrickWood/kraken2#163]
In compact_hash.cc:86:29: std::bad_alloc is intercepted by value. In classify.cc:314:44: sprintf expects unsigned long int, which commonly is 32bit (even on 64bit archs) and the passed argument is actually uint64_t.

**Comment by dfornika** [comment]
Just adding a couple links to make it easier to see the issue described above:

https://github.com/DerrickWood/kraken2/blob/4f73d69e75088e0e39021d1c6ab214a3c7b409ca/src/compact_hash.cc#L86

https://github.com/DerrickWood/kraken2/blob/4f73d69e75088e0e39021d1c6ab214a3c7b409ca/src/classify.cc#L314

**Comment by tseemann** [comment]
Nice find @dfornika - `uintXX_t` FTW

**Comment by DerrickWood** [comment]
These should be cleaned up as of https://github.com/DerrickWood/kraken2/commit/7127273c349991d5c031e126a747d4ce89fe7688 - thanks for pointing them out
