### ISSUE TITLE
dyld: Symbol not found: __ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev

### ISSUE THREAD

**Issue by EduanWilkinson** [DerrickWood/kraken2#165]
dyld: Symbol not found: __ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev
  Referenced from: /usr/local/Cellar/kraken2/2.0.8/libexec/classify
  Expected in: /usr/local/lib/libstdc++.6.dylib
 in /usr/local/Cellar/kraken2/2.0.8/libexec/classify
Abort trap: 6

Installed using home brew on Mac Pro

I'm not sure how to resolve this. Please advise

**Comment by DerrickWood** [comment]
Hi,

As noted in the manual, our ability to provide support for Mac installs is limited. In this case, what you're seeing appears to be a result of the home brew installation (which we don't control) either not checking for all needed dependencies or some sort of post-installation alteration of a dynamically loaded library. I'd recommend either installing from source directly or contacting the person who created the brew recipe (@tseemann I think).

**Comment by tseemann** [comment]
The brew recipe is fine. I think @EduanWilkinson has a problem with their installation. The first step is to fix all the problems `brew doctor` reports. Then `brew upgrade -v`. If that doesn't work, I would delete the whole `/usr/local` and re-install Brew.

**Comment by jenniferlu717** [comment]
closed this issue for now. If the problem persists, please open a new issue.
