### ISSUE TITLE
kraken2-experiment-code fails to build strex db

### ISSUE THREAD

**Issue by dpark01** [DerrickWood/kraken2#166]
@DerrickWood, this issue probably best belongs in [kraken2-experiment-code](https://github.com/DerrickWood/kraken2-experiment-code), but its archived status means I can't create new issues there.

I'm attempting to build the `strex` db using the provided [build script](https://github.com/DerrickWood/kraken2-experiment-code/blob/master/BuildScripts/build_kraken2.bash), but it appears to produce a 19GB database of *nothing* ("completed processing of 0 sequences, 0 bp"). Here is the output of `build_kraken2.bash` in my hands:

> Adding reference to Kraken 2 library
> Masking low-complexity regions of new file... done.
> Added "/data/RefData/strain_excluded.fna" to library (/data/Databases/Kraken2/strex)
> Running build program for Kraken 2
> Creating sequence ID to taxonomy ID map (step 1)...
> Sequence ID to taxonomy ID map complete. [0.017s]
> Estimating required capacity (step 2)...
> Estimated hash table requirement: 10078398168 bytes
> Capacity estimation complete. [1m4.808s]
> Building database files (step 3)...
> Taxonomy parsed and converted.
> CHT created with 14 bits reserved for taxid.
> Completed processing of 0 sequences, 0 bp
> Writing data to disk...  complete.
> Database files completed. [3m6.721s]
> Database construction complete. [Total: 4m12.389s]

The input fna file looks good and has 14297 sequences, and the resulting seqid2taxid.map looks well populated. The strex/library/added/(hash).fna file looks to be the same file size and probably identical to the input strain_excluded.fna file (with the exception of the line break width of the fasta sequences themselves, so I can't actually diff them). I'm not sure why the build processed no sequences.

If I `kraken2-inspect` this db, I get:

> \# Database options: nucleotide db, k = 35, l = 31
> \# Spaced mask = 11111111111111111111111111111111110011001100110011001100110011
> \# Toggle mask = 1110001101111110001010001100010000100111000110110101101000101101
> \# Total taxonomy nodes: 15231
> \# Table size: 0
> \# Table capacity: 2519599542
> \# Min clear hash value = 0

Note that that's the full output--no further lines after this because all taxa are zero. If I later try to classify the `accuracy_1.fq` and `accuracy_2.fq` reads against this, I, as you might expect, get nothing:

> Loading database information...
>  done.
> 50000 sequences (10.00 Mbp) processed in 0.798s (3757.7 Kseq/m, 751.54 Mbp/m).
>   0 sequences classified (0.00%)
>   50000 sequences unclassified (100.00%)

Here are the full steps to reproduce what I did from scratch:

1. Fire up a brand new VM in GCE (8 cores, 30GB RAM, 300GB main disk, Ubuntu 18.04 LTS)--presumably an EC2 Ubuntu VM would be equivalent but I haven't tried.
2. Run the following (maybe a script like this could be included or documented within kraken2-experiment-code also? I kind of figured this out as I went):

```
sudo apt-get update
sudo apt-get install -y git make gcc ncbi-blast+ g++ libiomp5 libiomp-dev

git clone https://github.com/DerrickWood/kraken2.git
git clone https://github.com/DerrickWood/kraken2-experiment-code.git
wget -O kraken2-reference-data.tar.gz https://zenodo.org/record/3365797/files/kraken2-reference-data.tar.gz?download=1
tar -xzpvf kraken2-reference-data.tar.gz
rm kraken2-reference-data.tar.gz

mkdir bin
cd kraken2
./install_kraken2.sh $HOME/bin
export PATH=$HOME/bin:$PATH

sudo mkdir /data
sudo chown `id -u -n` /data
cd /data
ln -s ~/kraken2-reference-data RefData
mkdir Programs; cd Programs
ln -s ~/bin k2-install

cd ~/kraken2-experiment-code/BuildScripts
# the next two lines ought to be a pull request on kraken2-experiment-code if it weren't archived
chmod a+x *.bash
sed -i 's/--threads 32/--threads `nproc`/g' *.bash
nohup ./build_kraken2.bash &
```

This will result in a `nohup.out` file that contains the output I quoted above.

I'm sure I'm missing something but I can't see what it is.

**Comment by DerrickWood** [comment]
Hi,

Thanks for bringing this to my attention. It may take me a little while to track the source of the problem down; could you give me the output of the following to help the process along?

- `head seqid2taxid.map`
- `head strex/library/added/*.fna`

Also, you may want to use the 2.0.8-beta version of Kraken 2 rather than just grabbing from the head of the repo; especially if you're trying to replicate things from the manuscript, some small changes have been committed since the 2.0.8 release.

**Comment by dpark01** [comment]
Thanks, no problem. Here are the outputs:

`head seqid2taxid.map`:
> 170018061|ref|NC_010468.1|kraken:taxid|481805	481805
> 38232642|ref|NC_002935.2|kraken:taxid|257309	257309
> 182682734|ref|NC_010579.1|kraken:taxid|405441	405441
> 182680572|ref|NC_010577.1|kraken:taxid|405441	405441
> 158421624|ref|NC_009937.1|kraken:taxid|438753	438753
> 566002026|ref|NC_023044.1|kraken:taxid|1379702	1379702
> 71277742|ref|NC_003910.7|kraken:taxid|167879	167879
> 296127869|ref|NC_014151.1|kraken:taxid|446466	446466
> 153011934|ref|NC_009670.1|kraken:taxid|439375	439375
> 153012113|ref|NC_009672.1|kraken:taxid|439375	439375

`head library/added/*.fna`:
> \>gi|170018061|ref|NC_010468.1|kraken:taxid|481805| Escherichia coli ATCC 8739 chromosome, complete genome
> TGTTTCAGCCTTAGTCATTATCGACTTTTGTTCGAGTGGAGTCCGCCGTGTCACTTTCGC
> TTTGGCAGCAGTGTCTTGCCCGATTGCAGGATGAGTTACCAGCCACAGAATTCAGTATGT
> GGATACGCCCATTGCAGGCGGAACTGAGCGATAACACGCTGGCCCTGTACGCGCCAAACC
> GTTTTGTCCTCGATTGGGTACGGGACAAGTACCTTAATAATATCAATGGACTGCTAACCA
> GTTTCTGCGGAGCGGATGCCCCACAGCTGCGTTTTGAAGTCGGCACCAAACCGGTGACGC
> AAACGCCACAAGCGGCAGTGACGAGCAACGTCGCGGCCCCTGCACAGGTGGCGCAAACGC
> AGCCGCAACGTGCTGCGCCTTCTATGCGCTCAGGTTGGGATAACGTCCCGGCCCCGGCAG
> AACCGACCTATCGTTCTAACGTAAACGTCAAACACACGTTTGATAACTTCGTCGAAGGTA
> AATCTAACCAACTGGCGCGCGCGGCGGCTCGCCAGGTGGCGGATAACCCTGGCGGTGCCT
> 

`cat library/added/*.fna | grep ^\> | head`:

> \>gi|170018061|ref|NC_010468.1|kraken:taxid|481805| Escherichia coli ATCC 8739 chromosome, complete genome
> \>gi|38232642|ref|NC_002935.2|kraken:taxid|257309| Corynebacterium diphtheriae NCTC 13129 chromosome, complete genome
> \>gi|182682734|ref|NC_010579.1|kraken:taxid|405441| Xylella fastidiosa M23 plasmid pXFAS01, complete sequence
> \>gi|182680572|ref|NC_010577.1|kraken:taxid|405441| Xylella fastidiosa M23 chromosome, complete genome
> \>gi|158421624|ref|NC_009937.1|kraken:taxid|438753| Azorhizobium caulinodans ORS 571 chromosome, complete genome
> \>gi|566002026|ref|NC_023044.1|kraken:taxid|1379702| Methanobacterium sp. MB1 complete sequence
> \>gi|71277742|ref|NC_003910.7|kraken:taxid|167879| Colwellia psychrerythraea 34H chromosome, complete genome
> \>gi|296127869|ref|NC_014151.1|kraken:taxid|446466| Cellulomonas flavigena DSM 20109 chromosome, complete genome
> \>gi|153011934|ref|NC_009670.1|kraken:taxid|439375| Ochrobactrum anthropi ATCC 49188 plasmid pOANT02, complete sequence
> \>gi|153012113|ref|NC_009672.1|kraken:taxid|439375| Ochrobactrum anthropi ATCC 49188 plasmid pOANT04, complete sequence

If you want to explore more for yourself, I'm able to repeatedly reproduce the described behavior within 15 mins on newborn VMs just using the above shell commands.

Will give 2.0.8-beta a try.

**Comment by DerrickWood** [comment]
That's probably enough for me; the error looks to be a result of a recent pull request that was merged in. The seqids in the `seqid2taxid.map` file aren't matching the seqids in the .fna file (the "gi|" is removed), which causes the classify program to not recognize the new sequences. This should not be a problem with 2.0.8.

**Comment by dpark01** [comment]
Excellent.. I'm rebuilding the db with 2.0.8 now and will report back.

**Comment by dpark01** [comment]
Works! Table size: 1764021644

> 50000 sequences (10.00 Mbp) processed in 0.930s (3225.2 Kseq/m, 645.04 Mbp/m).
>   44932 sequences classified (89.86%)
>   5068 sequences unclassified (10.14%)

Anyway looks like the current master HEAD has a bug worth fixing.

**Comment by DerrickWood** [comment]
Glad that's sorted out. Will revert the pull request shortly and figure out how to get the functionality of it in without breaking things. Thanks again for bringing this to my attention.
