### ISSUE TITLE
'Best' confidence threshold for general purpose classification?

### ISSUE THREAD

**Issue by BioinformaticsBro** [DerrickWood/kraken2#167]
I've seen conflicting information with regards to setting of confidence scores. Am I perhaps taking the following statements out of context? What's a good score that works for most circumstances?

"A filtering threshold of 0.05 was selected due to it showing the best precision/recall by the authors’ own measurements."
Simon, H. Ye, et al. "Benchmarking Metagenomics Tools for Taxonomic Classification." Cell 178.4 (2019): 779-794. 

![image](https://user-images.githubusercontent.com/37677948/66105416-01ff5a80-e5ee-11e9-96f6-30f6ea5e262e.png)

**Comment by jenniferlu717** [comment]
It depends on the context. Generally, I would go with 0.05 or 0.10 for general purposes. 

In the case where classifications with < 10 reads really affect the interpretation, I use a higher threshold of 0.5.

**Comment by rajukoorakula** [comment]
I completely agree with Jenniferlu717
