### ISSUE TITLE
Help building custom database from custom fasta file

### ISSUE THREAD

**Issue by marisalim** [DerrickWood/kraken2#169]
Hi,

I would like to build a custom kraken database using specific NCBI sequences for e.g., plants. I tried the RefSeq plant database, however it seems to consist primarily of agricultural species, and not species I'd expect to find in my samples. 

How can I incorporate the fasta file I download from NCBI into the kraken2-build steps after running the `--download-taxonomy` step? I'm not sure how to build the library.

Thanks!

**Comment by tseemann** [comment]
See https://github.com/DerrickWood/kraken2/blob/master/docs/MANUAL.markdown#custom-databases

**Comment by jenniferlu717** [comment]
`kraken2-build --add-to-library FILE.FA --db MYDB 
`

**Comment by Praneet-Prabhanjan** [comment]
Hello, I want to build a custom Kraken database for my 8 GB RAM local system. I need to run and analyze some metagenomic sample files. Can someone guide me and provide me with the commands to execute in the Miniconda environment?

Thank you.
