### ISSUE TITLE
How to get num of species?

### ISSUE THREAD

**Issue by flying-polarbear** [DerrickWood/kraken2#172]
Hi,
How can I know the database contains how many species?
For example, how many bacteria, virus, fungi etc.

**Comment by jenniferlu717** [comment]
We do not have a script for providing these numbers at the moment but you can classify everything in your library and get a report that will provide these values:

`kraken2 --db MYDB --threads THREADS ---report database.kreport2 <( find -L MYDB/library \( -name "*.fna" -o -name "*.fa" -o -name "*.fasta" \) -exec -cat {} + ) > database.kraken`

**Comment by deearahman** [comment]
Hello,

Can I check what is the MYDB/library?
