### ISSUE TITLE
Higher unclassified reads in updated MiniKraken2_v2_8GB_2019/04/23

### ISSUE THREAD

**Issue by rkendar** [DerrickWood/kraken2#174]
Hi Derrick,

Currently I am running kraken2 on 1 sample as a trial. And I noticed that I got more unclassified reads when I use the updated MiniKraken2_v2_8GB_2019/04/23 (~30%) compare to the previous MiniKraken2_v2_8GB_2018 (~2%). I used exactly the same parameter and sample for both run. Is this result expected? May I know what is the difference between the previous and updated DB version?

Thank you.

**Comment by jenniferlu717** [comment]
The newer database likely had far more genomes (as more bacterial/viral/microbial in general genomes are added into RefSeq overtime). To condense the genomes into 8GB, a smaller portion of each genome is actually able to be saved, making the unclassification rate increase. 

For example, if my sample has 10 species and the original database had 10 genomes, each 50% represented, then maybe I have 50% classification rate. But then over time, 90 more genomes were added that are different, so only 5% of each genome can be represented, so now I have a 5% classification rate. Hope that helps.
