### ISSUE TITLE
Different number of classified reads in the output and report files

### ISSUE THREAD

**Issue by apcamargo** [DerrickWood/kraken2#176]
I'm counting the number of unclassified reads in a Kraken2 run. When I count the number of "U" sequences in the output file, I get 41387496 reads. However, my report file puts 41270573 sequences in the root taxa. Summing up the reported percentages of classified and unclassified sequences doesn't add up to 100% (it gives me 99.87%).

The number of unclassified sequences is the same in both files.

Why is the report file missing some classified reads? This only happened when I used the "nt" database. Using the "environmental nt" gave me the expected results.

**Comment by jenniferlu717** [comment]
how are you calculating the number of "U" sequences? Can you provide the top 3 lines of the report file?

**Comment by apcamargo** [comment]
Here are the first three lines of my report file:
```
 54.71  50004168        50004168        U       0       unclassified
 45.16  41270573        138436  R       1       root
 44.82  40958023        1055604 R1      131567    cellular organisms
```

I don't have access to the output file right now, but as far as I remember I just counted the number of reads classified as `U`.

**Comment by jenniferlu717** [comment]
We are aware of this issue and are figuring out a solution. There are some reads in the kraken file that are labeled as "C" that are classified as 0 (unclassified) so that is the reason for the differences. but we are determining the cause and will provide a fix ASAP

**Comment by ciemanek** [comment]
Do you know how does that impact the report file that is used by Bracken? Does it have impact on abundances estimation?

**Comment by jenniferlu717** [comment]
It should not as far as I can tell so far.  I think it only affects the number of unclassified reads/artificial reads and neither of those numbers are used in Bracken's abundance estimation.

**Comment by apcamargo** [comment]
Hi @jenniferlu717! Do you got an update on this issue?

**Comment by jenniferlu717** [comment]
Sorry to everyone, we have fixed this problem @apcamargo 

The newest code has the fix, but I'm not sure if we made a new official release of it.

**Comment by apcamargo** [comment]
Thank you! Do you have plans for the next release?
