### ISSUE TITLE
Match to standard+bacteria+custom fasta files without NCBI taxnomony ID

### ISSUE THREAD

**Issue by yifengyuan** [DerrickWood/kraken2#179]
Hi, 
&nbsp;&nbsp;&nbsp;&nbsp; I am trying to do something similar with #154 . Since the majority of my reads failed to match to the standard database, I would like to add on the bacteria and my own reference genomes and build a custom database. I had my genomes in the format below and added in the custom database with --add-to-library command.
&nbsp;&nbsp;&nbsp;&nbsp; \> genomeID0123ABC456 | kraken:taxid | 0123fakeID456
AGTC......
&nbsp;&nbsp;&nbsp;&nbsp;I want Kraken2 to classify the input to the standard database or my genome IDs or fake taxid IDs. I mean,  I don't want to create NCBI taxonomy for my genomes. 
&nbsp;&nbsp;&nbsp;&nbsp;My questions are:
&nbsp;&nbsp;&nbsp;&nbsp;Shall I edit the nodes.dmp and names.dmp files in the database's taxonomy/ subdirectory like #154 mentioned? Can I proceed to build the database without add my genomes to the two .dmp files?
&nbsp;&nbsp;&nbsp;&nbsp;Thank you.

**Comment by jenniferlu717** [comment]
if those genome taxonomy IDs exist in the NCBI taxonomy, you won't need to edit/change the *.dmp files. If your reference genomes have corresponding organisms in NCBI, then you should be fine as long as you specify the right IDs. 

Otherwise, you will need to add those IDs to the dmp files.
