### ISSUE TITLE
kraken2-build for nr database (hash.k2d size too small?)

### ISSUE THREAD

**Issue by MetaQiime** [DerrickWood/kraken2#181]
Hello,
When I was building the nr database, this seemed to that it was done.
However, I find that the size of these 4 files seems too small?
seqidtaxid.map 8.87GB
taxo.k2d 89.71MB
opts.k2d 48.00 Bytes
hash.k2d 51.46KB
Would that be correct?
```
$ bsub -n 8 -I kraken2-build --build --db ~/Database/kraken2_nr --threads 16
Job <154056> is submitted to default queue <interactive>.
<<Waiting for dispatch ...>>
<<Starting on c01n05>>
Creating sequence ID to taxonomy ID map (step 1)...
Found 526675660/535774116 targets, searched through 805151865 accession IDs, search complete.
lookup_accession_numbers: 9098456/535774116 accession numbers remain unmapped, see unmapped.txt in DB directory
Sequence ID to taxonomy ID map complete. [59m51.944s]
Estimating required capacity (step 2)...
Estimated hash table requirement: 52660 bytes
Capacity estimation complete. [17m10.352s]
Building database files (step 3)...
Taxonomy parsed and converted.
CHT created with 21 bits reserved for taxid.
Completed processing of 163460797 sequences, 59728127620 bp
Writing data to disk...  complete.
Database files completed. [22m17.533s]
Database construction complete. [Total: 1h39m19.883s]
```

**Comment by jenniferlu717** [comment]
That is definitely not correct. How did you download the nr database/build it? Last time I tested this, the hash.k2d file is almost 90Mb. That is the file that I would consider the most important to test.

**Comment by jenniferlu717** [comment]
It may be that your taxonomy folder is out of date. If the taxonomy folder is not downloaded at the same time as the sequence files, some of the accession2taxid values may be incorrect and you will have missing sequences that Kraken 2 is not able to assign.

If kraken2 does not assign a taxonomy ID, it will not be able to use that sequence in building the database. I think the number of unmapped accession IDs is indicative of this.

I'm going to close this issue now. Please try and rebuild using a taxonomy folder downloaded on the same day as the sequences and if the issue persists, feel free to open a new issue.

**Comment by cm0109** [comment]
Hello, 

I am also trying to build the nr database, and I downloaded the taxonony IDs the same day as suggested above. My commands are as below:

`kraken2-build --download-taxonomy --db k2nr_jul2020/ --threads 42`
`kraken2-build --download-library nr  --protein --db k2nr_jul2020  --use-ftp --threads 42`
`kraken2-build --build --db k2nr_jul2020/ --threads 42`

The command line output from the --build command looks as below:

> Creating sequence ID to taxonomy ID map (step 1)...
Found 7913/539047623 targets, searched through 760966121 accession IDs, search complete.
lookup_accession_numbers: 539039710/539047623 accession numbers remain unmapped, see unmapped.txt in DB directory

Which is indicative that something is wrong. Any suggestions? 

Using version kraken2.0.9beta installed using Conda. Thanks!

**Comment by jenniferlu717** [comment]
It is not finding all of the accession IDs in the accession2taxid files. I did provide a separate script in KrakenTools (https://github.com/jenniferlu717/KrakenTools) called fix_unmapped.py. If you provide the unmapped.txt file and NCBI's accession2taxid files (ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/) then it can generate the seqid2taxid.map file you need.

If you already have a seqid2taxid.map file that is nonempty, simply take the output from fix_unmapped.py and cat (append) the files together.

**Comment by cm0109** [comment]
> https://github.com/jenniferlu717/KrakenTools

Thanks for the help. I followed your instructions for the fix_unmapped.py script and did this: 

`rm *.k2d 
mv seqid2taxid.map seqid2taxid_1.map
python fix_unmapped.py -i unmapped.txt --accession2taxid taxonomy/*accession2taxid -o seqid2taxid_temp.map
cat seqid2taxid_1.map seqid2taxid_temp.map
kraken2-build --build --db k2nr_jul2020/ --threads 42`

The python script ran succesfully. 
Unfortunately it is finding the exact same number of reads. Any idea what might be the issue here?

**Comment by mbshah** [comment]
> > https://github.com/jenniferlu717/KrakenTools
> 
> Thanks for the help. I followed your instructions for the fix_unmapped.py script and did this:
> 
> `rm *.k2d`
> `mv seqid2taxid.map seqid2taxid_1.map`
> `python fix_unmapped.py -i unmapped.txt --accession2taxid taxonomy/*accession2taxid -o seqid2taxid_temp.map`
> `cat seqid2taxid_1.map seqid2taxid_temp.map`
> `kraken2-build --build --db k2nr_jul2020/ --threads 42`
> 
> The python script ran succesfully.
> Unfortunately it is finding the exact same number of reads. Any idea what might be the issue here?

if you are still facing this issue, i believe you don't need to run kraken2-build again.

**Comment by arthurvinx** [comment]
Same problem here.

Code:

`kraken2-build --download-taxonomy --db kraken2/ --threads 30
kraken2-build --download-library nr --db kraken2/ --protein --threads 30
kraken2-build --build --db kraken2/ --threads 30
kraken2-build --clean --db kraken2/ --threads 30`

Results:

`ls -lh kraken2/
total 6,1G
-rw-r--r-- 1 diegomorais binfo  48K jan 28 03:13 hash.k2d
-rw-r--r-- 1 diegomorais binfo   64 jan 28 03:13 opts.k2d
-rw-r--r-- 1 diegomorais binfo  85K jan 28 03:03 taxo.k2d
-rw-r--r-- 1 diegomorais binfo 6,1G jan 28 01:56 unmapped.txt`

I will try the script suggested by @jenniferlu717.

**Comment by arthurvinx** [comment]
I tried the classification now, but no read was classified.

```
Loading database information... done.
507429 sequences (152.74 Mbp) processed in 18.891s (1611.6 Kseq/m, 485.11 Mbp/m).
  0 sequences classified (0.00%)
  507429 sequences unclassified (100.00%)
```

**Comment by jenniferlu717** [comment]
@arthurvinx Did you include the --protein command in your kraken2 run? 

@cm0109 Are you saying that the program is saying all of those reads are still unmapped? 
Also, the cat command should be: `cat seqid2taxid_1.map seqid2taxid_temp.map > seqid2taxid.map`

**Comment by arthurvinx** [comment]
Hi @jenniferlu717, I included the --protein.

The commands used are in the previous comment.

> Same problem here, took more than 24 hours and the resulting files map few identifiers.
> 
> Code for version 2.1.1 installed via conda with bioconda:
> 
> ```
> kraken2-build --download-taxonomy --db kraken2/ --threads 30
> kraken2-build --download-library nr --db kraken2/ --protein --threads 30
> kraken2-build --build --db kraken2/ --threads 30
> kraken2-build --clean --db kraken2/ --threads 30
> ```
> 
> Results:
> 
> ```
> ls -lh kraken2/
> total 6,1G
> -rw-r--r-- 1 diegomorais binfo  48K jan 28 03:13 hash.k2d
> -rw-r--r-- 1 diegomorais binfo   64 jan 28 03:13 opts.k2d
> -rw-r--r-- 1 diegomorais binfo  85K jan 28 03:03 taxo.k2d
> -rw-r--r-- 1 diegomorais binfo 6,1G jan 28 01:56 unmapped.txt
> ```
> 
> I will try the script suggested by @jenniferlu717.
> 
> Edit: After the fix_unmapped.py
> 
> ```
> ls -lh
> total 16G
> -rw-r--r-- 1 diegomorais binfo  48K jan 28 03:13 hash.k2d
> -rw-r--r-- 1 diegomorais binfo   64 jan 28 03:13 opts.k2d
> -rw-r--r-- 1 diegomorais binfo 7,6G jan 28 20:13 seqid2taxid.map
> -rw-r--r-- 1 diegomorais binfo 1,5G jan 28 20:13 still_unmapped.txt
> -rw-r--r-- 1 diegomorais binfo  85K jan 28 03:03 taxo.k2d
> -rw-r--r-- 1 diegomorais binfo 6,1G jan 28 01:56 unmapped.txt
> ```

**Comment by jenniferlu717** [comment]
Oh you should also be using --protein when you run `kraken2-build --build`: 

`kraken2-build --build --db kraken2/ --threads 30 --protein`

**Comment by andreott** [comment]
> Oh you should also be using --protein when you run `kraken2-build --build`:
> 
> `kraken2-build --build --db kraken2/ --threads 30 --protein`

I think the critical part is to apply the `--protein` option already for the `--download-taxonomy` job. Otherwise it will fetch the nucleotide _accession2taxid_ files from Ncbi - leading to the problem of unmapped ids
