### ISSUE TITLE
Unpaired reads support 

### ISSUE THREAD

**Issue by LeonardosMageiros** [DerrickWood/kraken2#185]
Hi, 

I would like to ask if there is any way to add the unpaired reads (after QC) along with the two pair end reads files to a single Kraken2 command?

Thank youfor your time 
Leonardos

**Comment by tseemann** [comment]
I don't think this is possible with the current software.

**Comment by jenniferlu717** [comment]
You can concatenate the paired end reads using "x" or "N" and add that to the unpaired reads file. The final file can then be put into kraken2, but otherwise, you cannot provide all three files to kraken2.

**Comment by tseemann** [comment]
@LeonardosMageiros  do you have only R1 and R2 after QC, but some are missing their mate?
