### ISSUE TITLE
Filtering out reads 

### ISSUE THREAD

**Issue by zmunro** [DerrickWood/kraken2#191]
I am trying to filter out all reads that are not classified by kraken as being Bacterial. 
I am using a custom built database that includes Human, Fungi, Bacteria, and Viruses. I want to run Kraken using this database, see what the distribution of reads are among these groups, and then filter the fastq file that I originally gave Kraken so that it only contains reads that were classified as some type of bacteria.

**Comment by jenniferlu717** [comment]
I've developed "extract_kraken_reads" to help with this: https://github.com/jenniferlu717/KrakenTools 

You can either specify the bacteria taxon and use --include-children/--exclude to remove everything that is bacteria or just --include-children to keep everything that is bacteria

**Comment by maxmaronna** [comment]
In case I just want those reads not identified (unclassified) as output, should I use "-t 0 --exclude -children"? Thanks in advance.

**Comment by jenniferlu717** [comment]
Just -t 0 for unclassified
