### ISSUE TITLE
Identify IDs in unmapped.txt

### ISSUE THREAD

**Issue by yifengyuan** [DerrickWood/kraken2#194]
Dear developers,

I am using the latest version of kraken2 on centos 6. 

I have built a database containing archaea, bacteria, human, fungi, viral, nt, env_nt, plant, plasmid. 

$ kraken2-build --build --db yyDB --threads 12
>Creating sequence ID to taxonomy ID map (step 1)... 
Found 185976536/188119403 targets, searched through 731540803 accession IDs, search complete. 
lookup_accession_numbers: 2142867/188119403 accession numbers remain unmapped, see unmapped.txt in DB directory 
Sequence ID to taxonomy ID map complete. [2h59m46.829s] 
Estimating required capacity (step 2)... 
Estimated hash table requirement: 279036206808 bytes 
Capacity estimation complete. [2h7m52.301s] 
Building database files (step 3)... 
Taxonomy parsed and converted. 
CHT created with 21 bits reserved for taxid. 
Completed processing of 180371807 sequences, 517815760900 bp 
Writing data to disk...  complete. 
Database files completed. [17h46m57.583s] 
Database construction complete. [Total: 22h54m36.843s]

$ head inspect.txt 
>\# Database options: nucleotide db, k = 35, l = 31
\# Spaced mask = 11111111111111111111111111111111110011001100110011001100110011
\# Toggle mask = 1110001101111110001010001100010000100111000110110101101000101101
\# Total taxonomy nodes: 2008509
\# Table size: 48796748094
\# Table capacity: 69759051702
\# Min clear hash value = 0
100.00	727152292	15967220	R	1	root
 70.72	514277546	325660	R1	131567	  cellular organisms
 56.85	413416649	783182	D	2759	    Eukaryota
 36.23	263449598	62947	D1	33154	      Opisthokonta
 32.39	235541302	1885	K	33208	        Metazoa
 32.36	235288228	8661	K1	6072	          Eumetazoa
 32.06	233113266	185396	K2	33213	            Bilateria
 25.79	187550125	8797	K3	33511	              Deuterostomia
 25.45	185077858	2943	P	7711	                Chordata
 25.36	184386455	0	P1	89593	                  Craniata
 25.36	184386455	974	P2	7742	                    Vertebrata
 25.35	184338412	11139	P3	7776	                      Gnathostomata
 25.28	183793877	0	P4	117570	                        Teleostomi

$head unmapped.txt
>LL360647
LM490608
LM441550
LL808576
LL699003
LM706321
LM355199
LM059514
LK998875
LL995237

$tail unmapped.txt 
>LM721834
LL438687
XM_021932317
LL330264
LM753282
LK906747
LL121821
LK885224
LM134236
LL852573

I would like to identify the unmapped ones, and maybe remove them. How can I locate them in the library files? I could not find them in library.fna. Thank you.

If I search "LL360647" in NCBI, I can get:
>Anisakis simplex genome assembly, scaffold: ASIM_contig0030437
GenBank: LL360647.1
Record removed. This record was removed at the submitter's request. Please contact 
\>LL360647.1 Anisakis simplex genome assembly, scaffold: ASIM_contig0030437

Is it the sequence corresponding to the unmapped LL360647? How can I locate it in library.fna?

Best,
Yifeng

**Comment by valentinavan** [comment]
Hi,

Did you figure this out?

I created a custom database and I got the unmapped.txt file with a long list of accession numbers. 

I would like to know **1)** how to find the taxa that have been successfully included in this db and **2)** if there is another way to include the excluded one.

Thanks

**Comment by AzizHN** [comment]
Hello @valentinavan, @yifengyuan .
Did you figure this out ? I am facing the same problem and I have a large unmapped.txt file

**Comment by yifengyuan** [comment]
Hi,

It has been a while. I don’t recall all details. It works well for me with a more recent version of kraken2 and carefully re-formated custom database. I created entries for names.dmp, nodes.dmp, seqid2taxid.map file and convert all sequences into >kraken:taxid|12345678|sequen1 format.

Best,
Yifeng

**Comment by valentinavan** [comment]
Hi I do not remember well neither now but I gave up using this tool...it did not work for me and I think that Kraken2 at that time was not working well if using a Mac system like I do.
