### ISSUE TITLE
Running kraken on RNA-seq

### ISSUE THREAD

**Issue by gevro** [DerrickWood/kraken2#196]
HI, Does Kraken work properly on RNA-seq data? Does Kraken attempt to map kmers in both directions (regular and reverse complement)? Since RNA reads might come from either strand of the reference.
Thanks.

**Comment by DerrickWood** [comment]
Yes, Kraken is intended to work with DNA input and so also has to handle the possibility of data from either strand being read there. Kraken does NOT differentiate between forward and reverse strand data, however, so you will not be able to get or use any sort of strand-specific information. If that's needed for your analysis, Kraken alone may not be the correct tool.

**Comment by laurakorobkova** [comment]
Hello @DerrickWood,  Can you please elaborate on your comment "Yes, Kraken is intended to work with DNA input". If I have RNA sequencing data (cDNA reads) can I still apply Kraken + Bracken  to estimate bacterial abundance in a sample? Thank you

**Comment by herokoking** [comment]
@laurakorobkova , I don't think Kraken2 + Bracken can work with cDNA reads due to it's k-mer database

**Comment by vebaev** [comment]
@herokoking you mention kraken2 cannot wwork with RNA seq data, strange as I see papers published with RNA, like:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8268838/

**Comment by nikyk** [comment]
Kraken2 appears to be capable of working with RNA-Seq, see review in Nature:
[https://pubmed.ncbi.nlm.nih.gov/34552145/](https://pubmed.ncbi.nlm.nih.gov/34552145/)

**Comment by Z-YWJ** [comment]
Thank you
