### ISSUE TITLE
Important BUG - inconsistent annotation order

### ISSUE THREAD

**Issue by gevro** [DerrickWood/kraken2#197]
Hi,
There is a major bug in kraken2 2.0.8. The order of the taxonomy that is output in the final report is not consistent between samples when using the --report-zero-counts option. I'm not sure why the order is changing in the reports, but it makes me question whether the results are accurate. Can you please investigate this?

**Comment by DerrickWood** [comment]
Are you expecting the report order to be the same when using `--report-zero-counts`? That option only provides line output for taxa with counts of zero, and has no effect on line order. From the manual:

> By default, taxa with no reads assigned to (or under) them will not have any output produced. However, if you wish to have all taxa displayed, you can use the `--report-zero-counts` switch to do so. This can be useful if you are looking to do further downstream analysis of the reports, and want to compare samples. Sorting by the taxonomy ID (using `sort -k5,5n`) can provide a consistent line ordering between reports.

There is no guarantee that line ordering will be the same between different samples. This is not a bug.

If I've misinterpreted your concern, please provide an example that can clarify it for me.

**Comment by gevro** [comment]
I see thank you. I think consistent line ordering might be better by default when '--report-zero-counts' is used, since the only reason people will use --report-zero-counts is for cross-sample comparisons.
