### ISSUE TITLE
kraken2 falied to download database 

### ISSUE THREAD

**Issue by neptuneyt** [DerrickWood/kraken2#198]
Kraken version 2.0.7-beta
commmand line:
nohup kraken2-build --download-library human --db ./Kraken2_Database/ --threads 40 &>./kraken2-build_human.log &
Retrun errors:
Step 1/2: Performing rsync file transfer of requested files
rsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at rsync.c(638) [generator=3.1.2]
rsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at io.c(504) [receiver=3.1.2]
rsync_from_ncbi.pl: rsync error, exiting: 5120
rsync: [receiver] write error: Broken pipe (32)
any suggesting?

**Comment by jenniferlu717** [comment]
I would try using --use-ftp when downloading the library?

**Comment by nankaiwolf** [comment]
I use https://github.com/mw55309/Kraken_db_install_scripts to download the databases of kraken, and of course, i adjusted some codes.

**Comment by nankaiwolf** [comment]
however, i haven't built the hash table yet, still downloading databases.

**Comment by BenLangmead** [comment]
I agree with using `--use-ftp`, which generally bypasses intermittent issues with rsync from NCBI.  I will close for now but feel free to reopen if you see consistent issues.
