### ISSUE TITLE
How to get mapping information ？

### ISSUE THREAD

**Issue by chenbt-hz** [DerrickWood/kraken2#199]
I want to get the position information of each classified read mapped to the reference genome, and I have extracted all classified reads. I use the “minikraken2_v2_8GB_201904_UPDATE” database. But I don't know how to look at the reference sequence information for each specific species in the database.

Maybe someone knows how to parse the binary database or get the location of the reference sequence on each read alignment directly.

I would be grateful if you could give me any help or advice.

**Comment by tseemann** [comment]
@MethTo This is not possible. The kraken2 database stores only k-mers and their associated taxid. It does not have any record of where in the original genomes they came from (and the same kmer could be in many genomes).
