### ISSUE TITLE
How was MiniKraken database created?

### ISSUE THREAD

**Issue by mw55309** [DerrickWood/kraken2#207]
My question relates to the MiniKraken database available on the kraken2 website

I ask because when I create my own RefSeq database, I get several species level hits to e.g. "[human gut metagenome](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=408170)" or "[marine metagenome](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi)"

These are kind of awkward classifications because they have a species level rank, but then every classification level above them has "no rank". They kind of mess with Kraken results a little but because you see a massive spike in species level classifications, but not at the other levels.

However, back to MiniKraken - they do not appear in the MiniKraken results.

So either you removed them, or they weren't in the version of RefSeq you created MiniKraken from.

Do you know which it is?

Could you provide an exact recipe (and RefSeq version) for how MiniKraken for Kraken2 was created?

**Comment by jenniferlu717** [comment]
What does your refseq database include?

Minikraken is Refseq complete bacteria, viral, archaeal, and human sequence and the UniVec Core sequence. We did not remove any specific levels or sequences. 

The exact code is:
`kraken2-build --db minikraken --download-library bacteria`
`kraken2-build --db minikraken --download-library archaea`
`kraken2-build --db minikraken --download-library human`
`kraken2-build --db minikraken --download-library viral`
`kraken2-build --db minikraken --download-library UniVec_core`
`kraken2-build --db minikraken --build --max-db-size 8000000000` for 8GB

The databases were built in April 2019, but I do not have the exact RefSeq version I used.

**Comment by mw55309** [comment]
Thanks @jenniferlu717 !

Is there a way to see either (i) the accessions, or (ii) the taxids that went into making the minikraken db, or in the downloads that preceded the build?

Do you still have the downloads?

**Comment by jenniferlu717** [comment]
I should have them and might be able to make a list for users. I'll try to put one together tonight.

**Comment by jenniferlu717** [comment]
I created a new minikraken database ftp.ccb.jhu.edu/pub/data/kraken2_dbs/ 

Accessions and taxids are included in the seqid2taxid.map files provided.
