### ISSUE TITLE
Kraken2 cant find Prevotella copri 

### ISSUE THREAD

**Issue by khemlalnirmalkar** [DerrickWood/kraken2#209]
Hi, I used Kraken2 for my shotgun sequences and while checking i couldn't find Prevotella copri. Since i know that P. copri is present in my samples, its weird, why Kraken2 cant find it/
Please may i know, is there any possible reason?
Thanks,
Khem

**Comment by jenniferlu717** [comment]
There is not enough information in what you provided for me to determine the problem. What is the database that you are using?

**Comment by khemlalnirmalkar** [comment]
Hi, I used refseq database through Kraken2 for the taxonomy in my samples. But i couldnt find Prevotella copri. When I used metaphlan2, this bacteria is available.
Thanks

**Comment by isardi** [comment]
The Kraken2 standard database does not have the Prevotella Copri genome.  You have to add it your self.  I am trying to do that but I am having problems.  See issue #221.

**Comment by khemlalnirmalkar** [comment]
Oh, Thanks for the information.
I will try to add and but you find the way to add P. copri genome without any issue, please do share your knowledge with me.
Thanks, Cheers :)

**Comment by BenLangmead** [comment]
Issue has moved to #221, so I will close this for now
