### ISSUE TITLE
Kraken2 Version of Kraken-Translate

### ISSUE THREAD

**Issue by glickmac** [DerrickWood/kraken2#210]
The report file generated includes information of the taxa, however, I am looking for a file that includes full taxonomy and the sequence header

The output of kraken-translate is two columns (sequence header and taxonomic lineage):
>Seq1_Header        root;cellular organisms;Bacteria;Proteobacteria;Gammaproteobacteria;

What command do we use to create a file in kraken 2 that includes just the sequence header and classified taxonomic string?

**Comment by jenniferlu717** [comment]
Does kraken-translate not work directly on the kraken2 output as well? 

I might have a script that can do this in https://github.com/jenniferlu717/KrakenTools but if the kraken2krona script is NOT what you are looking for, let me know.

**Comment by glickmac** [comment]
Hi @jennifelu1717, this is nice, however the kreport2krona is not exactly what I am looking for. It does the job of expending the lineages, yet I want a table with the fasta sequence header and the taxanomic lineage as columns. I have information within my sequence headers that is import to the lineage.

**Comment by glickmac** [comment]
I tried kraken-translate on the kraken2 output and received the following error:
kraken-translate: command not found 

Was kraken-translate added into kraken2? The manual says the report flag has replaced the functionality, however, I will have to manually translate the tax ids to lineages in the full output and remove all the other kmer information. Maybe I will open this as an enhancement and add my eventual script including taxa database downloads as a separate function.

**Comment by microbialman** [comment]
This was also discussed here, I have a script that uses TaxonKit to do similar `https://github.com/DerrickWood/kraken2/issues/71`

**Comment by glickmac** [comment]
Thanks @microbialman! I will try to incorporate this into my workflow. I may reach out to you if I run into trouble, however, this seems to be exactly what I am looking for. I wish they would incorporate this into kraken2 as a parameter option.
