### ISSUE TITLE
limited to a single thread

### ISSUE THREAD

**Issue by MRRedlinger** [DerrickWood/kraken2#211]
I am attempting to build a database with the following command
$ kraken2-build --standard --threads 104 --db kraken2_stdDB 

However, currently dustmasker is the only process running and it seems to be limited to a single thread. From what I understand my compiler supports openMP, so I'm at the limit of my ability to troubleshoot the issue. 

System specs are as follows: Ubuntu 18.04 on an EPYC 7702p 
G++,GCC version 7.4.0

**Comment by MRRedlinger** [comment]
multi-threading is working for the build_db processes

**Comment by cduvallet** [comment]
Hi @MRRedlinger - did you take any steps to get the multi-threading working?

I'm facing the same problem, I'm on an r5.8xlarge AWS instance (32 vCPUs and 256 GB of RAM), running Ubuntu 18.04.3 LTS. According to the [kraken2 documentation](https://ccb.jhu.edu/software/kraken2/index.shtml?t=manual), that means my database should build in ~35 min.

I ran:

`kraken2-build --standard --threads 32 --db $DBNAME`

It's been going for about 3.5 hours now, and when I open up `htop` it looks like only one thread is being used for the `dustmasker` command. Any thoughts on what might be going on?

**Comment by MRRedlinger** [comment]
@cduvallet I did not find a solution to dustmasker running with only a single thread, and in the end I set the DB to build overnight and it had completed by morning. Thankfully, this shouldn't be an ongoing issue unless you need to constantly build a new database. 

Looking at the arguments that dustmasker accepts, it doesn't appear that multithreading is supported natively on dustmasker. While it seems that it should be possible to split up the sequences and run multiple dustmasker processes, that's not a solution that I was able to implement. Since I'm only a biologist that taught myself a little bash scripting and python, I'm not qualified to say if that's a viable option for a future release of Kraken2.

**Comment by cduvallet** [comment]
Ok, thanks! And yeah, agreed that it's not a huge problem since that step is only done once.

And actually just after posting my comment, the dustmasker step finished. Now I see that the process has moved on to the `build_db` step, which as you also noted is working well on multiple threads.

Not sure if checking this out will become a priority for the kraken2 team, but just for future reference for anyone who lands here: the dustmasker step did eventually complete, and in my case it took around 4 hours to move on to the next step.

**Comment by fanninpm** [comment]
Perhaps the approach taken by [centrifuge](https://github.com/DaehwanKimLab/centrifuge/) could be of use. `centrifuge-download` dustmasks the individual FNA files before (eventually) combining them all into an index. `kraken2-build`, on the other hand, does the combination step before dustmasking.
