### ISSUE TITLE
Missing temp files during custom database

### ISSUE THREAD

**Issue by austinjyoder** [DerrickWood/kraken2#213]
I have run the kraken2 kraken-build command for a custom database a couple times and keep getting this error: mv: cannot stat 'taxo.k2d.tmp': No such file or directory
Is there possibly something missing in my version of the script that creates .tmp files? Does this file need to be there in the first place? I have been stuck on this for about a week now.

**Comment by jenniferlu717** [comment]
Do you have the taxo.k2d file? What are the exact command lines that you ran? 

Prior to building, you should run:
`kraken2-build --download-taxonomy --db $MYDB`

**Comment by austinjyoder** [comment]
So I don't exactly know what I did differently but after a few tries it has completed the database. I did use the .k2d files from the standard database and that at least let my program finish. Once that worked I removed them and ran it again. I just got it to work recently and seems to be fine now.
