### ISSUE TITLE
paired and unpaired mode together

### ISSUE THREAD

**Issue by margeti** [DerrickWood/kraken2#214]
Is it possible to simultaneously classify paired and unpaired reads in one run, producing only one output file? 
I have paired end reads which partially overlap, so I merged them and they thus function as single ended reads. When I now classify my samples I have to run it twice for each sample, once with the merged samples in single-end mode and once with the unmerged samples in paired-end mode. Then I have to somehow merge the output afterwards to compare the classifications across samples...
Would be really cool jsut put them together in a single run, or (second best perhaps) be able to merge the outputs after classification.

**Comment by jenniferlu717** [comment]
I'm not sure exactly how you want to combine everything, but if this helps, the way that Kraken2 processes paired reads is by first concatenating them with "x" and then just running them the usual way.

What you can do then is make a combined "paired" file by concatenating the reads with an "x" in the middle and then just run:
`cat paired.fasta merged.fasta > newdata.fasta` and run that through kraken

**Comment by margeti** [comment]
Thank you! That solves my problem!

**Comment by juanjo255** [comment]
Hello @jenniferlu717,

Could you give me some details on how this concatenation must be done?

Would this work?

`
FFFFxFFFF
@R1x@R2
AAAxTTT
+
`
Thank you.
Juan
