### ISSUE TITLE
Can I use Kraken2 with NT database to analyse assembled metagenomic data ?

### ISSUE THREAD

**Issue by CaroleBelliardo** [DerrickWood/kraken2#215]
I have contig > 1000 pb and I want to identify which are from a eukaryotic or prokaryotic organism. Do you think I need to change default parameters?  Like K-mers size or others ? 
Thanks a lot for your help

**Comment by sconlan** [comment]
Hi, I'm just a random kraken2 user but maybe I can help. If you already have assembled contigs, I'm not sure that kraken is the optimal tool for your question*. The Banfield lab has a tool for this purpose: https://www.ncbi.nlm.nih.gov/pubmed/?term=29496730 . I've used it for separating bacterial contaminants from a eukaryotic genome assembly. Depending on the number of sequences you have and compute resources, you could also just use blast to find related sequences.

*You might have better luck with methodological and best practices questions at seqanswers or biostars.

**Comment by BenLangmead** [comment]
I agree with @sconlan.  If I understand your situation correctly, it's also possible you want to break the contig up into pieces first and query them.
