### ISSUE TITLE
library and taxonomy output directories 

### ISSUE THREAD

**Issue by JGorzynski** [DerrickWood/kraken2#217]
Hi,
I recently built a custom kraken databse with `--max-db-size 8000000000` as a communal tool to be kept it in a shared directory with very limited space. The .k2d files are nice and small but the library and taxonomy directories created in the build are very large - are these files necessary and is there any way to shrink these down? 

![image](https://user-images.githubusercontent.com/51088622/75148081-b06b7f80-56f6-11ea-945c-2b56f65ec716.png)

Classifying using a copy of the database with these files removed gives me this error `Loading database information...classify: Error reading in hash table`
Thanks, Jamie.

**Comment by sconlan** [comment]
Not sure if this helps... the build script has a --clean flag that seems to just call kraken/2.0.8-beta/bin/clean_db.sh . If you inspect that script it's running:

```
rm -rf library/ taxonomy/ seqid2taxid.map
```

It looks like you could just run that script manually and supply your database name. That said, it doesn't explain why you are getting an error be doing something similar. I would try this on a copy of the database while debugging.

**Comment by JGorzynski** [comment]
Thanks @sconlan  , problem solved! I think the error was introduced because of renaming my database when copying.

I had completely forgotten about the --clean command, thanks for investigating. I normally use it but without knowing how it works, I didn't put two and two together that that's what I was missing.
