### ISSUE TITLE
rsync 403 Forbidden error when using kraken2-build to download taxonomy

### ISSUE THREAD

**Issue by sconlan** [DerrickWood/kraken2#219]
Recently (in the last week?) the kraken2-build script is failing to download files via the default rsync method (I wasn't having this issue before):
```
09:56 cn3267 Trash$ kraken2-build --download-taxonomy --db ./
Downloading nucleotide gb accession to taxon map...bad response from proxy -- HTTP/1.1 403 Forbidden
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]
```

The raw rsync command also fails:
```
09:56 cn3267 Trash$ rsync --no-motd rsync://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/prot.accession2taxid.gz .
```
leading me to think it's some sort of change at NCBI. Note the the files are 1) where they are supposed to be at NCBI and 2) the --use-ftp flag allows you to successfully download the files.

related to this issue: https://github.com/DerrickWood/kraken/issues/114

**Comment by BenLangmead** [comment]
I have seen it too, but only intermittently.  If I try again several minutes later, I can often get it to work.  How consistent is it for you?

**Comment by sconlan** [comment]
It happened last week on Friday and then again this morning (so n=2). I assumed it was something on NCBI's end. The issue I linked to for kraken, also indicated it was intermittent. I think others in lab got it working.

I posted the issue just in case others were having this problem since --use-ftp is a workaround.

**Comment by BenLangmead** [comment]
Yes, I agree that `--use-ftp` is the right workaround.  Given that this seems to happen with some frequency, we'll consider whether we should make that the default.  Thanks for the report.
