### ISSUE TITLE
Problems adding genome to database - Prevotella Copri

### ISSUE THREAD

**Issue by isardi** [DerrickWood/kraken2#221]
Hi,
I am trying to add the Prevotella Copri genome into the Kraken2 database.  
I downloaded the genome from NCBI, and then changed all the sequence ID information to add the kraken:taxid.  The new fasta looks like this:

>NZ_GG703878.1|kraken:taxid|537011
AGTTCCTTAACCATGAATCTCTCAACGCCTTAGTATGTTCTACCCGACCACGTGTGTCCGTTTGCGGTACGGGTGCCGCA....
>NZ_GG703877.1|kraken:taxid|537011
CTCCTGCAGATGGTCGAGTGCATCCATCAGCACACCGTGGATGGTACCACGAGAGTATGGCGAGCCGTGGTCG...

There is a '>' in each line by the sequence ID, which is not showing up for some reason, but it is in the file.
I then followed the steps from the website:

kraken2-build --add-to-library PrevotellaCopri.fasta --db KrakenDB
kraken2-build --build --db KrakenDB

However, when I inspect the database I still can't find the Prevotella Copri genome.  I am inspecting the database using the kraken2-inspect --db KrakenDB command.

Not sure what I am doing wrong.  I would appreciate your help.

Thanks,
-Isabel

**Comment by jenniferlu717** [comment]
Is NZ_GG703878.1|kraken:taxid|537011 in the seqid2taxid.map file?

**Comment by isardi** [comment]
HI,

This problem was resolved.  I was able to add many more genomes.

Thanks!
-MIS

**Comment by khemlalnirmalkar** [comment]
> HI, This problem was resolved. I was able to add many more genomes. Thanks! -MIS From: Jen Lu <notifications@github.com> Sent: Thursday, April 9, 2020 10:08 PM To: DerrickWood/kraken2 <kraken2@noreply.github.com> Cc: Maria Sardi <Maria_Sardi@cargill.com>; Author <author@noreply.github.com> Subject: Re: [DerrickWood/kraken2] Problems adding genome to database - Prevotella Copri (#221) [EXTERNAL] This email came from outside of Cargill. Do not click links or open attachments unless you recognize the sender. If you suspect this is spam, send this email as an attachment to spam@cargill.com<mailto:spam@cargill.com> Is NZ_GG703878.1|kraken:taxid|537011 in the seqid2taxid.map file? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DerrickWood_kraken2_issues_221-23issuecomment-2D611855421&d=DwMCaQ&c=h2Fu29X6B8vuaRkwP4jdQg&r=9Nshnt4akjki4FQBlCG0eSWWiZqEiPZyrUmStHnUCbQ&m=K8f9-8WwLuaXmKcpOWlYZTwt2bl8m8wKCwNQIy2vMEM&s=TxIsZF648b2K7Ogeunp6x7qGo-qCGjh5ytu8YHuCpQ8&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AH25KPXWMUIUSDG5L324RETRL2EQNANCNFSM4K5ICLGA&d=DwMCaQ&c=h2Fu29X6B8vuaRkwP4jdQg&r=9Nshnt4akjki4FQBlCG0eSWWiZqEiPZyrUmStHnUCbQ&m=K8f9-8WwLuaXmKcpOWlYZTwt2bl8m8wKCwNQIy2vMEM&s=1tOy9ejGEb0LeAhH9mtNS_mRK8VZ9ljMFpiyg6pFViE&e=>.

Hi  @jenniferlu717 @isardi @DerrickWood 
I want to add Prevotella copri genome in my currently built kraken2 database.
I saw the above comment, but please can you explain how to start to add P. copri and what was the error and how to solve it?
I am newbie, should i download first P. copri from NCBI refseq in fast format? 
Thanks,
Khem

**Comment by isardi** [comment]
Hello Khem,

Yes, you need to download P. copri from NCBI.
All the intructions are in Kraken2 wiki
https://github.com/DerrickWood/kraken2/wiki/Manual#custom-databases

In the past, I had downloaded the pre-build database MiniKraken2. That is why I was confused before.  If you want to add another genome, you need to start from scratch, and rebuild the entire database, to add the P. copri.  The instructions are pretty good.  

Good luck!
