### ISSUE TITLE
kraken2-build not working with NCBI "env_nt"

### ISSUE THREAD

**Issue by gabyrech** [DerrickWood/kraken2#224]
Hi!
I am having problems for downloading the "env_nt" database using kraken2-build. 
First I tried with:
```
$ kraken2-build --download-library env_nt --db kraken2DBCustom20200228
Downloading env_nt database from server... rsync: link_stat "/db/FASTA/env_nt.gz" (in blast) failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1655) [Receiver=3.1.1]
```
But it doesn't work. I tried also with: (this one works for all the other dabases (nt, bacteria, etc...) 

```
$ kraken2-build --download-library env_nt --use-ftp --db kraken2DBCustom20200228
Downloading env_nt database from server... 

```
But it does nothing with the env_nt database.. any clue?

```
$ kraken2-build --version
Kraken version 2.0.7-beta
Copyright 2013-2018, Derrick Wood (dwood@cs.jhu.edu)
```
Thanks!

**Comment by jenniferlu717** [comment]
It seems like the env_nt file that the download script used to reference is no longer available in that folder. I will take a look to see if we can update the link

**Comment by jenniferlu717** [comment]
Apologies, I contacted NCBI, but they are no longer providing the env_nt database for download so we will have to remove that option. I think the nt database may be the closest option available.
