### ISSUE TITLE
kraken2 - wrong family name assigned when using the pre-build SILVA database

### ISSUE THREAD

**Issue by MariskaBeekman** [DerrickWood/kraken2#225]
I used the SILVA reference database to analyse my 16s sequences. When I look at the output I see that the genus Serratia and Providencia are both placed withing the Family Enterobacteriaceae. However, when I look into the actual SILVA database, Serratia belong to the family Yersiniaceae within the order of Enterobacteriales, and Providencia within the family Morganellaceae within the order Enterobacteriales. Is there maybe something wrong with the pre-build SILVA database or could something go wrong when making the output files? Thanks!

d__Bacteria | p__Proteobacteria | c__Gammaproteobacteria | o__Enterobacteriales | f__Enterobacteriaceae | g__Serratia

d__Bacteria | p__Proteobacteria | c__Gammaproteobacteria | o__Enterobacteriales | f__Enterobacteriaceae | g__Providencia

**Comment by jenniferlu717** [comment]
Ah, thanks for noticing this. It seems something happened when making the database itself. I'll take a look at our scripts for this.

**Comment by jenniferlu717** [comment]
oh, okay, this is really strange. It depends on what version of SILVA you are using. In SILVA_132, Serratia is assigned to Enterobacteriaceae: 
`Bacteria;Proteobacteria;Gammaproteobacteria;Enterobacteriales;Enterobacteriaceae;Serratia;  3523     genus           119`

However, in SILVA 138, Serratia is assigned to Yersiniacee: 

`Bacteria;Proteobacteria;Gammaproteobacteria;Enterobacterales;Yersiniaceae;Serratia;     46541genus           138`

I did provide both of these versions of the kraken2 database in our ftp download site: ftp.ccb.jhu.edu/pub/data/kraken2_dbs/ but they are performing based on the taxonomy provided.
