### ISSUE TITLE
Error during masking of low-complexity regions

### ISSUE THREAD

**Issue by jkin2003** [DerrickWood/kraken2#227]
running on cluster with following batch code:
#!/bin/bash
#SBATCH --time=04::00
#SBATCH --no-kill
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kinskeyj@usf.edu
#step 2 of kraken bacterial database installation

cd /work/k/kinskeyj/KrakenDownload/kraken2/scripts/

module purge
module load apps/blast/2.7.1
module load apps/perl/5.30.0
module load apps/miniconda/3.6.1
module load compilers/gcc/7.3.0

/work/k/kinskeyj/KrakenDownload/kraken2/scripts/kraken2-build --download-library bacteria --db /work/k/kinskeyj/KrakenDownload/bacteria_db

error output:
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library...dustmasker: error while loading shared libraries: libgnutls.so.26: cannot open shared object file: No such file or directory

**Comment by BenLangmead** [comment]
Looks like the BLAST tool dustmasker has a library dependency on a library called "gnutls" that's not installed on the worker nodes of your cluster.  I suggest contacting your cluster admins to see if they can install it.
