### ISSUE TITLE
rsync error with standard DB build

### ISSUE THREAD

**Issue by jkin2003** [DerrickWood/kraken2#229]
Input :
./kraken2-build  --standard --db /work/k/kinskeyj/standardDB 
I am getting the following error:
Masking low-complexity regions of downloaded library... done.
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library... done.
rsync: failed to connect to ftp.ncbi.nlm.nih.gov (130.14.250.7): Connection refused (111)
rsync: failed to connect to ftp.ncbi.nlm.nih.gov (2607:f220:41e:250::7): Network is unreachable (101)
rsync error: error in socket IO (code 10) at clientserver.c(122) [Receiver=3.0.9]
Error downloading assembly summary file for human, exiting.

**Comment by nankaiwolf** [comment]
my friend met this problem before, and I think the rsync server is down. However, I use ftp to download the database, and download hash table from LomanLab(https://lomanlab.github.io/mockcommunity/mc_databases.html).

**Comment by fungal-spore** [comment]
I had same problem this morning, you just need to add --use-ftp argument and it wont use rsync, mine is downloading right now :)

**Comment by jenniferlu717** [comment]
Please use the --use-ftp argument. We are looking into to switching the default download method for our scripts, but rsync and ftp will both be available as options. Some times rsync just does not work, though we do not have control over that.

If you continue to have problems even with the use-ftp argument, please open another issue.

**Comment by Maryamtarazkar** [comment]
I applied 
kraken2-build --standard –use-ftp --db ./Kraken2_Database
a " taxonomy" folder is created under Kraken2_Database. But the folder is empty. is that what it should be?
