### ISSUE TITLE
Improve instructions for converting existing database into kraken

### ISSUE THREAD

**Issue by kilojarek** [DerrickWood/kraken2#232]
Hi,

I would like to suggest improving/adding information to the manual on how to turn an existing database to kraken format. I think many users (i.e. me :-) have already a local BLAST+ database (e.g. nt) and it would be beneficial to add and/or clarify steps needed to use this existing database with kraken.

For example, it is unclear whether taxonomy and library folders need to be inside every database made. Let's say that I already have kraken2's default database, with its taxonomy and library folders. When I am making another database from existing BLAST+ nt database, how do I create a library folder for this database? And if I don't need to create it, can one library folder  be used for multiple database folders (in this case, can I use the kraken2's default database's library folder for my nt database?

It would be useful if kraken2-build had a parameter to skip downloading the genomic library and used one at specified path, but I don't know how feasible it is - it might be easier to improve the instructions :-)

**Comment by jenniferlu717** [comment]
`kraken2-build --build`  just requires that the library/ and taxonomy/ folders exist (sequences in the library/ folder, and taxonomy downloaded using `kraken2-build --download-taxonomy`). If you have an existing taxonomy folder, it should have the nodes.dmp/names.dmp files. 

If you are adding existing sequences to a library, two ways to make sure they are appropriately formatted is by:

1) Using the `kraken2-build --add-to-library $file` command to ensure that the seqid2taxid.map file can be generated or
2) making a seqid2taxid.map file where every sequence ID has a taxid assigned.
