### ISSUE TITLE
Segmentation error while running on one sample

### ISSUE THREAD

**Issue by AndreaQ7** [DerrickWood/kraken2#237]
Good evening everyone,
I am pretty new to kraken2. I have created my Custom DB and then I was running just one sample with the following string

kraken2 --db CustomDB filename.fastq.gz --gzip-compressed --output filename.kraken --report filename.report

But I get " Processed 11193243 sequences.....Segmentation error"

What does it means and how can i resolve it?
kraken2 is located under a specific environment  with conda in the server
thanks to anyone will help
Andrea

**Comment by maxibor** [comment]
See #222

**Comment by jenniferlu717** [comment]
Based on the recent updates from conda, the kraken2 install should be working now.

**Comment by AndreaQ7** [comment]
I did the update but i have the same problem as before

**Comment by AndreaQ7** [comment]
ok now there is another update and it seems to work well!!
