### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by davetang** [DerrickWood/kraken2#24]
In [Standard Kraken Output Format](https://github.com/DerrickWood/kraken2/blob/master/docs/MANUAL.markdown#standard-kraken-output-format), the line:

`For example, "562:15 561:4 A:31 0:1 562:3" would indicate that:`

should be:

`For example, "562:13 561:4 A:31 0:1 562:3" would indicate that:`

The HTML file has the same typo, since it was generated from the same Markdown file.

**Comment by DerrickWood** [comment]
Thanks, fixed in https://github.com/DerrickWood/kraken2/commit/48da133a39c666cc504f289b155773a63a127d63
