### ISSUE TITLE
Modifying taxonomy/nodes.dmp

### ISSUE THREAD

**Issue by ibharvey** [DerrickWood/kraken2#240]
I'm working with a set of subspecies not currently in public taxonomy databases. The README mentions that you can modify the taxonomy database manually by modifying the names.dmp, nodes.dmp, and seqid2taxid.map files. 

names.dmp and seqid2taxid.map are fairly straight-forward formats, but the nodes.dmp contains multiple undescribed columns. What do the integers in these columns represent?

**Comment by jenniferlu717** [comment]
1) taxid
2) parent taxid
3) rank type (superkingdom, genus, species, order, family, etc) 
4) n/a (I'm not sure but kraken doesn't use it for anything so just write '-') 

All separated by \t|\t (tab, vertical line, tab)

**Comment by jenniferlu717** [comment]
I'm going to close this issue. If you have additional problems, feel free to reopen this issue or open a new issue.
