### ISSUE TITLE
Classified file

### ISSUE THREAD

**Issue by SumTot** [DerrickWood/kraken2#243]

**Comment by jenniferlu717** [comment]
That is all from the FASTQ file. Its the copy/paste from the input sequence for a read that was classified.

**Comment by SumTot** [comment]
Thanks!;)
 I will close and delete this issue

**Comment by SumTot** [comment]
Sorry, just a last question. The input sequences that were classified, will they appear in the classified file as many times as reads have assigned?

**Comment by jenniferlu717** [comment]
Yes

**Comment by SumTot** [comment]
thanks!
