### ISSUE TITLE
failed to open the database URL

### ISSUE THREAD

**Issue by bitcometz** [DerrickWood/kraken2#244]
hello,

the database URL provided by the kraken2 website failed to be opened:

ftp://ftp.ccb.jhu.edu/pub/data/kraken2_dbs/

Could you help with this problem?

Thanks!!!

**Comment by LasKru** [comment]
hello,

i have the same problem with the URLs for the two minikraken2 dbs 
ftp://ftp.ccb.jhu.edu/pub/data/kraken2_dbs/minikraken2_v1_8GB_201904_UPDATE.tgz
ftp://ftp.ccb.jhu.edu/pub/data/kraken2_dbs/minikraken2_v2_8GB_201904_UPDATE.tgz

thanks in advance!

**Comment by jenniferlu717** [comment]
@bitcometz sometimes the ftp site goes down but it is back up now. @LasKru since I released a new minikraken db, the old ones have been moved to the kraken2_dbs/old/ folder.

**Comment by bitcometz** [comment]
Thanks for your help !!!
But I still  cannot open the URL:
ftp://ftp.ccb.jhu.edu/pub/data/kraken2_dbs/

Best
