### ISSUE TITLE
How to join custom databases?

### ISSUE THREAD

**Issue by MaryoHg** [DerrickWood/kraken2#25]
Hi, Dear Kraken Team.

I downloaded four libraries I'm interested to: archaea, bacteria, fungi and viral.

My question is:
Can I join the four libraries to build a unique database or do I have to build each separately?

I want to: 
$ kraken2-build --build --threads 56 --db 'this_folder_has_four_libraries_joined/'

Thanks for your help.

Maryo.

**Comment by DerrickWood** [comment]
Sure, you can do that. For example, if you had a DB named 'bigDB':

    kraken2-build --db bigDB --download-taxonomy
    kraken2-build --db bigDB --download-library archaea
    kraken2-build --db bigDB --download-library bacteria
    kraken2-build --db bigDB --download-library fungi
    kraken2-build --db bigDB --download-library viral
    kraken2-build --db bigDB --build --threads 56

would do what you're looking for.

I'll make a little change to the documentation to make it more clear that multiple libraries can be put into a single DB.

**Comment by MaryoHg** [comment]
Derrick,

I was trying to use that script. I was not sure how. 
I really appreciate how explicit you were for this example.
¡Thanks!

> I'll make a little change to the documentation to make it more clear that multiple libraries can be put into a single DB.

It would be great.

Thanks again,
Maryo.
