### ISSUE TITLE
Extract classified sequences 

### ISSUE THREAD

**Issue by SumTot** [DerrickWood/kraken2#251]
Hello!
I would like to find the nucleotide sequence of some of my sequences that are assigned to a taxa by Kraken2.
I was looking to the different output files from the analysis with Kraken2 and I didn´t find them.
Could someone tell me which steps I should follow to get my original sequences?
Thank you very much!

**Comment by jenniferlu717** [comment]
I have provided an extract_kraken_reads.py script here: https://github.com/jenniferlu717/KrakenTools/ that is compatible with Kraken2.
