### ISSUE TITLE
Links to minikraken2 database downloads are incorrect

### ISSUE THREAD

**Issue by ialbert** [DerrickWood/kraken2#254]
The files for minikraken2 download listed from the page below are linking to non-existing files

https://ccb.jhu.edu/software/kraken2/index.shtml?t=downloads

For example:

ftp://ftp.ccb.jhu.edu/pub/data/kraken2_dbs/minikraken2_v2_8GB_201904_UPDATE.tgz

does not exist.

**Comment by jenniferlu717** [comment]
As per the note at the top of the page, the links are being updated. 

All databases can be found at ftp://ftp.ccb.jhu.edu/pub/data/kraken2_dbs/. 

Older databases have been moved to the ftp://ftp.ccb.jhu.edu/pub/data/kraken2_dbs/old.

**Comment by ialbert** [comment]
All I am saying that you should not link to data that does not exist. 

**ALL** the download links that you feature of the manual page (!) are invalid

- MiniKraken2_v1_8GB: (5.5GB) 8GB Kraken 2 Database built from the refseq bacteria, archaea, and viral libraries.
- MiniKraken2_v2_8GB: (5.5GB) 8GB Kraken 2 Database built from the Refseq bacteria, archaea, and viral libraries and the GRCh38 human genome

You should remove that section if it is not a valid content. It helps no one and leads us all to waste our time. Plus there would be no need to say "links are being updated" if there are no invalid links.

**Comment by jenniferlu717** [comment]
I have updated the website for now.

**Comment by ialbert** [comment]
thank you for the consideration and fast action

**Comment by luciazifcakova** [comment]
ftp://ftp.ccb.jhu.edu/pub/data/kraken2_dbs/ is still not showing any databases... links on kraken website are still not working in 2022...

**Comment by mikemwanga** [comment]
Its 2022 and links to ftp://ftp.ccb.jhu.edu/pub/data/kraken2_dbs/ kraken databases are down. Please reopen this issue.

**Comment by rociogerez** [comment]
Same problem in 2023

**Comment by ialbert** [comment]
The entry point appears to be the following:

https://github.com/BenLangmead/aws-indexes/blob/master/docs/k2.md
