### ISSUE TITLE
masking of nt database is very slow

### ISSUE THREAD

**Issue by ajaybabu27** [DerrickWood/kraken2#26]
Hi,

I finished downloading "nt" database and I am now stuck at the step of masking low-complexity sequences. The dustmasker script has been running for almost a day. I see that it not multi-threaded. Is it typical for this step to take such a long time ? Would it be possible to replace "dustmasker" with a more efficient tool such as "repeatmasker" ? 

Ajay.

**Comment by DerrickWood** [comment]
Any sort of low-complexity masking is fine, but I don't think repeatmasker is strictly a low-complexity masking program. Work is underway to provide a multi-processor version of the masking with dustmasker.

**Comment by ajaybabu27** [comment]
Hi Derrick,

Thanks for getting back to me. Looking forward to that update. FYI, it took 24 hours to complete masking of nt database and it successfully completed. 

Cheers,
Ajay.
