### ISSUE TITLE
Confusion when using nr database

### ISSUE THREAD

**Issue by sleepvet** [DerrickWood/kraken2#262]
What I want is to mapping paired reads to a nr database, and get the mapping counts/rate results. I found kraken2 supports protien reference, but the process to do it is not in detailed. I tried _kraken2-build --download-library nr --protein --threads 80  --db krakennr_ . The comments look good as follows, and I get a file library.faa (119G size), a file prelim_map.txt (16G), and an empty file library.faa.masked. I have no idea what it is, and how to claasify reads against nr database. Could you please help me with it?

_Downloading nr database from server... done.
Uncompressing nr database...done.
Parsing nr FASTA file...done.
Masking low-complexity regions of downloaded library... done._

**Comment by jenniferlu717** [comment]
The command you ran executed correctly. The library.fna.masked file just tells Kraken that the library had low complexity seqs removed (its existence,its supposed to be empty)but you now want to build the database:

`kraken2-build --build --protein --threads=80 --db=krakennr`

**Comment by sleepvet** [comment]
> The command you ran executed correctly. The library.fna.masked file just tells Kraken that the library had low complexity seqs removed (its existence,its supposed to be empty)but you now want to build the database:
> 
> `kraken2-build --build --protein --threads=80 --db=krakennr`
I got a error hit after runing this command line. It looks like the kraken2 was looking for a taxonomy folder. The error hit is as follow:
_Can't find taxonomy/ subdirectory in database directory, exiting._

**Comment by jenniferlu717** [comment]
Oh you need to download the taxonomy folder first too. 

kraken2build --download-taxonomy --db krakennr 

Please refer to the manual if that command doesnt work.
