### ISSUE TITLE
trouble with installation - build

### ISSUE THREAD

**Issue by RichardCorbett** [DerrickWood/kraken2#263]
Hi folks,

I am trying to build the database and got the following message.    My machine is connected to the internet (ie. I can ping various websites).
```
./kraken2-build --standard --threads 48 --db default_db
Downloading taxonomy tree data... done.
Untarring taxonomy tree data... done.
rsync: failed to connect to ftp.ncbi.nlm.nih.gov (130.14.250.13): Connection refused (111)
rsync: failed to connect to ftp.ncbi.nlm.nih.gov (2607:f220:41e:250::10): Network is unreachable (101)
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]
Error downloading assembly summary file for archaea, exiting.
```

am I doing something silly?

thanks
Richard

**Comment by douglasgscofield** [comment]
Hej, we're seeing the same thing, at least back to May 27:
```
Downloading nucleotide gb accession to taxon map...rsync: failed to connect to ftp.ncbi.nlm.nih.gov (130.14.250.13): Connection refused (111)
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]
Command exited with non-zero status 10
```

**Comment by jenniferlu717** [comment]
This has to do with a server issue. It happens sometimes because
1) The ncbi website is having problems
2) rsync is not available for your server
3) rsync is having problems

If this problem is occuring, please trying using the --use-ftp flag when downloading the taxonomy.
