### ISSUE TITLE
Download standard database

### ISSUE THREAD

**Issue by Maryamtarazkar** [DerrickWood/kraken2#264]
I am trying to download standard database using
kraken2-build --standard --use-ftp --db ./Kraken2_Database

but when I apply this command only one "taxonomy" folder is created and the folder is empty. following is the things I see on my page once I apply the command.

Is there something I missed before downloading the database? (I installed Kraken2 using bioconda)

  --standard                 Download and build default database
  --help                     Print this message
  --version                  Print version information

Options:
  --db NAME                  Kraken 2 DB name (mandatory except for
                             --help/--version)
  --threads #                Number of threads (def: 1)
  --kmer-len NUM             K-mer length in bp/aa (build task only;
                             def: 35 nt, 15 aa)
  --minimizer-len NUM        Minimizer length in bp/aa (build task only;
                             def: 31 nt, 12 aa)
  --minimizer-spaces NUM     Number of characters in minimizer that are
                             ignored in comparisons (build task only;
                             def: 7 nt, 0 aa)
  --protein                  Build a protein database for translated search
  --no-masking               Used with --standard/--download-library/
                             --add-to-library to avoid masking low-complexity
                             sequences prior to building; masking requires
                             dustmasker or segmasker to be installed in PATH,
                             which some users might not have.
  --max-db-size NUM          Maximum number of bytes for Kraken 2 hash table;
                             if the estimator determines more would normally be
                             needed, the reference library will be downsampled
                             to fit. (Used with --build/--standard/--special)
  --use-ftp                  Use FTP for downloading instead of RSYNC; used with
                             --download-library/--download-taxonomy/--standard.
  --skip-maps                Avoids downloading accession number to taxid maps,
                             used with --download-taxonomy.
  --load-factor FRAC         Proportion of the hash table to be populated
                             (build task only; def: 0.7, must be
                             between 0 and 1).

**Comment by jenniferlu717** [comment]
Prior to building, run:
`kraken2-build --download-taxonomy --db MYDB`

**Comment by Maryamtarazkar** [comment]
Thank you for your comment, that worked !
