### ISSUE TITLE
Malformed FastQ

### ISSUE THREAD

**Issue by cazzlewazzle89** [DerrickWood/kraken2#266]
I am receiving the Following error when running Kraken2 (v. 2.0.8-beta) on RNA-Seq data generated on an Illumina NextSeq.

`classify: malformed FASTQ file (exp. '@', saw "AAAAAEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEAEEEEEEEEEEE/EEEEE<EEEEEEEEEE"), aborting`

The command I am using, and the offending read, are below but I do not see the issue 

```
kraken2 107_R1.fastq.gz 107_R2.fastq.gz --paired --threads 24 --db /data/databases/Kraken2_GTDB_r89_54k/ --output 107__GTDB54k_krakenoutput.txt --report 107_GTDB_kreport.txt --report-zero-counts

---

@NB501531:133:HLNN3BGXF:1:22202:23415:16788/1
CCCGACCACGCAGGTTCTCTTGAACAATGCAGGTCACAAGGAACTCAACAAGCTTCAGACCCTCACCGCTCGCGT
+
AAAAAEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEAEEEEEEEEEEE/EEEEE<EEEEEEEEEE
```

I have had no issues for any other samples in this dataset, or for any other dataset using this exact same command and database.

Any advice or suggestions would be much appreciated.

Thanks, and all the best,
Calum

**Comment by jenniferlu717** [comment]
If you put just that read into a file and classify that, do you still have problems? What about the read following that one?

**Comment by cazzlewazzle89** [comment]
Hi Jen,

It ran fine when I tried making input files containing the offending read and the reads immediately before and after.
I also had an issue when trying to convert to FastA format using IDBA's fq2fa script. No issues with the file containing the reverse reads though.
It seems like it is miscounting the lines in the input file if it is expecting a FastQ header instead of quality info.

I ran the sample through humann2 last night and received an error
`Saw ASCII character 10 but expected 33-based Phred qual.``
which seems as though a newline character may have been introduced somehow.

**Comment by PingWang7** [comment]
Same question occured to me recently.
![image](https://github.com/DerrickWood/kraken2/assets/52268937/30368e68-482f-42ce-a7fe-1de4e8a5615d)

**Comment by xxx0310** [comment]
> Same question occured to me recently. ![image](https://user-images.githubusercontent.com/52268937/244570812-30368e68-482f-42ce-a7fe-1de4e8a5615d.png)
I also encountered the same problem, how did you solve it? Can you help me? It's urgent. Thank you

**Comment by cazzlewazzle89** [comment]
@xxx0310 it was a whule ago so I can't remember with 100% certainty but I _think_ there was an issue with the FASTQ ordering. Somehow my paired reads weren't in the same order in the R1 and R2 files.

**Comment by xxx0310** [comment]
Thank you very much for seeing and replying to my question. I am really touched. But I looked up some data, and I couldn't find a way to sort R1 and R2, right? Can you recall what method you used at that time? I would appreciate your reply. Thank you.

**Comment by cazzlewazzle89** [comment]
They should come off the sequencer in the correct order (ie. the same order in both files). I think I made a mistake in a preprocessing step - removal of host DNA or microbial rRNA - which removed one read of the pair instead of both.

You could try the following:
a) double check any steps you have performed to this stage to see if there are any errors 
b) run Kraken2 on the raw sequencing reads to make sure they run correctly
c) try `gzip-t` on each of your input files to test that they are properly compressed.

**Comment by PingWang7** [comment]
> Same question occured to me recently. ![image](https://user-images.githubusercontent.com/52268937/244570812-30368e68-482f-42ce-a7fe-1de4e8a5615d.png)

The data processed in my work is single-ended sequencing data. To evaluate the correlation between the size of input data and time consumed, I splitted the orignal data to 50 parts (total line number of each parts % 4 = 0). Then I add up the separated data get the data with ascending gradient of data size. Unfortunately, Only the first part of the data gets the mistake.
![image](https://github.com/DerrickWood/kraken2/assets/52268937/cf84e7bd-3e40-4662-940a-8c2d266c1e20)
