### ISSUE TITLE
Custom taxonomy

### ISSUE THREAD

**Issue by skDooley** [DerrickWood/kraken2#267]
Is it possible to create a custom database that uses a taxonomy that isn't NCBI's? I want to be able to define my own taxonomy based on a phylogenetic tree. Is this possible?

**Comment by jenniferlu717** [comment]
Yes as long as the nodes.dmp/names.dmp files are placed in a "taxonomy/" folder and appropriately formatted (\t|\t delimited, beginning with root node) 

nodes.dmp: 
1. taxonomy ID 
2. parent taxonomy ID (except root -- which goes to root) 
3. level (no rank, superkingdom, phylum, etc) 
4. - (hyphen) 
e.g. 
1       |       1       |       no rank |       -       |
2       |       1       |       superkingdom    |       -       |

names.dmp 
1. taxonomy ID 
2. name
3. - (hyphen)
4. scientific name
e.g. 
1       |       root    |       -       |       scientific name |
2       |       Archaea |       -       |       scientific name |
