### ISSUE TITLE
How can I extract the reads from a specific taxonomic group?

### ISSUE THREAD

**Issue by Lily-WL** [DerrickWood/kraken2#27]
Dear Developer,

The Kraken2 give the results of classified sequence and taxonomic ID. A report including aggregrate counts/clade also was generated. But How can I extract the classified reads of a specific taxonomic group for the following assembly? Is there any script including in kraken2 that can be used?

**Comment by tseemann** [comment]
When you say "specific taxonomic group" do you mean just a single specific taxid, or that and everything under it in the taxonomy?

**Comment by katewd** [comment]
Kraken classifies, but doesn't separate. To extract the reads from a specific group for assembly, I use a combination of R and python scripts. 
First, from Kraken v1, I run the kraken-translate command to generate a "reads-with-hits.labels" file, which goes into R as follows.

This code is to pull out the species names and frequency of occurrence of hits to the Kraken database of bacterial/archaeal/viral RefSeq sequences. 
In particular, this code pulls out those sequence reads from the samples that are classified as originating from a specific species of interest.

`library(dplyr)
kraken_species_hit <- read.delim(file = "/path to your file/reads-with-hits.labels", sep="\t", row.names = NULL, col.names = c("read","taxonomy"))`

`write.csv(as.data.frame(table(kraken_species_hit$taxonomy)), file = "/path to your file/species-frequency.csv", quote = FALSE, row.names = FALSE)`

For example, filter table for viral hits only, then
pull out reads classified as originating from specific viral sub-species, and write read names to file
(change to your species of interest):

`v = grep("Virus+",kraken_species_hit$taxonomy, perl=TRUE, value=FALSE)`
`viral_hits = kraken_species_hit[v,]`

`CA = which(viral_hits$taxonomy == "root;Viruses;Retro-transcribing viruses;Caulimoviridae;Badnavirus;unclassified Badnavirus;Banana streak CA virus")
bsvCA_reads = viral_hits[CA,]`

`write.table(bsvCA_reads$read, file = "/path to your file/banana_streak_CA_virus_reads", quote = FALSE, sep = " ", row.names = FALSE, col.names = FALSE)`

For example, summary of viral species hits and frequency:

`virfreq = (viral_hits %>% group_by(taxonomy) %>% summarise(Freq = length(taxonomy))) 
write.csv(virfreq, file = "/path to your file/viral_species_counts.csv")`

Once you have the list of reads originating from your species of interest, you'll need to extract them from your fasta file. I do this with a python script:
[https://github.com/katewd/SugarcaneYCS/blob/master/seq_extractor.py](url)

Alternatively, perhaps you want to exclude the reads on your reads list, for example any with a Human hit, and remove them from your fasta file instead. In that case, use this python script instead:[https://github.com/katewd/SugarcaneYCS/blob/master/seq_clean.py](url)

Good luck!

**Comment by Lily-WL** [comment]
Dear Kate,

Thank you very much for your reply. It is very useful.

Best wishes!

Lily

**Comment by bishopia** [comment]
I'm also trying to separate reads (in paired fastq files) that are not classified by my database from those that are. The --unclassified-out option seemingly gives me what I want (unclassified reads only), but I'm confused as to why the output file has more lines than the input file. Is the following code giving me the subset fastq I'm looking for, even if it is longer than the input? 

kraken2 --use-names --confidence 0.95 --minimum-base-quality 20 --threads 16 --fastq-input --gzip-compressed --paired --unclassified-out lib11#.fq.gz --db vi_bac_arc --report test_report.txt lib11_R1_P.fq.gz lib11_R2_P.fq.gz

my goal is to exclude bacteria reads prior to de novo assembly for a protist, if that context helps. any help is much appreciated.

**Comment by JCSzamosi** [comment]
The solutions given here seem to work for all reads assigned to a specific taxon. Is there a way to extract all reads from a taxon and its daughters (e.g. all Bacterial reads, including those assigned to specific bacteria of any type)? Or would you need to first make a comprehensive list of all names/taxids under that node and then filter for all of them?

**Comment by jenniferlu717** [comment]
I have provided the extract_kraken_reads.py script here: https://github.com/jenniferlu717/KrakenTools to allow for extracting reads for an exact taxon, for the taxon and its parents or for the taxon and its children.
