### ISSUE TITLE
Database version

### ISSUE THREAD

**Issue by Dries-B** [DerrickWood/kraken2#271]
Is there any versioning associated with the standard Kraken2 database? Has the standard database so far been constant for users? Or do the standard databases built now differ from the standard databases which were built one year ago?

I'm refering to the database built by the following command: `kraken2-build --standard --db kraken2_db`

**Comment by jenniferlu717** [comment]
Short answer: standard dbs built today will be different than standard dbs built a year ago. 

Running `kraken2-build --standard --db kraken2_db` will run the same code and download the **current** Refseq libraries for bacteria/viral/archaea and human reference. As the Refseq libraries change, so will the standard database. 

The standard switch only determines which Refseq libraries are downloaded. 

There is not any versioning as a result.
