### ISSUE TITLE
What is minikraken_8GB_20200312_genomes.txt ?

### ISSUE THREAD

**Issue by smoretti** [DerrickWood/kraken2#274]
Hi

I wonder how to use **minikraken_8GB_20200312_genomes.txt** with *minikraken_8GB_202003.tgz*, if it has to be used with it.

**Comment by jenniferlu717** [comment]
It is just a list of all of the genomes that are included in the minikraken database. You do not need to download it to run the database but if you have a question about which genomes are in the database, you should refer to that text file.
