### ISSUE TITLE
How paired reads are classified

### ISSUE THREAD

**Issue by ZeweiSong** [DerrickWood/kraken2#275]
Hi,

I am a bit confusing on how kraken2 classifies the paired reads.

On the manual it said, "Note that paired read data will contain a "|:|" token in this list to indicate the end of one read and the beginning of another."

Does this mean that Read1 and Read2 were classified separately? If so, how does kraken2 calculate the profile?

Thanks.

Zewei

**Comment by jenniferlu717** [comment]
The two reads are connected and then classified. The token in the middle is to keep Kraken from classifying any kmers that span the break between the two. 

**For example:** if the paired reads are: 1) AAA AAA AAA and 2) GGG GGG GGG with kmer length 3, kraken will show taxonomy classifications as 1 1 1 1 1 1 1 |:| 2 2 2 2 2 2 2. Then it will perform the LCA/scoring on all of those kmer assignments. It will not assign a taxonomy ID to AAG or AGG.

Once all the kmers are classified, then all of the kmer assignments will be taken into consideration to give the two pairs ONE final taxonomy classification.

For example:

- if pair 1 is human, and pair 2 is unclassified, then the full read will be assigned to human
- if pair 1 is human and pair 2 is bacteria, then Kraken will give the full read a taxonomy classification for the highest scoring leaf node from all of the kmers. 

I hope that makes sense. You will have to review the original Kraken 1 paper to understand more of the scoring scheme.
