### ISSUE TITLE
Species assignment of 16S amplicons from nanopore sequencing

### ISSUE THREAD

**Issue by ganiatgithub** [DerrickWood/kraken2#277]
Hi, 

I've tried Kraken2 to for taxonomy assignment with silva 138 pre-built database. The reads were full-length 16S amplicons from nanopore sequencing. It works nicely except none of the sequences (total >1 million) were assigned at species level.

Is this normal? Are there ways to go to species level for nanopore reads?

Btw I'm working with a mixed bacterial community.

Kind regards,
Gaofeng

**Comment by jenniferlu717** [comment]
The SILVA taxonomy does not have species-level taxonomy assignments. The pre-built database uses SILVA sequences AND the SILVA taxonomy. You can modify the SILVA taxonomy to assign each genome to a species but we are not currently making changes to the SILVA taxonomy. I do not know why SILVA does not have species in their taxonomy.
