### ISSUE TITLE
Repeated reference genomes in the library?

### ISSUE THREAD

**Issue by yjk555** [DerrickWood/kraken2#278]
Dear developer, 

I recently built a custom database for rumen microbiome consists of bacterial and archaeal complete genomes from Refseq and some genomes retrieved from Genbank in related studies. I am really happy with the high proportion of classified reads from the output with the new database. However, I found that there might be a little bias while looking at the bacteria composition at the genus level, the result shows the most dominant genus with Ruminococcus (a high proportion of around 30%), not Prevotella (around20%). To my knowledge, this is unacceptable, and I suspect that this may be attributed to repeated genomes added to the library. Does this issue possible to occur?  If yes, how to avoid this problem? Many thanks in advance.

Best regards,
Jiangkun

**Comment by jenniferlu717** [comment]
The results will highly depend on which genomes you included in the database, so unfortunately, there is not a lot that we can advise on.

What I will say is that if more kmers are being classified in the Ruminococcus subtree, then reads will be classified in that genus. 

I do not believe it is a result of repeated reference genomes as it depends on the number of unique kmers in a subtree, not the number of genomes in total. If all of those reference genomes are identical, it will not affect the results. 

If you would like to require more kmers in a read to match, you can increase the confidence score to 0.1 (--confidence 0.1) when running kraken2.

**Comment by yjk555** [comment]
Thank you so much for the wonderful interpretation! Hope the
confidence score setting improves my classification results.
Many thanks,
Jiangkun
