### ISSUE TITLE
Problem with 'kraken2-build --add-to-library' in parallel

### ISSUE THREAD

**Issue by thbtmntgn** [DerrickWood/kraken2#28]
Hi @DerrickWood 

I'm truying to build a custom database and I have a lot of sequences to add so I tried to use the `kraken2-build --add-to-library` command in parallel. I used the command from the MANUAL with the `-P` option for `xargs` but it seems to produce some errors. Here is the command I used:

`find ${GENOMESDIR} -name *'.fna' -print0 | xargs -I{} -0 -n1 -P${CPU} kraken2-build --add-to-library {} --db ${DBNAME} &>> log.add_to_library`

Where:
- `${GENOMESDIR}` is the path to the directory containing your FASTA files
- `${CPU}` is the number of processors you want to use
-  `${DBNAME}` the name of your Kraken2 database

The problem seems to come from the `add_to_library.sh` script. When using in parallel, the `cp` and `rm` commands at the end not always work because the `temp_map.txt` file does not exit. I obtain error messages like:

`cat: ${DBNAME}/kraken2/library/added/temp_map.txt: No such file or directory` and `rm: cannot remove ‘${DBNAME}/kraken2/library/added/temp_map.txt’`

It also seems to mess up the resulting `prelim_map.txt` file.

**Comment by DerrickWood** [comment]
Thanks for pointing this out - this is pretty clearly a race condition. I think that code example is just copied from the Kraken 1 manual, and I don't think this translates well over to Kraken 2's methods. This might be fixed with a few small changes to the `add_to_library.sh` and `build_kraken2_db.sh` scripts, though. I'll take a look and see if I can get a fixed version out soon.

**Comment by thbtmntgn** [comment]
It seems to work very well!

I launched the following command and it took approximatively 2 000 seconds instead of 60 000 to add all the sequences to library.

`find ${GENOMESDIR} -name *'.fna' -print0 | xargs -I{} -P${CPU} -0 -n1 kraken2-build --add-to-library {} --db ${DBNAME} &>> log.add_to_library`

`log.add_to_library` is a little messy but their is no error message anymore.

Thank you!
