### ISSUE TITLE
Can we use refseq genomic 

### ISSUE THREAD

**Issue by CaroleBelliardo** [DerrickWood/kraken2#281]
Dear Authors,
I would like to use refseq representative genomic as reference database.  Can I download a preformated db or make by my self with the built option ? 
Thanks a lot for your help,
Best regards.

**Comment by jenniferlu717** [comment]
`kraken2-build --db . --download-library bacteria` (or archaea, viral, etc) will download the Refseq complete genomes within that group. 

See the Manual (either the file in the code or in the github wiki here) for all download options. 

If you have additional genomes or want genomes outside of those options, you can download them and add them using `kraken2-build --add-to-library $file --db .` 

After downloading any of the libraries. Make sure to also download the taxonomy:
`kraken2-build --download-taxonomy --db .`

and then build the database:
`kraken2-build --build --db .`

Hope that helps. 
Jen Lu
