### ISSUE TITLE
a question about Standard Kraken Output Format

### ISSUE THREAD

**Issue by fjptwenger** [DerrickWood/kraken2#283]
I analyzed a sample using kraken2，The result confused me。

from the Manual，the last column is the **A space-delimited list indicating the LCA mapping of each k-mer in the sequence(s)** ， why here the id **15217:Q**  seem the sequence id from the second column？and what the Q mean?

![image](https://user-images.githubusercontent.com/25705121/88502817-425b1980-d002-11ea-8487-f82e2342eb38.png)

**Comment by jenniferlu717** [comment]
What is the exact command line that you used?

**Comment by fjptwenger** [comment]
my command : kraken2 --db  minikraken_8GB_20200312 --threads 8  final.contigs.fa --classified-out ~/meta/metadata/CCMD21593359ST/unclass.fa  --quick --output MEGAHIT/CCMD2159.karken2.out --threads 8

**Comment by jenniferlu717** [comment]
Sorry for the late reply. I meant to respond earlier.

The Q is resulting from running kraken2 using --quick mode. --quick mode means that as soon as a kmer is classified, it will move on.
