### ISSUE TITLE
Kraken2-build terminated by signal 13

### ISSUE THREAD

**Issue by tsoratto** [DerrickWood/kraken2#286]
Hi,

I'm trying to build a custom database for Fungi. I download the taxonomy and the library. And using the command:
kraken2-build --build --db fungi_refseq200731/ --threads 18

I get the following error:
Sequence ID to taxonomy ID map already present, skipping map creation.
Estimating required capacity (step 2)...
/proj/virus/tools/kraken2/2.0.9/scripts/build_kraken2_db.sh: line 101: estimate_capacity: command not found
xargs: cat: terminated by signal 13

I'm using the last version of Kraken 2.0.9-beta and I installed it using the command:
bash install_kraken2.sh ./

**Comment by lynngao** [comment]
Hi, have you fixed the xargs: cat: terminated by signal 13 problem? Thanks a lot!

**Comment by nicolo-tellini** [comment]
Hello all,

I am following the issue, has been the problem fixed ? 

thanks

best
