### ISSUE TITLE
kraken2-build timeout

### ISSUE THREAD

**Issue by Jessica-2345** [DerrickWood/kraken2#288]
Dear authors,
I am trying to build the standard kraken database but it failed each time.

Here is the code I used : 
kraken2-build --standard --use-ftp --no-masking --threads 24 --db dbkraken

And here's the output: 
Step 1/2: Performing ftp file transfer of requested files
Step 2/2: Assigning taxonomic IDs to sequences
All files processed, cleaning up extra sequence files... done, library complete.
Step 1/2: Performing ftp file transfer of requested files
Timeout at /usr/share/perl5/Net/FTP.pm line 491

If I don't use the option  --use-ftp I have this output:

Step 1/2: Performing ftp file transfer of requested files
Step 2/2: Assigning taxonomic IDs to sequences
All files processed, cleaning up extra sequence files... done, library complete.
rsync_from_ncbi.pl: unexpected FTP path (new server?) for na

and If I remove --no-masking:

Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library...which: no dustmasker in (/gpfsuser/home/users/j/o/jody/KRAKEN2install/kraken2/kraken2:/gpfsuser/home/users/j/o/jody/KRAKEN2install/kraken2/kraken2:/home/ulb/ebe/jody/miniconda3/bin:/home/ulb/ebe/jody/miniconda3/condabin:/home/ulb/ebe/jody/KRAKEN2install/kraken2/kraken2:/home/ulb/ebe/jody/mash-Linux64-v2.2:/home/ulb/ebe/jody/pplacer-Linux-v1.1.alpha19:/home/ulb/ebe/jody/Sparc/hadoop-2.7.3/bin:/home/ulb/ebe/jody/Sparc/spark-2.4.5-bin-hadoop2.7/bin:/home/ulb/ebe/jody/Sparc:/home/ulb/ebe/jody/hmmer-3.2.1/src:/home/ulb/ebe/jody/Prodigal:/home/ulb/ebe/jody/bin:/home/ulb/ebe/jody:.:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/CECI/soft/cecisw/noarch/manual/ceci-tools/bin:/sbin:/usr/sbin:/cm/shared/apps/slurm/current/bin:/cm/shared/apps/slurm/current/sbin:/home/ulb/ebe/jody/bin)
Unable to find dustmasker in path, can't mask low-complexity sequences

Also, I previously run
 kraken2-build --download-taxonomy --db MYDB

I need some help or suggestion to resolve those errors.

Thanks in advance
Ody J.

**Comment by jenniferlu717** [comment]
For the first error, it seems like your FTP configuration has some problems that I'm unaware of. 

The second error is something we keep coming up against where the assembly_summary.txt file has some missing links but if you rerun it, it might work the second time when the file has been updated.

For the last error, it seems that dustmasker isnt installed on your system, so you will need to install that. https://www.ncbi.nlm.nih.gov/IEB/ToolBox/CPP_DOC/lxr/source/src/app/dustmasker/

**Comment by Jessica-2345** [comment]
Thanks,
I tried again after installing dustmasker but I ended up with another error.
$ kraken2-build --standard --threads 24 --db dbkraken
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 390 projects (604 sequences, 1.02 Gbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library... done.
rsync: read error: Connection reset by peer (104)
rsync error: error in rsync protocol data stream (code 12) at io.c(759) [receiver=3.0.6]
Error downloading assembly summary file for bacteria, exiting.

Do you know what's wrong this time?
Ody J.

**Comment by jenniferlu717** [comment]
It seems like it had a problem downloading the assembly_summary.txt file for bacteria. 

Try these commands instead of that one?
`kraken2-build --db $DB --download-taxonomy--skip-maps
kraken2-build --db $DB --download-library archaea
kraken2-build --db $DB --download-library bacteria
kraken2-build --db $DB --download-library viral
kraken2-build --db $DB --download-library human --no-mask
kraken2-build --db $DB --download-library UniVec_Core
kraken2-build --db $DB --build --threads $THREADS`

It will make it easier for you to restart the build if rsync breaks at any step. so you wont have to redo steps you already completed.

**Comment by heweihuang** [comment]
> Thanks,
> I tried again after installing dustmasker but I ended up with another error.
> $ kraken2-build --standard --threads 24 --db dbkraken
> Step 1/2: Performing rsync file transfer of requested files
> Rsync file transfer complete.
> Step 2/2: Assigning taxonomic IDs to sequences
> Processed 390 projects (604 sequences, 1.02 Gbp)... done.
> All files processed, cleaning up extra sequence files... done, library complete.
> Masking low-complexity regions of downloaded library... done.
> rsync: read error: Connection reset by peer (104)
> rsync error: error in rsync protocol data stream (code 12) at io.c(759) [receiver=3.0.6]
> Error downloading assembly summary file for bacteria, exiting.
> 
> Do you know what's wrong this time?
> Ody J.



> For the first error, it seems like your FTP configuration has some problems that I'm unaware of.
> 
> The second error is something we keep coming up against where the assembly_summary.txt file has some missing links but if you rerun it, it might work the second time when the file has been updated.
> 
> For the last error, it seems that dustmasker isnt installed on your system, so you will need to install that. https://www.ncbi.nlm.nih.gov/IEB/ToolBox/CPP_DOC/lxr/source/src/app/dustmasker/

How to install dustmasker in Linux ?

**Comment by jenniferlu717** [comment]
rsync errors has to do with your servers ability to connect  to NCBI. You can try with --use-ftp for the download command instead.

Use the link I specified earlier to download/install dustmasker.

**Comment by ZhangMH2000** [comment]
> It seems like it had a problem downloading the assembly_summary.txt file for bacteria.
> 
> Try these commands instead of that one? `kraken2-build --db $DB --download-taxonomy--skip-maps` `kraken2-build --db $DB --download-library archaea` `kraken2-build --db $DB --download-library bacteria` `kraken2-build --db $DB --download-library viral` `kraken2-build --db $DB --download-library human --no-mask` `kraken2-build --db $DB --download-library UniVec_Core` `kraken2-build --db $DB --build --threads $THREADS`
> 
> It will make it easier for you to restart the build if rsync breaks at any step. so you wont have to redo steps you already completed.

Hi jenniferlu. I used --use-ftp but the speed is quite slow (50kb/s). rsync sometimes run successfully but more often it failed to download the file. So can I continue the former download whenever it showed 'rsync: [receiver] read error: Connection reset by peer (104)'? Even if it may be troublesome, I prefer use this rather than ftp.

**Comment by su9y** [comment]
how to solve this problem in Linux centOS 
(base)  xxx@localhost ~]$ host ~]$ kraken2-build --standard --thread 24 --db /data/my_kraken2_db2
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 623 projects (1165 sequences, 1.78 Gbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library...rsync: [receiver] write error: Broken pipe (32)
