### ISSUE TITLE
Error creating standard database

### ISSUE THREAD

**Issue by termithorbor** [DerrickWood/kraken2#289]
Hi all,

when I try to create the standard databse everything works fine till the point when the viral database is downloaded.

This is the error I get:

error in rsync protocol data stream (code 12) at io.c(285) [Receiver=3.1.3]
Error downloading assembly summary file for viral, exiting.

Does anybody know what the problem could be?

Many thanks in advance :)

**Comment by termithorbor** [comment]
Interesting observation: When I try to add the database on its own by using kraken2-build --downl                                                                                                                                                             oad-library viral --db $DBName it seems to work.

**Comment by jenniferlu717** [comment]
It seems like it was a problem with rsync. Unfortunately, there are some issues with NCBI's server sometimes that prevent people from downloading but it tends to then work later on. What you can do is run the individual commands used to download the standard database itself:

`kraken2-build --db $DB --download-taxonomy--skip-maps`
`kraken2-build --db $DB --download-library archaea`
`kraken2-build --db $DB --download-library bacteria`
`kraken2-build --db $DB --download-library viral`
`kraken2-build --db $DB --download-library human --no-mask`
`kraken2-build --db $DB --download-library UniVec_Core`
`kraken2-build --db $DB --build --threads $THREADS`

**Comment by Thomieh73** [comment]
Hi @jenniferlu717,
I was looking at your commands here and I was wondering why you are not masking the human genome?  Any particular reason for doing that?

**Comment by jenniferlu717** [comment]
We dont want to miss classifying any potential human reads, low complexity or not. Often we care more about the nonhuman reads. I can elaborate if that doesnt make sense? @Thomieh73

**Comment by termithorbor** [comment]
kraken2-build --db $DB --build --threads $THREADS $DB here is the path of the downloaded library right?

**Comment by jenniferlu717** [comment]
@termithorbor yes. 

I'm going to close this issue for now, if you continue to have problems, please open a new issue (also. we just updated the code so try updating your code first)
