### ISSUE TITLE
#!/usr/bin/perl  => #!/usr/bin/env perl

### ISSUE THREAD

**Issue by tseemann** [DerrickWood/kraken2#3]
Can you please change `#!/usr/bin/perl`  to `#!/usr/bin/env perl` so it uses the Perl in the PATH rather than forcing system perl?

I know most ppl will have system perl, and you only use core modules, but it causes problems for packaging in bioconda and brew.

**Comment by DerrickWood** [comment]
Fair enough - should be fixed in https://github.com/DerrickWood/kraken2/commit/c26661b0f8823b9ecc136fabae44883ff1cd6e56
