### ISSUE TITLE
kraken2 does not generate a report file

### ISSUE THREAD

**Issue by pengouy** [DerrickWood/kraken2#301]
Hi,
  When I run my kraken2 script, it only generated an output file, but not a report file which I needed in the same time. would you please help me to find where the problem is? Here is my code: 
  _time kraken2 --db ~/db/kraken2 --paired temp/qc/1B_1_kneaddata_paired*.fastq \
      --threads 1 --use-names --use-mpa-style --report-zero-counts \
      --report temp/kraken2/1B_report \
      --output temp/kraken2/1B_output_
  By the way, the log said that I had a segmentation fault, does this fault influence the output? 
Hope to get your response, thanks a lot！

**Comment by pengouy** [comment]
Problem solved itself even I don't know how it worked. I had run thousands of times before today and always got the same result untill this morning.

**Comment by jenniferlu717** [comment]
That is strange to hear. Maybe there was someone else using the RAM on the system at the same time so Kraken may have had some memory problems that caused the seg fault. I'll close the issue for now but if the problem persists, feel free to open a new issue.
