### ISSUE TITLE
Minikraken2 database FTP server down

### ISSUE THREAD

**Issue by wenzelm** [DerrickWood/kraken2#306]
Hi all,

I would like to download the pre-built minikraken2 database, but it looks like the FTP server is down:
ftp://ftp.ccb.jhu.edu/pub/data/kraken2_dbs/old/minikraken2_v2_8GB_201904.tgz

Are there any download mirrors? I couldn't find any alternative downloads. 

Many thanks,
Marius

**Comment by BenLangmead** [comment]
Yes, you can find links from a cloud-based mirror here: https://benlangmead.github.io/aws-indexes/k2

**Comment by BenLangmead** [comment]
Oh, sorry I just noticed that you're trying to access an older minikraken database that has not been copied to the cloud.  I will try to copy it over soon.  In the meantime, keep trying the ftp link now and then as it sometimes experiences temporary outages

**Comment by wenzelm** [comment]
Thank you so much, Ben, for the link to the aws indexes! The database on there is absolutely fine and I'm downloading it now. Issue solved, thank you very much!
