### ISSUE TITLE
Custom Taxonomy .dmp files

### ISSUE THREAD

**Issue by punnettsun** [DerrickWood/kraken2#317]
Hello,

My question is based on #154 . Would I have to modify all .dmp files if I want to use my own taxonomy that is different from NCBI's? Or would I only have to modify or create my own nodes.dmp and names.dmp. When I looked at your scripts for creating the taxonomy for RDP and Greengenes, it seems they only changed the nodes.dmp and names.dmp file (please correct me if I'm wrong as I am not too familiar with bash scripting). Would the other .dmp files be necessary to have in the Kraken2 database taxonomy directory?

Thank you.

**Comment by jenniferlu717** [comment]
Only the names.dmp and nodes.dmp files are required

**Comment by punnettsun** [comment]
Great, thank you for the very quick response! Truly appreciate it!

**Comment by punnettsun** [comment]
One more clarification. If we were not using NCBI's taxonomy at all, I would also need the accession to taxid for my own sequences correct?

**Comment by punnettsun** [comment]
Hi Jennifer,

I was able to use my own nodes.dmp & names.dmp file and added my reference sequences to the library. All I did was delete the previous nodes.dmp, names.dmp, citations.dmp, delnodes.dmp, division.dmp, gc.prt, gencode.dmp, and merged.dmp. I then added my own nodes.dmp & names.dmp files as well as an "accession2taxid.tsv" file. I then made empty files for citations.dmp & all of the rest of the files. This worked, and I was able to build my database. 

My question is, is this the right way of going about using my own taxonomy to build the database and classify reads? Is this all I had to do or did I need to modify any of the scripts?

Thank you.

**Comment by mw55309** [comment]
I think what you're doing is the right way!

However, I am having problems of my own modifying the NCBI taxonomy names.dmp and nodes.dmp, and could sure use some help!

**Comment by punnettsun** [comment]
@mw55309 I was able to make my own nodes.dmp and names.dmp file using FlexTaxD [https://pypi.org/project/flextaxd/](url). Here is their GitHub page: [https://github.com/FOI-Bioinformatics/flextaxd](url)
This tool gives you the option to modify NCBI taxonomy files or you can make your own nodes.dmp and names.dmp files! It took me some time to understand how to use it but the developer has been very quick with their response.

**Comment by jenniferlu717** [comment]
I'm going to close this issue as I think both problems have been solved. Please open a new issue if you continue having problems.

**Comment by DJFast** [comment]
Hi @punnettsun 

I am currently struggling with a similar issue #436 

If you have any advice I would really appreciate it
