### ISSUE TITLE
Kraken classification gives all R classification levels for classified reads

### ISSUE THREAD

**Issue by punnettsun** [DerrickWood/kraken2#329]
Hi,

I used my own taxonomy rather than NCBI and provided Kraken2 with the nodes.dmp and names.dmp files. I was able to run Kraken2 but I came across the problem where all the taxids would be correctly identified but the classification level is incorrect. How can I fix this problem? Is there something I am doing incorrectly?
I have attached the .kreport that I retrieved from the Kraken2 run below.
[sample_kraken2_report.txt](https://github.com/DerrickWood/kraken2/files/5320831/sample_kraken2_report.txt)

Thank you.

**Comment by jenniferlu717** [comment]
In your nodes.dmp file, this happens if you do not have the normal levels listed ("supperkingdom" for bacteria, genus, species, class, family, etc)

**Comment by punnettsun** [comment]
Hi Jennifer,
I was able to fix the ranks problem and can see the different ranks now. Thank you.
