### ISSUE TITLE
no mpa-report with 16S databases

### ISSUE THREAD

**Issue by bioinfo-bfr** [DerrickWood/kraken2#33]
Hey,

I classified my 16S reads with "kraken2 --db $DB_Silva --threads 5 --output $out/20170519_Silva.kraken --report $out/20170519_Silva.mpareport --use-mpa-style $infile1". Although I got a normal kraken output file, I only obtained an empty mpa-report. The same for the other 16S databases (RDP and Greengenes) I tried the same command with a custom database that I used for my shotgun samples and got a normal mpa-report. So I would guess that the 16S databases could be the problem here. I recognized that in the taxonomy of the 16S databases only two files (only names.dmp and nodes.dmp) were present in contrast to the custom database with 22 files in that folder. Do you have an idea what could cause the problem here?

Thank you
Josephine

**Comment by bioinfo-bfr** [comment]
Thanks, for you comment. I never used the --clean option. However, also after "cleaning" I still get an empty mpa-report, while kraken-report is ok.

**Comment by tseemann** [comment]
I assume you mean `kraken2-report` ?
Don't forget to pass the correct `--db` to every command, in case it is different to the '$DEFAULT_KRAKEN_DB`

**Comment by DerrickWood** [comment]
Hi @bioinfo-bfr , this is indeed likely due to errors with the building of the 16S databases; I suspect it's due to errors in the formatting of the two taxonomy files you saw (`nodes.dmp` and `names.dmp`). I'm working on a fix for this now.

**Comment by DerrickWood** [comment]
This should now be fixed as of the https://github.com/DerrickWood/kraken2/commit/ee24dd32626e77324b0c6f3682e0a9d00c4b7917 commit.

**Comment by bioinfo-bfr** [comment]
Hey @DerrickWood, thanks for the fix! 
I realized that there is no species classification with Silva and RDP therefore it is not possible to use the metaphlan2krona.py script to transform the mpa-report in a krona chart.  Furthermore I saw that the mpa-format with RDP is inconsistent like in this row of the mpa-report:

> d__Bacteria|p__"Proteobacteria"|c__Gammaproteobacteria|o__"Vibrionales"|f__Vibrionaceae|g__Catenococcus	281

**Comment by DerrickWood** [comment]
@bioinfo-bfr I'm not sure what you mean by the format being inconsistent with RDP - can you explain?

**Comment by bioinfo-bfr** [comment]
So what I mean is that in the RDP mpa-report some of the taxonomic ranks are in quotation marks, while others are not. In the example I gave before Proteobacteria is in quotation marks, while Gammaproteobacteria is not. I saw the same also for some others like 
> d__Bacteria|p__"Actinobacteria"|c__Actinobacteria|o__Solirubrobacterales|f__Solirubrobacteraceae|g__Solirubrobacter	9

while for some others its just fine
> d__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Peptococcaceae 2|g__Desulfotomaculum	12

**Comment by bioinfo-bfr** [comment]
I wouldn't consider me as a typical RDP user. I just don't see the quotation marks when I use greengenes, Silva or NCBI. But maybe there is a deeper meaning behind this. But I see that this is a database issue. So maybe just leave it as it is. Would you mind including the species level from Silva database? Thanks for your support!

**Comment by DerrickWood** [comment]
The file we get from Silva that has the taxonomy information (`tax_slv_ssu_132.txt`) doesn't have any species-level (or even sub-genus) information, unfortunately.

**Comment by bioinfo-bfr** [comment]
Ah, ok. They just have it for qiime. It is probably a different format then.
