### ISSUE TITLE
Kraken2 Error in buildind NCBI bacterial database

### ISSUE THREAD

**Issue by SShaminur** [DerrickWood/kraken2#332]
Hi,

I am trying to build an NCBI RefSeq database of bacteria with Kraken2

`kraken2-build --download-library bacteria --db bacteria`

Error messages

> rsync_from_ncbi.pl: unexpected FTP path (new server?) for an

Any solution? Thanks in advance. (https://www.biostars.org/p/466332/)

**Comment by ahkennedy** [comment]
I'm having a similar issue.  I cannot download the NCBI taxonomy library.  Error message:

"Downloading nucleotide est accession to taxon map...rsync: link_stat "/taxonomy/accession2taxid/nucl_est.accession2taxid.gz" (in pub) failed. No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1659) [Receiver=3.1.3]"

I contacted NCBI support and received the following response:

There is now no such a nucl_est.accession2taxid.gz file under the directory of ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/
You may want to download the nucl_gb.accession2taxid.gz file as it includes the est records.

I downloaded the suggested file and placed it my db's directory RefSeq/Library.  When I try to build the db, I get the following error:

"Creating sequence ID to taxonomy ID map (step 1)...
Sequence ID to taxonomy ID map complete. [0.048s]
Estimating required capacity (step 2)...
Estimated hash table requirement: 2219594604 bytes
Capacity estimation complete. [39.944s]
Building database files (step 3)...
build_db: error opening taxonomy//nodes.dmp: No such file or directory
xargs: cat: terminated by signal 13"

It appears that another file (taxonomy//nodes.dmp) must be generated when downloading the library with Kraken2.

Any solution to downloading the libraries from NCBI?

**Comment by SShaminur** [comment]
https://github.com/DerrickWood/kraken/issues/114

These issues work for me.

Thank you.
