### ISSUE TITLE
Missing .kmer_distrib files

### ISSUE THREAD

**Issue by isardi** [DerrickWood/kraken2#336]
Hello,

I am building a database using the following command:

for file in Genomes/*.fna
do
    kraken2-build --add-to-library $file --db DB --threads 32
done

kraken2-build --build --db DB --threads 16 --kmer-len 250

My log says:
Unable to find dustmasker in path, can't mask low-complexity sequences
Creating sequence ID to taxonomy ID map (step 1)...
Sequence ID to taxonomy ID map complete. [24.406s]
Estimating required capacity (step 2)...
Estimated hash table requirement: 127123748 bytes
Capacity estimation complete. [2m53.229s]
Building database files (step 3)...
Database files completed. [3m33.894s]
Database construction complete. [Total: 6m51.604s]

Within my database file I get:
hash.k2d  
library  
opts.k2d  
seqid2taxid.map  
taxo.k2d  
taxonomy

But I am missing the database_kmer_distrib files that I need for Bracken.  What am I missing?  I did not get any errors when I run my built.
Any help would be greatly appreacited!

-Isabel

**Comment by isardi** [comment]
I just figured out!! It is not part of kraken-build but backen-build!
Yay!

**Comment by jenniferlu717** [comment]
I assume you figured out the issue. kraken2-build and bracken-build are two separate tools that need to be run in succession. I will close this issue for now. If you have any other problems, please open a new issue.
