### ISSUE TITLE
hyperloglogplus.h and cstdint

### ISSUE THREAD

**Issue by hmontenegro** [DerrickWood/kraken2#341]
On a Debian testing system with GCC  version 10.2.0 (Debian 10.2.0-13), compilation failed with:

```
In file included from hyperloglogplus.cc:8:
hyperloglogplus.h:30:1: error: ‘uint64_t’ does not name a type
   30 | uint64_t murmurhash3_finalizer (uint64_t key);
```
Including cstdint at **hyperloglogplus.h** solved the issue.

**Comment by DerrickWood** [comment]
This should be fixed in v2.1.1, with the addition of a header include (`kraken2_headers.h`) that will pull in the `<cstdint>` header.
