### ISSUE TITLE
Unable to get an output from Kraken

### ISSUE THREAD

**Issue by shivamjgandhi** [DerrickWood/kraken2#347]
I'm running the following line:

kraken2 --db /data1/krakenModdb --threads 40 --use-names --paired --classified-out cseqs#.fq [first_file.fq] [second_file.fq] --report kraken_report --output kraken_output

And I'm not getting any output in the folder I'm running this from. Specifically, I'm trying to get a report telling me what Kraken classified the different sequences in my files as. I may just be running this incorrectly, so if anybody has some suggestions on how to change that line that I'm running, please let me know.

Thanks!

**Comment by jenniferlu717** [comment]
The --report and --output options should be specified before the sequence files. The sequence files should be the last parameters given to Kraken2.

**Comment by shivamjgandhi** [comment]
kraken2 --db /data1/krakenModdb --threads 40 --use-names --paired --report kraken_report --output kraken_output --classified-out cseqs#.fq unmapped_1.fq unmapped_2.fq 

I made the change you suggested by moving --report and --output before the sequence files. I'm still not getting an output unfortunately. Am I putting wrong parameters for --report and --output? Thank you!

**Comment by shivamjgandhi** [comment]
Resolved the issue! Turns out that I didn't have permissions in the directory I was attempting to write to. Thank you for your help!
