### ISSUE TITLE
Percent (%) symbol in kraken2 but not in kraken1 reports?

### ISSUE THREAD

**Issue by tseemann** [DerrickWood/kraken2#35]
Was the new '%' sign deliberate?

(It causes parsing failures in some downstream tools)

v1
```
86.44  476324  476324  U       0       unclassified
 13.56  74700   1274    -       1       root
 13.33  73425   244     -       131567    cellular organisms
 13.27  73116   2776    D       2           Bacteria
```

v2
```
 41.51% 228715  228715  U       0       unclassified
 58.49% 322309  82      R       1       root
 58.31% 321318  405     R1      131567    cellular organisms
 57.91% 319096  4873    D       2           Bacteria
```

**Comment by jenniferlu717** [comment]
The percent sign was added, but not for any particular reason. I am noticing a number of users finding this to be an issue with any downstream programs so I'll discuss with Derrick to see if we want to remove it or not.

**Comment by DerrickWood** [comment]
Percent sign removed in https://github.com/DerrickWood/kraken2/commit/405af9124e0b61f000c26a7fbacd1781162bfc1a
