### ISSUE TITLE
does proportion of species in a kraken2 database skew results?

### ISSUE THREAD

**Issue by csmatyi** [DerrickWood/kraken2#351]
Hello all,

I have a question: I have virus A and virus B in a database, with 100 sequences each. 
What would happen if I added 900 sequences of virus A into my database so that I would have 1000 sequences from A, and only 100 from B. Would simply the ratio of virus A in the database skew results if I ran fastq files against the database?

Thanks, Matthew

**Comment by jenniferlu717** [comment]
Technically no, the proportion does not skew the results.
The database is based on the unique kmers in the library files. I would assume adding 100 vs 1000 sequences of A would not increase the number of kmers a lot. I would assume that all of the virus A sequences share a lot of kmers so adding additional sequences would not add too many more unique kmers.

**Comment by csmatyi** [comment]
> 
> 
> Technically no, the proportion does not skew the results.
> The database is based on the unique kmers in the library files. I would assume adding 100 vs 1000 sequences of A would not increase the number of kmers a lot. I would assume that all of the virus A sequences share a lot of kmers so adding additional sequences would not add too many more unique kmers.

Thank you, Jennifer,

Another question -- let's say I have species A, B, C and D in my database. If I want to add species E, then I just add its library to the database with kraken2 --add-to-library and then rebuild the database?

And, another question: how do I remove a library from my database? Do I have to rebuild after removal?

Thanks, Matthew

**Comment by mihkelvaher** [comment]
Addition:
If you want to add a new species then yes, you can use `--add-to-library`, but rebuilding (updating) won't work unless you delete `*.k2d` files and `seqid2taxid.map` file. I had a similar question: #357

Removing:
Removing _should_ work by removing anything related to the species from the `library` dir. Depending on if the species was added later (`--add-to-library`) or in the beginning (`--download-library nt` or other) the info is stored in the `added` or the `nt` (or some other) dir. Sequence itself is in a .fna file and mapping info in prelim_map*.txt file.
As with adding the `*.k2d` files and `seqid2taxid.map` file needs to be removed before building again.

Hope it helps,
Mihkel

**Comment by jenniferlu717** [comment]
@mihkelvaher has answered the question I believe.

@csmatyi I'm going to close this issue for now but if you have additional questions, please open a new issue.
