### ISSUE TITLE
Adding one genome fasta to an existing custom database (GTDB r95)

### ISSUE THREAD

**Issue by ellyyuyang** [DerrickWood/kraken2#353]
Hello,

I understand that a few issues regarding building custom databases, have been raised and closed, but I don't seem to follow how people resolved their issue. Would be grateful if anyone can point to me where to fix.

I am trying to add 1 additional genome to the already-built custom GTDB database. So what I did was 
1. change the sequence ID in the genome.fasta file and assigned a random taxid (an ID not existing in the already-built GTDB kraken2 database). 
**>genome|kraken:taxid|99999 e.coli**
2. run 
**kraken2-build --add-to-library genome.fa --db kraken2DB_new**
3. run
**kraken2-build --build --db kraken2DB_new**

I have noticed that the **library/added/** folder was updated (the file modification time indicates its been modified).

But none of the index files (***.k2d**) were changed, nor the **seqid2taxid.map** file were modified.

I think somehow somewhere I should add the **taxonomy lineage information** of this additional genome fasta, but I am not sure if this should be added manually or through one of the kraken2 build commands. 

Appreciate any help in advance!

Regards,
Elly

**Comment by jenniferlu717** [comment]
For GTDB databases, you need to make sure that the seqid2taxid.map file contains the correct seqid to taxid map (because that database uses a specific taxonomy structure). Kraken2 does not automatically detect new taxids and will ignore any that are not in the taxonomy/ folder. 

The new taxonomy lineage information should be added to the taxonomy/nodes.dmp and taxonomy/names.dmp files 

I should be updating the wiki sometime soon to include information about those files.

**Comment by ellyyuyang** [comment]
> For GTDB databases, you need to make sure that the seqid2taxid.map file contains the correct seqid to taxid map (because that database uses a specific taxonomy structure). Kraken2 does not automatically detect new taxids and will ignore any that are not in the taxonomy/ folder.
> 
> The new taxonomy lineage information should be added to the taxonomy/nodes.dmp and taxonomy/names.dmp files
> 
> I should be updating the wiki sometime soon to include information about those files.

Thanks for your reply Jennifer! I ended up rebuilding from scratch with this additional genome and it worked well. Looking forward to your update! Best.
