### ISSUE TITLE
version diff

### ISSUE THREAD

**Issue by widewater** [DerrickWood/kraken2#356]
hi,
I found that the results varied greatly from version to version.
info:
database: minikraken_8GB_20200312
kraken2 version: 2.0.8, 2.1.0
use paramter: --threads 4 --db minikraken_8GB_20200312 --report xxx.txt --gzip-compressed xxx.fq.gz

result:
for version 2.0.8:
Loading database information... done.
5378921 sequences (193.64 Mbp) processed in 6.718s (48043.2 Kseq/m, 1729.56 Mbp/m).
  987689 sequences classified (18.36%)
  4391232 sequences unclassified (81.64%)

for version 2.1.0:
Loading database information... done.
5378921 sequences (193.64 Mbp) processed in 8.473s (38087.8 Kseq/m, 1371.16 Mbp/m).
  38210 sequences classified (0.71%)
  5340711 sequences unclassified (99.29%)

How do these differences come about?

**Comment by DerrickWood** [comment]
In v2.0.9 (April 2020), we introduced `kraken2`'s `--minimum-hit-groups` switch with a default of 2, requiring a bit more evidence to classify a fragment than was needed in v2.0.8. This is likely the cause of the discrepancy.

**Comment by widewater** [comment]
Thank you! It's really because of this parameter.

**Comment by widewater** [comment]
@DerrickWood Thanks，it's realy because of this paramter.
