### ISSUE TITLE
Remove certain species from standard database

### ISSUE THREAD

**Issue by snenish03** [DerrickWood/kraken2#358]
Hello, 

I am using the standard database from Kraken2 to classify my reads and then Bracken to estimate abundances. I want to narrow down on only a small list of Lactobacillus species and all other species from other genus. (i.e lets say there are 100 Lactobacillus species, I was to keep only 5 of them in the database and remove the rest). Is there a way I can do that?

**Comment by jenniferlu717** [comment]
We do not have an automatic way of doing that. You will have to manually modify the library.fna file for bacteria to remove the species you do not want in the database.

**Comment by snenish03** [comment]
Got it. Is there a way I can build a custom database using a fasta file?

**Comment by snenish03** [comment]
To give more background, I download fasta file from SILVA and made some changes to it. I want to create a database using this edited reference and then run Kraken2 on it.

**Comment by jenniferlu717** [comment]
If you want the SILVA taxonomy structure, I would suggest running `kraken2-build --special silva --db . ` and then cancelling the download once it generates the seqid2taxid.map file. 

Then, I would replace the library file with the new one you want to use and run the build command `kraken2-build --build --db . `
