### ISSUE TITLE
how to interpret the output data?

### ISSUE THREAD

**Issue by joyang-aDNA** [DerrickWood/kraken2#359]
hi author:
    Thanks for your great kraken to help me work on my data. But here is something that I don't understand totally. 
    The output file has a header like that. but what is R1 G1 D1...? I saw from the method that it is some undefined rank code but they do not add up to R(29.12). So Could you please answer my question? 
    Thank you!
<img width="595" alt="512809399a29a319f4a95e1ceb59b1f" src="https://user-images.githubusercontent.com/70130473/98509366-08a1dc00-229c-11eb-99cf-502e383557c3.png">

This is part of the data if the image fails to load successfully.
70.88 | 284236405 | 284236405 | U | 0 | unclassified |  
29.12 | 116795770 | 0 | R | 1 | root |  
29.12 | 116795770 | 166726 | R1 | 131567 | cellular organisms |  
28.93 | 116006363 | 2971917 | D | 2 | Bacteria |  
18.11 | 72612320 | 236157 | D1 | 1783272 | Terrabacteria group
17.86 | 71642599 | 203377 | P | 201174 | Actinobacteria |  
17.69 | 70936292 | 9040134 | C | 1760 | Actinobacteria |  
3.4 | 13638472 | 0 | O | 85008 | Micromonosporales
3.4 | 13638472 | 1557559 | F | 28056 | Micromonosporaceae
1.78 | 7135542 | 1855316 | G | 1873 | Micromonospora
0.28 | 1117673 | 65585 | G1 | 2617518 | unclassified Micromonospora
0.08 | 309402 | 309402 | S | 2675222 | Micromonospora sp.   WMMC415
0.05 | 210382 | 210382 | S | 2749844 | Micromonospora sp.   28ISP2-46
0.05 | 191912 | 191912 | S | 2583243 | Micromonospora sp. HM134
0.04 | 176424 | 176424 | S | 2039870 | Micromonospora sp.   WMMA2032
0.04 | 149728 | 149728 | S | 2201999 | Micromonospora sp. B006
0 | 14240 | 14240 | S | 648999 | Micromonospora sp. L5
0.08 | 340571 | 340571 | S | 47857 | Micromonospora   echinaurantiaca
0.08 | 331201 | 331201 | S | 1877 | Micromonospora echinospora
0.07 | 294057 | 294057 | S | 307121 | Micromonospora krabiensis

**Comment by jenniferlu717** [comment]
The rank code is labels "typical" taxonomic levels like G = genus, F = family, etc. However, sometimes there are taxonomic levels INBETWEEN the traditional levels. So G1 is a level inbetween genus and species, G2 is a level inbetween G1 and species etc. 

Hope that helps.
