### ISSUE TITLE
Yes, those files are designed to work within the path structure of the expanded software archive.  So you should download the archive, decompress it (or, instead of the last two steps, just clone the github repo) then change to the directory with the install script and run it from there.  The other surrounding files will then also be available.

### ISSUE THREAD

**Issue by MANZHAOHUI** [DerrickWood/kraken2#361]
Yes, those files are designed to work within the path structure of the expanded software archive.  So you should download the archive, decompress it (or, instead of the last two steps, just clone the github repo) then change to the directory with the install script and run it from there.  The other surrounding files will then also be available.

_Originally posted by @BenLangmead in https://github.com/DerrickWood/kraken2/issues/76#issuecomment-598123211_

**Comment by MANZHAOHUI** [comment]
Could you please give some details about this process? I also have trouble installing kraken2 using the following command:
$ ./install_kraken2.sh /kraken
mkdir: cannot create directory ‘/kraken’: Permission denied

thank you.

**Comment by jenniferlu717** [comment]
You need to move to a directory where you can create folders. That error happens when you're trying to modify a folder you do not have write-access to.

**Comment by MANZHAOHUI** [comment]
> You need to move to a directory where you can create folders. That error happens when you're trying to modify a folder you do not have write-access to.

I can definitely mkdir folders in this directory.

(base) [zhaohui@longleaf-login2 kraken2]$ mkdir -p kraken2
(base) [zhaohui@longleaf-login2 kraken2]$ ls
CHANGELOG.md  CMakeLists.txt  install_kraken2.sh  kraken2  LICENSE  README.md  scripts  src
(base) [zhaohui@longleaf-login2 kraken2]$ ./install_kraken2.sh /kraken2
mkdir: cannot create directory ‘/kraken2’: Permission denied

**Comment by MANZHAOHUI** [comment]
I solved this problem by copying the folder 'src' to the directory where install_kraken2.sh is located.
