### ISSUE TITLE
kraken2-build: no such file or directory

### ISSUE THREAD

**Issue by MANZHAOHUI** [DerrickWood/kraken2#363]
I followed the manual and successfully installed kraken2 and copied the main scripts to my bin (as is shown below)
(base) [zhaohui@longleaf-login1 KRAKEN2]$ ./install_kraken2.sh zhaohui_kraken2
make: Entering directory `/proj/barc/users/zhaohui/KRAKEN2/src'
cp estimate_capacity build_db classify dump_table lookup_accession_numbers /proj/barc/users/zhaohui/KRAKEN2/zhaohui_kraken2/
make: Leaving directory `/proj/barc/users/zhaohui/KRAKEN2/src'
./install_kraken2.sh: line 32: scripts/*: No such file or directory
(base) [zhaohui@longleaf-login1 KRAKEN2]$ ./install_kraken2.sh zhaohui_kraken2
make: Entering directory `/proj/barc/users/zhaohui/KRAKEN2/src'
cp estimate_capacity build_db classify dump_table lookup_accession_numbers /proj/barc/users/zhaohui/KRAKEN2/zhaohui_kraken2/
make: Leaving directory `/proj/barc/users/zhaohui/KRAKEN2/src'

Kraken 2 installation complete.

To make things easier for you, you may want to copy/symlink the following
files into a directory in your PATH:
(base) [zhaohui@longleaf-login1 KRAKEN2]$ echo $PATH
/nas/longleaf/home/zhaohui/anaconda3/bin:/nas/longleaf/home/zhaohui/anaconda3/condabin:/usr/local/bin:/usr/bin:/opt/puppetlabs/bin:/usr/local/sbin:/usr/sbin:/nas/longleaf/home/zhaohui/.local/bin:/nas/longleaf/home/zhaohui/bin
(base) [zhaohui@longleaf-login1 KRAKEN2]$ cp zhaohui_kraken2/kraken2{,-build,-inspect} /nas/longleaf/home/zhaohui/anaconda3/bin

However, I can by no means make the following command work:
(base) [zhaohui@longleaf-login1 KRAKEN2]$ kraken2-build --standard --db kraken2DB
: No such file or directory

whatever I do, I will get this error. 

what's more,  after I manually downloaded the minikraken database, and use the following script to generate the report, the same error pops up:

(base) [zhaohui@longleaf-login1 KRAKEN2]$ kraken2 --db minikraken_8GB_20200312 /proj/barc/users/zhaohui/paired_fastq/all40.fastq.gz --gzip-compressed --output all40.kraken --report all40.kraken.report
: No such file or directory

Anybody experienced this problem? And how can it be fixed? Thank you.

**Comment by MANZHAOHUI** [comment]
And I checked the kraken2 script, the dir has been modified to my installing directory:
use strict;
use warnings;
use Fcntl;
use File::Basename;
use Getopt::Long;

my $PROG = basename $0;
my $KRAKEN2_DIR = '/proj/barc/users/zhaohui/KRAKEN2/zhaohui_kraken2';

# Test to see if the executables got moved, try to recover if we can
if (! -e "$KRAKEN2_DIR/classify") {
  use Cwd 'abs_path';
  $KRAKEN2_DIR = dirname abs_path($0);
}

require "$KRAKEN2_DIR/kraken2lib.pm";
$ENV{"KRAKEN2_DIR"} = $KRAKEN2_DIR;
$ENV{"PATH"} = "$KRAKEN2_DIR:$ENV{PATH}";

**Comment by limfs92** [comment]
Hi @MANZHAOHUI,

I am experiencing the same problem here. It was running fine last week on the "kraken2-build" command but while I am doing it today, I have got the same error as yours, although I have included it into my /.bashrc. Have you found a solution for this?

Best,
Lim

**Comment by MANZHAOHUI** [comment]
> Hi @MANZHAOHUI,
> 
> I am experiencing the same problem here. It was running fine last week on the "kraken2-build" command but while I am doing it today, I have got the same error as yours, although I have included it into my /.bashrc. Have you found a solution for this?
> 
> Best,
> Lim

I just reinstalled kraken2 using conda and problem solved.
