### ISSUE TITLE
Are the Kraken2 databases found in the "Index Zone" ready for use right away?

### ISSUE THREAD

**Issue by Lamm-a** [DerrickWood/kraken2#365]
Are we able to use the databases found [here](https://benlangmead.github.io/aws-indexes/k2) instead of `kraken2-build` commands?

**Comment by fanli-gcb** [comment]
Yes, those tarballs contain the files created by kraken2-build:
```
hash.k2d: Contains the minimizer to taxon mappings
opts.k2d: Contains information about the options used to build the database
taxo.k2d: Contains taxonomy information used to build the database 
```
Just extract and fire away with your `kraken2` commands

**Comment by jenniferlu717** [comment]
@Lamm-a yes (as @fanli-gcb said)
