### ISSUE TITLE
EuPathDB48 library files

### ISSUE THREAD

**Issue by fanli-gcb** [DerrickWood/kraken2#366]
Hi,

Is there a download link to the library (FASTA) files used to create the EuPathDB48 database? This seems to contain more genomes since the original release here:
http://ccb.jhu.edu/data/eupathDB/

Thanks!
Fan

**Comment by jenniferlu717** [comment]
I haven't had a chance to update the website yet but the files to download are here: ftp://ftp.ccb.jhu.edu/pub/data/EuPathDB48

**Comment by promexjm** [comment]
Compared with the previous version, the number of blocked bases is reduced. So is the use of new filtering algorithm?

**Comment by jenniferlu717** [comment]
@promexjm  I'm not sure what the differences are that you are referring to. The filtering algorithm is the same, although dusting (removal of low complexity sequences) was performed before removing any contamination. 

I'm going to close this issue now as its not a Kraken2 problem, but if you have other questions, please email me at jlu26@jhmi.edu
