### ISSUE TITLE
Sharing Kraken2 DB indifferent jobs

### ISSUE THREAD

**Issue by diriano** [DerrickWood/kraken2#373]
Hi,
is there a way that I could load the kraken2 DB in RAM, and then different jobs (with diofferent source files or samples) query the same database?
Currently each of my jobs load the DB in memory, so this is limiting the amount of jobs that I can run in parallel. If I could shre the DB among jobs, I would be able to run more jobs in parallel. Wold this be possible?
Thanks

**Comment by ashenflower** [comment]
Hello @diriano, did you figure it how somehow?

**Comment by diriano** [comment]
Unfortunately not

**Comment by slw287r** [comment]
> Hello @diriano, did you figure it how somehow?

You can load the db into ram via `/dev/shm` on Linux system. Just copy the `*.k2d`s to `/dev/shm` and apply the new path to Kraken2.
