### ISSUE TITLE
build_db: OMP only wants you to use 1 threads

### ISSUE THREAD

**Issue by mohhefny** [DerrickWood/kraken2#374]
Hello,
I am building nt database useing kraken2-build and I used 32 threads. After few hours it failed with this error messages (the job err log):

`Found 67424684/67580164 targets, searched through 772297082 accession IDs, search complete.
lookup_accession_numbers: 155480/67580164 accession numbers remain unmapped, see unmapped.txt in DB directory
build_db: OMP only wants you to use 1 threads
`

How to fix this issue?
Thank you.

**Comment by bschiffthaler** [comment]
See my comment here: https://github.com/DerrickWood/kraken2/issues/348#issuecomment-743106099

**Comment by mohhefny** [comment]
> See my comment here: [#348 (comment)](https://github.com/DerrickWood/kraken2/issues/348#issuecomment-743106099)

Thank you very much. This is helpful. I also set the environment to the number of tasks within the script itself and it solved my issue
