### ISSUE TITLE
kraken2 classification Toxoplasma gondii and Plasmodium vivax

### ISSUE THREAD

**Issue by rocanja** [DerrickWood/kraken2#376]
Hello kraken2 team,
We have recently started using kraken2 to investigate the microbiome ('contamination') in our human RNAseq data derived from cell lines, xenografts and patient samples. Our input for kraken2 are the 'unmapped' reads after alignment to human and/or mouse and we have setup a kraken2 database that contains virus, archea, bacteria, plasmid, fungi and protozoa. 
Surprisingly, in the majority of our samples, the highest ranking microba are 'Toxoplasma gondii' and 'Plasmodium vivax' ... which is unexpected and since this is across the board of samples with various backgrounds, we were wondering whether this is a know artifact of some kind?

**Comment by mihkelvaher** [comment]
You could extract_kraken_reads.py (https://github.com/jenniferlu717/KrakenTools) and then blast the reads. Doesn't also hurt to visually inspect them (repeats? adapters? etc).

**Comment by fconstancias** [comment]
you should have a look there: https://github.com/DerrickWood/kraken2/issues/34

**Comment by rocanja** [comment]
> you should have a look there: #34

Thanks so much @fconstancias, this is exactly the information I was looking for! We have also done an alignment against Toxoplasma to check for the 'coverage of the sequence' and the reads only map very scatchy to a few scaffold regions of the Toxoplasma genome ... which supports the idea of it being a false positive result.

@rwst
> There are not only problems with taxonomic classifications of databases but also with contamination, see Lu/Salzberg, http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1006277. I found out the hard way yesterday that `protozoa` gives false _Toxoplasma_ and _Plasmodium_ positives, just as described in the above paper with EuPathDB.
> I think providing clean databases may need a concerted effort.

**Comment by jenniferlu717** [comment]
I'm glad that the script has been useful. That script was the main focus for KrakenTools and was developed to help in situations like this. I'm going to close this issue for now but feel free to open another issue if you have any other questions or concerns..

Also if you think of other downstream scripts that would be universally useful, feel free to open an issue in the KrakenTools github.
