### ISSUE TITLE
kraken2 database installation

### ISSUE THREAD

**Issue by jessikamarquis** [DerrickWood/kraken2#383]
Hi there.

I keep coming across this error everytime I try and install the bacteria database:

(base) jmarquis@nia-login01:/scratch/j/jronho/jmarquis$ kraken2-build --db krak                                   en_db --download-taxonomy
Downloading nucleotide gb accession to taxon map... done.
Downloading nucleotide wgs accession to taxon map... done.
Downloaded accession to taxon map(s)
Downloading taxonomy tree data... done.
Uncompressing taxonomy data... done.
Untarring taxonomy tree data... done.
(base) jmarquis@nia-login01:/scratch/j/jronho/jmarquis$ kraken2-build --db krak                                   en_db --download-library archaea
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 387 projects (602 sequences, 1.02 Gbp)... done.
All files processed, cleaning up extra sequence files... done, library complete                                   .
Masking low-complexity regions of downloaded library... done.
(base) jmarquis@nia-login01:/scratch/j/jronho/jmarquis$ kraken2-build --db krak                                   en_db --download-library bacteria
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 22395 projects (50181 sequences, 91.71 Gbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library.../home/j/jronho/jmarquis/miniconda3/libexec/mask_low_complexity.sh: line 27: 325025 CPU time limit exceeded $MASKER -in $file -outfmt fasta
     325026 Done                    | sed -e '/^>/!s/[a-z]/x/g' > "$file.tmp"

Is there anyone that can help me with this?
Thanks in advance!

**Comment by mihkelvaher** [comment]
As the error suggests, there's something wrong with masking.
You could first check if your dustmasker/segmasker works properly. If everything else fails, you could try the database without masking (and risk having more false positive results). See https://github.com/DerrickWood/kraken2/blob/master/docs/MANUAL.markdown#masking-of-low-complexity-sequences

**Comment by jessikamarquis** [comment]
got it! thanks

**Comment by jenniferlu717** [comment]
I'm going to close this issue for now but @jessikamarquis if you continue to have problems, feel free to open a new issue
