### ISSUE TITLE
Is it possible to build custom database from ONE multiple fasta file?

### ISSUE THREAD

**Issue by yifengyuan** [DerrickWood/kraken2#384]
Dear Derrick,

Currently Kraken2 adds reference genomes into custom database in the way that each fasta file is a reference genome.
Is that possible to add any arg/flag to let Kraken2 add reference genomes into custom database from ONE multi-fasta file in the way that each sequence is a reference genome? Thank you. 

Basically, I am wondering how to skip the process that split a multi-fasta file into single fasta files (the amount of Inodes would be a problem for me).

**Comment by DerrickWood** [comment]
This sounds like behavior that hasn't been in Kraken for quite a while. Others brought this issue to my attention over 6 years ago, so I fixed it in pre-1.0 Kraken (https://github.com/DerrickWood/kraken/commit/415658feb58e8407dc3e7740f052f820132b9775). As best as I can remember, Kraken 2 has never split multi-fasta files into actual single-fasta files, so I'm afraid I'm unsure what you're referring to here.

The Kraken 2 scripts for adding references to a custom library should accept a multi-fasta without problem - see our build code from the Kraken 2 paper, available here: https://github.com/DerrickWood/kraken2-experiment-code/blob/master/BuildScripts/build_kraken2.bash (the `strain_excluded.fna` file is a large multi-fasta file, and multiple single-fasta files aren't created anywhere).

So I believe the answer to your question is yes, but the way to do it is simply use `kraken2-build --add-to-library multifasta.fna --db $DBNAME`. If I'm misunderstanding something, please let me know, preferably with a small set of commands/data that can be used to replicate your issue.

**Comment by yifengyuan** [comment]
Thank you very much for your reply! You are correct. Kraken2 didn't split the multi-fast file. 
I am closing this issue. Thank you.
