### ISSUE TITLE
dowload of prebuilt databases :: ftp://ftp.ccb.jhu.edu/pub/data/kraken2_dbs requires password

### ISSUE THREAD

**Issue by EricDeveaud** [DerrickWood/kraken2#394]
Hello

few times ago I was abble to download prebuilt databases from ftp://ftp.ccb.jhu.edu/pub/data/kraken2_dbs
today it requires a login//password. 

how one can download prebuilt database ?

regards

Eric

**Comment by jenniferlu717** [comment]
Hello, I'm not sure why theres a login/password now required, but I'll look into it.

However, we are moving all of our kraken2 database hosting to this site:
https://benlangmead.github.io/aws-indexes/k2 so I would use those moving forward. 

The ccb ftp site hasnt been updated in awhile. The newest database are at the benlangmead.github website now.

**Comment by EricDeveaud** [comment]
thanks

**Comment by EricDeveaud** [comment]
Hello, after checking the kraaken index page I noticed that the minikraken provided is older tha the one that was provided on ccb ftp site.

ccb was providing: `minikraken_8GB_202003.tgz`  while benlangmead.github.io/ provides  `minikraken2_v2_8GB_201904.tgz` 

maybee it will worth the update 

regards

Eric

**Comment by jenniferlu717** [comment]
The minikraken 8GB databases are now labeled "Standard-8" or "PlusPF-8" on the benlangmead.github website They were updated December 2, 2020.

**Comment by EricDeveaud** [comment]
thnaks again
