### ISSUE TITLE
Adding additional genomes to prebuilt database

### ISSUE THREAD

**Issue by shreyaramachandran** [DerrickWood/kraken2#395]
Hello,
I am interested in using the complete PlusPFP database listed on Dr. Langmead's Index Zone. However, there are a few additional genomes from Refseq that I would also like to add to this pre-built database. Is there a way to use kraken-build to add more genomes to PlusPFP after downloading?

Thank you very much!

**Comment by mihkelvaher** [comment]
New sequences can't be added to a prebuilt database, you need the reference fasta sequences and build the whole database from scratch.
Also: #357

**Comment by shreyaramachandran** [comment]
Thank you, that helps! I realized that I'd have to rebuild the database from scratch, but I see now that I will have to download everything from scratch as well. That is, I have to download *all* the fasta files I'm interested in, including the species already in the database, and not just the new ones. 

I was wondering if I'd be able to delete just the .k2d files, add my additional species to the library, and then rebuild, but it seems like this is not the case?

**Comment by mihkelvaher** [comment]
If the library already contains all of the previous sequences, then removing `*.k2d` and `seqid2taxid.map` files, adding new and building afterwards should work.
I've extended the 'nt' database this way.

Just for testing and making sure you know all of the steps, create and build some small database (like `UniVec_Core`), then try to add a couple of seqs and build again. Lastly, `inspect` to make sure the seqs were actually added.

**Comment by jenniferlu717** [comment]
I'm going to close this issue, thank you so much @mihkelvaher for all of the helpful responses.

**Comment by gabridinosauro** [comment]
Hello, I am interested in adding a little guide on how to do it. 
I also have two species to add to the PFP datanbase.
I guess once downloaded it from here: https://benlangmead.github.io/aws-indexes/k2 and extracted.
I would have to cancel the two files *.k2d and seqid2taxid.map.

Then run the commands: 

```
kraken2-build --add-to-library genome_1.fasta --db /xdisk/gabri/final_database --threads 48
kraken2-build --add-to-library genome_2.fasta --db /xdisk/gabri/final_database --threads 48
```
and then build it, is that correct?
```
kraken2-build --build --db /xdisk/pkiela/schiro/petrullo/final_database --threads 48`
```

Thanks in advance,

Gabri
