### ISSUE TITLE
Start from a specific step when build database

### ISSUE THREAD

**Issue by XMTian** [DerrickWood/kraken2#396]
Hi,

May I know how long does it use to build the kraken2 database? I used the following command to construct the kraken2 database, everything goes well before the last output line "Masking low-complexity regions of downloaded library...", it took about 4 hours for the previous steps but take more than 15 hours in the last step. 
Do you know is anything wrong? If I want to start from "Masking low-complexity regions of downloaded library..." instead of restart from the beginning, do you have any suggestions?

```
kraken2-build --standard --threads 24 --db /Users/xmtian/PhD/db/kraken2
Downloading nucleotide gb accession to taxon map... done.
Downloading nucleotide wgs accession to taxon map... done.
Downloaded accession to taxon map(s)
Downloading taxonomy tree data... done.
Uncompressing taxonomy data... done.
Untarring taxonomy tree data... done.
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 388 projects (603 sequences, 1.02 Gbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library... done.
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 22466 projects (50916 sequences, 91.96 Gbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library...
```

Thanks in advance!

**Comment by AGalanis97** [comment]
I'm sure someone working on the standard database will be able to help you.
However, you can also download it already from here if needed:  https://benlangmead.github.io/aws-indexes/k2

I'm sharing because I also only recently became aware of this index zone and maybe it could help you in the future!

**Comment by XMTian** [comment]
Thank you for your prompt reply! I will try to figure it out with your suggestions.
