### ISSUE TITLE
kraken2-build --standard --threads 24 took 35 minutes in 2018, why is it taking 20 hours now with --threads 64?

### ISSUE THREAD

**Issue by pbuendia** [DerrickWood/kraken2#399]
In the manual it says
kraken2-build --standard --threads 24 --db $DBNAME
Using 32 threads on an AWS EC2 r4.8xlarge instance with 16 dual-core hyperthreaded 2.30 GHz CPUs and 244 GB of RAM, the build process took approximately 35 minutes in Jan. 2018.

I ran 
kraken2-build --standard --threads 64 --db $DBNAME
on a 64 vCPUs, 240 GB memory Linux VM. I could see that all 64 CPUs are being used at 100% during the build_db command with 150 sequences processed in a minute. That is very slow given that for the last step after the CHT creation step there were  99868 sequences processed. 
I know that the databases have grown since 2018 but should the speed slow down so much?

My questions are: 
Why is this so slow? And is it normal?
How do I speed it up except adding more RAMs and CPUs?
Is the nr database larger than the standard db? I ask, because my run processed 99868 sequences, but the same command for the nr database completed processing of [163460797 sequences](https://github.com/DerrickWood/kraken2/issues/181). 

This is the run with times added:
```
(6 pm start --threads 64)
Downloading nucleotide gb accession to taxon map... done.
Downloading nucleotide wgs accession to taxon map... done.
Downloaded accession to taxon map(s)
Downloading taxonomy tree data... done.
Uncompressing taxonomy data... done.
Untarring taxonomy tree data... done.
Step 1/2: Performing rsync file transfer of requested files
(1 hour for --threads 64)
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 388 projects (603 sequences, 1.02 Gbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library... done.
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 22545 projects (51097 sequences, 92.29 Gbp)... done.
All files processed, cleaning up extra sequence files... done, library complete
(2 hours for --threads 64)
Masking low-complexity regions of downloaded library...done.
(> 5 hours (running overnight) --threads 64)
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 10547 projects (13171 sequences, 396.42 Mbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library... done.
Downloading plasmid files from FTP... done.
Masking low-complexity regions of downloaded library... done.
mv: replace 'assembly_summary.txt', overriding mode 0444 (r--r--r--)? y
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 1 project (639 sequences, 3.27 Gbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Downloading UniVec_Core data from server... done.
Adding taxonomy ID of 28384 to all sequences... done.
Masking low-complexity regions of downloaded library... done.
Creating sequence ID to taxonomy ID map (step 1)...
Found 31382/31471 targets, searched through 779197899 accession IDs, search complete. 
(15 hours - overnight until 9 am --threads 64)
lookup_accession_numbers: 89/31471 accession numbers remain unmapped, see unmapped.txt in DB directory
Sequence ID to taxonomy ID map complete. [2m18.888s]
Estimating required capacity (step 2)...
Estimated hash table requirement: 51141602740 bytes
Capacity estimation complete. [15m1.405s]
Building database files (step 3)...
Taxonomy parsed and converted.
CHT created with 15 bits reserved for taxid.
Completed processing of 99868 sequences, 99783969334 bp 
(20 hours --threads 64)
Writing data to disk...  complete.
Database files completed. [4h47m40.716s]
Database construction complete. [Total: 5h5m1.030s]
(20 hours & some minutes)
```
This is what I got
```
-rw-r--r-- 1 rsa-key-20201228 rsa-key-20201228  48G Jan 18 19:04 hash.k2d
drwxr-xr-x 8 rsa-key-20201228 rsa-key-20201228 4.0K Jan 18 13:59 library
-rw-r--r-- 1 rsa-key-20201228 rsa-key-20201228   64 Jan 18 19:04 opts.k2d
-rw-r--r-- 1 rsa-key-20201228 rsa-key-20201228 3.2M Jan 18 14:01 seqid2taxid.map
-rw-r--r-- 1 rsa-key-20201228 rsa-key-20201228 2.4M Jan 18 14:16 taxo.k2d
drwxr-xr-x 2 rsa-key-20201228 rsa-key-20201228 4.0K Jan 18 13:59 taxonomy
-rw-r--r-- 1 rsa-key-20201228 rsa-key-20201228 1.1K Jan 18 14:01 unmapped.txt
```

**Comment by AGalanis97** [comment]
nr is significantly larger than the standard database. I have also used the same command as you are using with very similar RAM (actually 256GB) to build the nt and it takes about 24 hrs (more or less).

According to the manual:

**Comment by AGalanis97** [comment]
nr is significantly larger than the standard database. I have also used the same command as you are using with very similar RAM (actually 256GB) to build the nt and it takes about 24 hrs (more or less). The nr database is probably approximately 200GB, while the standard database is about 30-40GB as far as I remember. So I wouldn't say it's unexpected to have such a long building time. 

According to the manual: 
> Kraken 2 allows users to perform a six-frame translated search, similar to the well-known BLASTX program. To do this, Kraken 2 uses a reduced 15 amino acid alphabet and stores amino acid minimizers in its database. LCA results from all 6 frames are combined to yield a set of LCA hits, which is then resolved in the same manner as in Kraken's normal operation.

> To build a protein database, the --protein option should be given to kraken2-build (either along with --standard, or with all steps if building a custom database).

**Comment by pbuendia** [comment]
Thanks AGalanis97 for your reply.
I will answer my other questions as I figured out a few things and hope it helps others who experience the same slow run. 
I learned that there is more to look at than the CPU number and memory size in a cloud VM configuration. I have now access to a new VM with 60 vCPUs and 240 RAM and the command 
kraken2-build --standard --threads 60 --db $DBNAME
is running faster and should end in 3 hours for a total of 7 hours. The last step of processing the sequences is still very slow.

The new VM has an SSD disk instead of an HDD (Standard persistent disk) which is significantly faster. The slow VM had vCPUs with 2.3 GHz, the new one has 3.1 GHz vCPUs (with up to 3.8 GHz sustained all-core turbo).

**Comment by renatapirani** [comment]
Hi all,
I am trying to run kraken but the number of --threads is not working.  I am getting the same error over and over no matter which number I include on it (16, 24, 32...). 
Error:                                                                                                                     
Value "--threads" invalid for option confidence (real number expected)                                                             
kraken2: database ("/scratch/genomics/piranir/Kraken2/anolis_d1.fasta") does not contain necessary file taxo.k2d   

My job is: kraken2 --db input.fasta --report kraken_report --use-names --confidence --threads 32 output_kraken.fa

The memory is that I am using here is: 
#$ -pe mthread 10 
#$ -l mres=40G,h_data=4G,h_vmem=4G

Any help I will appreciate.   
Thank you.

**Comment by AGalanis97** [comment]
Hi,

the problem is that you are using the --confidence flag but you haven't specified the confidence threshold so it thinks that what comes after --confidence, in other words the whole part --threads 32 output_kraken.fa, is the confidence threshold which should be anything between 0 and 1. The code is correct you just need to say what kind of confidence threshold you want to use by simply picking any number between 0 and 1. So you can try running:
`kraken2 --db input.fasta --report kraken_report --use-names --confidence 0.05 --threads 32 output_kraken.fa`
0.05 is a good starting point for a confidence threshold, but you may want to investigate what suits you best!

**Comment by renatapirani** [comment]
Thanks @AGalanis97 , it worked. 
But now I am getting this error: 
kraken2: database ("input_d1.fasta") does not contain necessary file taxo.k2d

I think the problem is on the amount of memory I am asking, maybe it is not enough for this job.

**Comment by jenniferlu717** [comment]
The command line suggested by @AGalanis97 is incorrect, replace input.fasta with the path to the kraken database build (folder where hash.k2d is). After --threads 32, then specify the read file input.fasta > output.txt

**Comment by renatapirani** [comment]
Thank you so much @jenniferlu717 . It is working perfectly now!!!

**Comment by renatapirani** [comment]
Hi all, I have another question.
After running kraken2, I got the *.log file with all my results (prefect). 
However, I would like to to have a list of the contigs. But when I run the command line below, the output is empty and I dont know hoe to fix it. 

grep "Contig" output_kraken.log > kraken2_results.txt

After that, I would like to remove anything classified as bacteria, plasmids or viruses. 

grep "unclassified\|Homo sapiens" kraken2_results.txt | cut -f2 > assembly.fa.HsU.list

But If the first command is not generating any output, the second one is not working as well. I really appreciate any help. 
Best, 
Renata
