### ISSUE TITLE
Could krakenhll used by kraken2

### ISSUE THREAD

**Issue by yi1873** [DerrickWood/kraken2#4]
Kraken has upgraded to version 2, but Krakenhll could be used by kraken2 to get kmer_coverage results ?

**Comment by DerrickWood** [comment]
KrakenHLL, to my understanding, is a separate program, forked from Kraken 1. Kraken 2 is a rewrite of the entire code base of Kraken 1, without any guarantee of backwards compatibility with outside programs. We may at a future date include similar functionality from KrakenHLL into Kraken 2, however.
