### ISSUE TITLE
Problem Building Kraken2 Database 

### ISSUE THREAD

**Issue by danielsh3n** [DerrickWood/kraken2#402]
I get this error when building the Kraken2 database: 

Downloading nucleotide est accession to taxon map...rsync: link_stat "/taxonomy/accession2taxid/n$
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1651$
done

I poked around threads from over a year ago and it seems to be an issue w/ NCBI's naming of files and Kraken2's code? Has this been resolved? Anyone else have a similar issue?

**Comment by danielsh3n** [comment]
Some other information that might be relevant - I'm installing this onto NFS storage, am using a conda environment, and am running on the MacOS system.

**Comment by AGalanis97** [comment]
hey, i think i had also that problem once.. have you tried the --use-ftp flag? seems like a downloading error

**Comment by danielsh3n** [comment]
Hmmm. I did try this: kraken2-build --download-taxonomy --use-ftp --db before and I remember that command wasn't valid?

**Comment by khoriba** [comment]
maybe the same problem.

```
Downloading nucleotide est accession to taxon map...rsync: link_stat "/taxonomy/accession2taxid/nucl_est.accession2taxid.gz" (in pub) failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1651) [Receiver=3.1.2]
```

**Comment by khoriba** [comment]
I'm sorry. My problem was solved with a Kraken2 update. 
It was because I downloaded and installed Kraken2 in 2019 and didn't update it.
thanks.
