### ISSUE TITLE
Experience with PacBio HiFI / CCS reads

### ISSUE THREAD

**Issue by caspargross** [DerrickWood/kraken2#408]
Is it possible to use Kraken2 with Pacbio CCS (HiFi) reads?
Are there any publications on this Topic?

Thanks, Caspar

**Comment by ms-gx** [comment]
I am pretty sure this should work well, since the HiFi reads have a high accuracy. What do you want to do?

**Comment by caspargross** [comment]
Removal of human host reads for Sars-Cov-2 sequencing. 
We use this step in our Illumina based Pipeline, I will just try it out when the data is ready.
Thanks!

**Comment by ms-gx** [comment]
Ah, I see.

You might want to use a mapping-based approach for this. I think this could be better potentially.

**Comment by bishopia** [comment]
on a related note, are there particular parameter adjustments anyone would recommend that might improve classification with hifi reads? I'm specifically wondering about --minimum-hit-groups and --confidence values. my explicit goal is to remove microbiome reads prior to eukaryotic de novo assembly.

**Comment by ms-gx** [comment]
Why don't you assemble first and then remove contamination? Since you have HiFi reads I would not worry too much about mixed assembly between eukaryote and contamination. After the assembly the picture should get much simpler. Then a simple Blast approach might be better.
