### ISSUE TITLE
Problem with pre-built "EuPathDB48"?

### ISSUE THREAD

**Issue by ms-gx** [DerrickWood/kraken2#409]
I use Kraken2 v. version 2.1.1

If I compile my own database or if I use the pre-compiled "Standard" database (https://genome-idx.s3.amazonaws.com/kraken/k2_standard_20201202.tar.gz) everything works well when I classify my raw Illumina data.

However, the pre-built "EuPathDB48" (https://genome-idx.s3.amazonaws.com/kraken/k2_eupathdb48_20201113.tar.gz) seems to have a problem for me. I have three observations which are suspicious:
1) The DB loads extremely fast to RAM compared to other kraken2 databases with similar size
2) I get zero hits. Either from a metagnomic random sample as well as a sample which should contain a target
3) The "Inspect"-file which comes with the DB is empty

Can someone look into this?

**Comment by jenniferlu717** [comment]
I just double checked and I'm not getting the same issues using that database link. I suspect that the database did not download correctly for you? Can you try to download/unzip the database again?

**Comment by ms-gx** [comment]
I downloaded and unzipped again. Still not working on data I would expect at least some hits.

As an additional test I compared two genome assemblies which are reported to be in the DB against the EuPathDB:
https://www.ncbi.nlm.nih.gov/assembly/GCA_000182405.1/
https://www.ncbi.nlm.nih.gov/assembly/GCA_000826245.1/

Still zero sequences classified. Am I doint something wrong? My call is:
`kraken2 --db /path/EuPathDB48/ --output out_eupath.txt --report report_eupath.txt ncbi-genomes-2021-02-03/GCA_000182405.1_ASM18240v1_genomic.fna `

**Comment by ms-gx** [comment]
By the way: can you maybe add m5d hashes, at least for the very large downloads. That would be awesome :)

**Comment by ms-gx** [comment]
It is related to this bug:
https://github.com/DerrickWood/kraken2/commit/a88a61e2befc0d904db36ec31b69c6c6f277b7fa

Since EuPathDB48 has `k=l` the index does not work with the last release. As soon I cloned the last (unreleased) version of Kraken2 EuPathDB48 index works for me.
