### ISSUE TITLE
special database - greengenes

### ISSUE THREAD

**Issue by pedrocr83** [DerrickWood/kraken2#413]
Hi there, 

quick question, if i want to add new sequences to a special database such as greengenes 16S do i add "--add-to-library" before the build process or can i do it after building it and just run build again?

Thank you!

**Comment by jenniferlu717** [comment]
Add the sequences using `--add-to-library` before the build process

**Comment by pedrocr83** [comment]
Hi there!
Thank you, i'll close the issue then.
