### ISSUE TITLE
feature: accession blacklist

### ISSUE THREAD

**Issue by rwst** [DerrickWood/kraken2#42]
I have a list of 303 accession IDs in `protozoa` that apparently consist completely of sequences that produce hits from other domains (and so they would give false positives when using `protozoa`). I would now like to have the feature that kraken, when building a database, looks up IDs in my blacklist so the accessions are no longer included with any new database build. Sounds reasonable?

**Comment by DerrickWood** [comment]
I'll have to think a bit about how best to implement this, but in the short term, you can hack your way to something like that by starting a build, then using Ctrl+C to stop it after the sequence ID to taxid map is created. You can then edit the `$DBNAME/seqid2taxid.map` file, deleting the offending accession IDs, and restart the build, e.g.:

    $ kraken2-build --db $DBNAME --build
    Creating sequence ID to taxonomy ID map (step 1)...
    Sequence ID to taxonomy ID map complete. [0.012s]
    Estimating required capacity (step 2)...^C
    $ vi $DBNAME/seqid2taxid.map  # or edit however you like
    $ kraken2-build --db $DBNAME --build
    Creating sequence ID to taxonomy ID map (step 1)...
    Sequence ID to taxonomy ID map already present, skipping map creation.
    Estimating required capacity (step 2)...   # build progresses on...

If `seqid2taxid.map` doesn't have a sequence ID present for a given file, that sequence won't be added into the database.
