### ISSUE TITLE
Incorrect taxids in classified-out

### ISSUE THREAD

**Issue by donutbrew** [DerrickWood/kraken2#44]
I haven't taken the time to track down the source, but I have noticed that the annotated fastq files that are output by '--classified-out' have incorrect taxids. 

For example, I have a certain taxid in the kraken2 output file and report file, and regex-ing the classified-out I can't even find that taxid. If I go find the read name in the output file and pull it by name out of the classified-out fastq, the read is what I think it is, but the "taxid|XXXX" annotation is wrong. I can't see a logical reason for the taxid that is printed. However, the number printed in the fastq is consistently wrong, so taxid 9606 is represented as 19742 every time.

**Comment by DerrickWood** [comment]
Thanks for bringing that to my attention - I believe this is now fixed in https://github.com/DerrickWood/kraken2/commit/343a2d09f46b0d5bca1a3238880ccc274241a8b3

**Comment by firelabber** [comment]
Hmmmn, I am still having this problem

**Comment by NBaileyNCL** [comment]
Hi

I've noticed a similar issue. There are lots of taxid|0 annotations in the output from --classified-out. How can taxid be 0 if they're classified?

More perplexing still - reads in --classified-out and --unclassified-out don't add up to the number of input reads, even if I add all the taxid|0 from --classified-out

Is there any explanation for this?

Any help much appreciated

**Comment by laugon10** [comment]
Hi,
I am having just the same problem. I have a species up to 30% in the report but the taxid is not present in the classified-out file. How could this be possible? 

Any explanation or correction for this?

Thank you very much
