### ISSUE TITLE
add genomes to existing database

### ISSUE THREAD

**Issue by bhanusakhamuri** [DerrickWood/kraken2#45]
Hi i have already built the standard database using the kraken2-build. How can i add more genomes to the bacterial library in the database.

**Comment by jenniferlu717** [comment]
I would delete the *.k2d files and the seqid2taxid.map file and use this:
` kraken2-build --add-to-library $NEW_FILE --db . `
and then rebuild. You cannot add in new genomes once the database is built but you can just add more to the library before building.

**Comment by nick-youngblut** [comment]
So there's no way combining build databases? That would allow for batching `kraken2-build --build` jobs, which could speed things up a lot if the user utilizes a compute cluster

**Comment by jenniferlu717** [comment]
There is no current way to combine builds due to the way that the database is stored in memory.
