### ISSUE TITLE
Bacteria, fungi and viruses in the same db

### ISSUE THREAD

**Issue by termithorbor** [DerrickWood/kraken2#453]
Hi all,

Is it recommended to use a db with bacteria, fungi and virus in it or are the kmers too different to get reasonable results?

Thanks in advance :)

**Comment by BenLangmead** [comment]
Yes, this is a standard index to make.  E.g. the "PlusPF" and "PlusPFP" databases described here include all of those taxa: https://benlangmead.github.io/aws-indexes/k2
