### ISSUE TITLE
kraken2 for short 16S

### ISSUE THREAD

**Issue by raw937** [DerrickWood/kraken2#46]
Hello, 

I have older 1.5 Illumina 16S data. I am wondering if kraken2 can use it?
Also, how do I get the 16S databases? Just format from the fasta? Can I add custom sequences?

Cheers
Rick

**Comment by DerrickWood** [comment]
I can't think of a reason why Kraken 2 wouldn't be able to handle that older Illumina data. As for getting the 16S databases, you'd want to use one of the "special" databases, e.g.:

    kraken2-build --db newdb --special silva
