### ISSUE TITLE
Kraken2 download link not working

### ISSUE THREAD

**Issue by geethanjali97** [DerrickWood/kraken2#462]
Hello 
I tried downloading minikraken database, but the link seems broken.
Also the link to silva, RDP and othere database is also not working

**Comment by BenLangmead** [comment]
I tried the links just now and they worked for me.  Are they still not working for you?  If they are not, could you supply the specific URLs you are attempting to download from?

**Comment by geethanjali97** [comment]
hey i just tried again, but doesn't seems to work
here is the link-  https://ccb.jhu.edu/software/kraken2/index.shtml?t=downloads

**Comment by jenniferlu717** [comment]
@geethanjali97 We have moved all of our kraken2 downloads to https://benlangmead.github.io/aws-indexes/

**Comment by geethanjali97** [comment]
ohk thank you so much @jenniferlu717
