### ISSUE TITLE
Less classified reads using kraken2.1.2 compared to kraken2.0.8

### ISSUE THREAD

**Issue by ellyyuyang** [DerrickWood/kraken2#466]
Hello Kraken2 developers,

Thanks for the awesome tool and its has been really helpful for me. Much appreciated for all your efforts in maintaining and updating Kraken2!

I have recently found something interesting and would like to see if you can show me any pointers to help me understand what I could be potentially doing wrong please. Thanks!

So I constructed Kraken2 database using **GTDB-R202** with **Kraken2.1.2**. 
I then proceeded with classifying one sample of mine using two different versions of Kraken2: **Kraken2.0.8 and Kraken2.1.2** with exactly the same command and database. However, I found that the %classified was 15% lower using **Kraken2.1.2 (32.66%)** than **Kraken2.0.8 (47.78%)**. Below is the command I used for both version of kraken2

_kraken2.1.2 \  #kraken2.0.8 for v2.0.8
  --db /gtdb_r202_db/ 
  /clean_paired.pair1.truncated.fa \
  /clean_paired.pair2.truncated.fa \
  --output clean_kraken2_gtdb_r202 \
  --use-names \
  --report clean_kraken2_gtdb_r202_report \
  --classified-out clean_kraken2_gtdb_r202_classified  \
  --threads 30 \
  --unclassified-out clean_kraken2_gtdb_r202_unclassified_

Thanks in advance!

Best,
Elly

**Comment by jenniferlu717** [comment]
We changed the code to reduce the number of false positives in the sample (using the --minimum-hit-groups parameter) so this may have resulted in less classified reads

**Comment by ellyyuyang** [comment]
> We changed the code to reduce the number of false positives in the sample (using the --minimum-hit-groups parameter) so this may have resulted in less classified reads

Ah right, now I see it! Sorry, careless me not noticing it before! Thanks!
