### ISSUE TITLE
Would "add-to-library" build upon the existing library/added folder or override the existing one? 

### ISSUE THREAD

**Issue by ellyyuyang** [DerrickWood/kraken2#468]
Hello Developers,

Sorry if I have missed this info somewhere, but I was wondering if the "add-to-library" option would override the masked files already in the library/added folder?

I killed my "add-to-library" command halfway and ran the same "add-to-library" command again with an expanded genome folder that contained the genomes used in the previous "add-to-library“ command. I was wondering in this case, was I supposed to clear the library/added folder before running the second-time "add-to-library" command, or would it override the mask files built from the first-time "add-to-library" command so that I wouldnt need to clear the library/added folder? How would this affect the kraken2 output?

Thanks,
Elly

**Comment by jenniferlu717** [comment]
"add-to-library" does not overwrite any files in the library/added folder.
