### ISSUE TITLE
Rsync errors and possible solution

### ISSUE THREAD

**Issue by timkahlke** [DerrickWood/kraken2#48]
Hi,
I had the same/a similar problem as described here https://github.com/DerrickWood/kraken2/issues/38 and https://github.com/DerrickWood/kraken/issues/114. However, for me rsync only failed once in a while: the taxonomy download via `download_taxonomy.sh` mostly ran through. However, the syncing of the genomic DNA files sometimes died. I'm not sure if it is a problem/timeout with the NCBI rsync server or if it's client side on our cluster.

However, a potential workaround is to add a check in the rsync system call in `rsync_from_ncbi.pl` to retry syncing in case rsync returns anything but 0:

```
my $rc = 1;
while($rc){
   print STDOUT "\nTrying rsync\n";
   $rc = system("rsync --no-motd --files-from=manifest.txt rsync://ftp.ncbi.nlm.nih.gov/genomes/ .");
}
```
This is a potential infinite loop, of course. Could be adjusted to only do it if the error msg is _Network is unreachable (101)_ or a counter or something.

**Comment by BenLangmead** [comment]
In our experience, the solution to the periodic rsync failures is to add `--use-ftp`.  I will close for now but feel free to reopen if you see consistent issues even with that option.  (We will consider making it the default.)
