### ISSUE TITLE
build_kraken2_db.sh: line 84: lookup_accession_numbers: command not found

### ISSUE THREAD

**Issue by jessicarowell** [DerrickWood/kraken2#487]
Over the last few days, I ran these commands to build an nt database for kraken2:

`kraken2-build --download-taxonomy --db nt_db`
`kraken2-build --download-library nt --threads 32 --db nt_db`

I now have a directory, `nt_db`, containing two folders: `taxonomy/` and `library/`.

Now I want to build this custom database:
`kraken2-build --build --threads 32 --db nt_kraken_db`

When I try it, I get the following result on STOUT:
```
Creating sequence ID to taxonomy ID map (step 1)...
/home/ec2-user/src/kraken2/scripts/build_kraken2_db.sh: line 84: lookup_accession_numbers: command not found
```

Any idea what is causing this?
Thanks!

**Comment by JSSaini** [comment]
I have some similar issues. Stuck with building db.

**Comment by jessicarowell** [comment]
Ok so I had only added the `scripts` directory (in my kraken install directory) to my PATH.  There are a ton of other scripts in the parent directory that need to be added to your PATH.  That seems to have fixed the problem.
