### ISSUE TITLE
--report not working, output is the same as if you don't use it

### ISSUE THREAD

**Issue by morganleepetrovich** [DerrickWood/kraken2#49]
Hello,

I've been trying to generate a report with the formatting for --use-mpa-style, and my code is just giving the exact same output as when I don't use the options --report --use-mpa-style. Here is what I am inputting exactly:

kraken2 --db /projects/b1052/krakenDB/ /projects/b1052/Wells_b1042/Morgan/assembled/idba/S_AS1_contig.fa --report --use-mpa-style > /projects/b1052/Wells_b1042/Morgan/Kraken2/Output/S_AS1_Kraken_Output_Report.txt

But the output still looks like this, which is identical to the output without the extra report options specified:

C	contig-101_31860	990316	600	990316:566

Can you please let me know why this isn't working?

**Comment by rwst** [comment]
I think you need to give a filename with the `--report` option because the output to stdout is not the report but the class./unclass. info.

**Comment by morganleepetrovich** [comment]
I tried that as well, using the following syntax:

kraken2 --db /projects/b1052/krakenDB/ /projects/b1052/Wells_b1042/Morgan/assembled/idba/S_AS1_contig.fa > /projects/b1052/Wells_b1042/Morgan/Kraken2/Output/S_AS1_Kraken_Output_Test.txt --report --use-mpa-style > /projects/b1052/Wells_b1042/Morgan/Kraken2/Output/S_AS1_Kraken_Output_Report.txt


The report file is the same as I listed above, and the "Test" file which I imagined should have contained the classifications is completely empty.

**Comment by morganleepetrovich** [comment]
The second file name in the above syntax was intended to be the report: /projects/b1052/Wells_b1042/Morgan/Kraken2/Output/S_AS1_Kraken_Output_Report.txt

However, I did try doing it in this order (below) instead, and it gave a correct report file, but the classification file /projects/b1052/Wells_b1042/Morgan/Kraken2/Output/S_AS1_Kraken_Output_Test.txt was still empty. Maybe it's just not possible to do both tasks simultaneously and the report has to be generated separately from the classifications.

kraken2 --db /projects/b1052/krakenDB/ --output /projects/b1052/Wells_b1042/Morgan/Kraken2/Output/S_AS1_Kraken_Output_Report.txt --report /projects/b1052/Wells_b1042/Morgan/Kraken2/Output/S_AS1_Kraken_Output_Report_Default.txt /projects/b1052/Wells_b1042/Morgan/assembled/idba/S_AS1_contig.fa

**Comment by rwst** [comment]
You say "but the classification file /projects/b1052/Wells_b1042/Morgan/Kraken2/Output/S_AS1_Kraken_Output_Test.txt was still empty" but you never give that filename in your command:
>kraken2 --db /projects/b1052/krakenDB/ --output /projects/b1052/Wells_b1042/Morgan/Kraken2/Output/S_AS1_Kraken_Output_Report.txt --report /projects/b1052/Wells_b1042/Morgan/Kraken2/Output/S_AS1_Kraken_Output_Report_Default.txt /projects/b1052/Wells_b1042/Morgan/assembled/idba/S_AS1_contig.fa

**Comment by morganleepetrovich** [comment]
Oh I see the problem now! I meant to change that first file name /projects/b1052/Wells_b1042/Morgan/Kraken2/Output/S_AS1_Kraken_Output_Report.txt to S_AS1_Kraken_Output_Test.txt. The second one S_AS1_Kraken_Output_Report_Default.txt is the report which worked correctly, and now it looks like the classification file also worked correctly when run simultaneously. So then, the correct syntax to make this work is:

kraken2 --db /projects/b1052/krakenDB/ --output /projects/b1052/Wells_b1042/Morgan/Kraken2/Output/S_AS1_Kraken_Output_Test.txt --report /projects/b1052/Wells_b1042/Morgan/Kraken2/Output/S_AS1_Kraken_Output_Report_Default.txt /projects/b1052/Wells_b1042/Morgan/assembled/idba/S_AS1_contig.fa

Thank you for your help!
