### ISSUE TITLE
unexpected FTP path (new server?)

### ISSUE THREAD

**Issue by lynngao** [DerrickWood/kraken2#508]
Hi there,

I used this command to download standard library:
kraken2-build --use-ftp --standard --threads 24 --db database/

and the error message shows like this:
Downloading nucleotide gb accession to taxon map... done.
Downloading nucleotide wgs accession to taxon map... done.
Downloaded accession to taxon map(s)
Downloading taxonomy tree data... done.
Uncompressing taxonomy data... done.
Untarring taxonomy tree data... done.
rsync_from_ncbi.pl: unexpected FTP path (new server?) for https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/762/265/GCF_000762265.1_ASM76226v1

I checked on the ncbi directory this GCF_000762265.1_ASM76226v1 folder actually exists, but don't know why this error occurs. Is there any solution for this? Thank you so much!

**Comment by jquxch1** [comment]
How did you change the line in your file? I downloaded the file, changed the line, and uploaded it back with the same name, and now I get this error: /work/j/jquach1/kraken2-2.1.2/download_genomic_library.sh: line 56: /work/j/jquach1/kraken2-2.1.2/rsync_from_ncbi.pl: Permission denied

**Comment by shengxin450** [comment]
hi，excuse me ,could you help me how to use your codes? for example, I want to download the kraken2 standard db ,by using"kraken2-build --use-ftp --standard --threads 24 --db database/", so how can I use your codes to change or correct my codes? 
 if (! ($full_path =~ s#^ftp://${qm_server}${qm_server_path}/##)) { kraken2-build --use-ftp --standard --threads 24 --db database/ }
to
if (! ($full_path =~ s#^https://${qm_server}${qm_server_path}/##)) {kraken2-build --use-ftp --standard --threads 24 --db database/ }          
?? ?
Thanks for your help , very much!
(我来自中国，不知老师是否会说汉语，我想问，关于kraken2的这个报错，我该如何将您的代码结合到"kraken2-build --use-ftp --standard --threads 24 --db database/"这个代码中，请老师指点迷津，十分感谢)

**Comment by lynngao** [comment]
> hi，excuse me ,could you help me how to use your codes? for example, I want to download the kraken2 standard db ,by using"kraken2-build --use-ftp --standard --threads 24 --db database/", so how can I use your codes to change or correct my codes? if (! ($full_path =~ s#^ftp://${qm_server}${qm_server_path}/##)) { kraken2-build --use-ftp --standard --threads 24 --db database/ } to if (! ($full_path =~ s#^https://${qm_server}${qm_server_path}/##)) {kraken2-build --use-ftp --standard --threads 24 --db database/ } ?? ? Thanks for your help , very much! (我来自中国，不知老师是否会说汉语，我想问，关于kraken2的这个报错，我该如何将您的代码结合到"kraken2-build --use-ftp --standard --threads 24 --db database/"这个代码中，请老师指点迷津，十分感谢)

Hi, you only need to change the "ftp" into "https" in the rsync_from_ncbi.pl file. Do not modify other codes. kraken2-build --use-ftp --standard --threads 24 --db database/ is a command you need to run in linux system.
你好，kraken2-build是一个需要在linux上run的command，不是代码文件里面的代码。这里的主要问题是原作者在写rsync_from_ncbi.pl这个文件的时候读取的文件里面下载网址是ftp开头的，但是实际我们下载下来网址是https开头的，所以只需要把这个文件里面的ftp改成https即可。

**Comment by shengxin450** [comment]
谢谢老师，我回去试试，还有想请问老师，就是rsync_from_ncbi.pl这个.pl文件在linux的什么位置？

**Comment by lynngao** [comment]
> 谢谢老师，我回去试试，还有想请问老师，就是rsync_from_ncbi.pl这个.pl文件在linux的什么位置？

在kraken2的文件夹里

**Comment by shengxin450** [comment]
尊敬的lynngao老师，最近多有打扰，十分感谢老师您耐心的回答我的问题，处理这个问题太曲折了。先是按照您的指导，使用find命令找到了rsync_from_ncbi.pl 这个文件，手动 （就是将文件下载下来，修改后再替换原文件，因为我不会用linux命令在线修改）修改了rsync_from_ncbi.pl的第46行的https，结果还是报错，提示还是unexpected FTP path (new server?)故我怀疑修改的不彻底，kraken2依托的conda环境的rsync_from_ncbi.pl 也需要修改，故按照老师的指导将ftp改成https，还是报错（我都快崩溃
了，当然我知道肯定是我自己机器或者操作的问题），这次报错的内容是：~/.../download_genomic_library.sh: line 56: ~/.../miniconda3/envs/qc2/libexec/rsync_from_ncbi.pl: Permission denied，一看是文件权限问题，故顺藤摸瓜，在FileZilla将所有该文件的权限变为 “可执行” ，这才顺利跑通。十分感谢老师的启迪和指导，祝lynngao小姐姐工作顺利+学业有成！！Best wishes！Thank you very much！！

**Comment by Luponsky** [comment]
worked for the kraken2 installed from conda, but I had to change the same line also from a local installation of kraken2.
Thanks,
L

**Comment by liaochenlanruo** [comment]
kraken2的数据库是超级难安装

**Comment by YJGeng-Iriy** [comment]
您的邮件已确认收到，祝您万事如意，每天都有好心情（此为自动回复）

**Comment by zhp2333** [comment]
Thank you very much. Very helpful！

**Comment by Gambrian** [comment]
您的邮件已确认收到，祝您万事如意，每天都有好心情（此为自动回复）
