### ISSUE TITLE
Kraken2 database does not contain the necessary file taxo.k2d

### ISSUE THREAD

**Issue by ZhenyanZhang** [DerrickWood/kraken2#514]
Hi everyone,

I run the Kraken2 for my samples after installed standard database, however, it gave me an error that does not contain the necessary file taxo.k2d

I reinstalled the database several time but still got the same error. I have no idea what's wrong with it.

your help is appreciated

**Comment by nashanghenzan** [comment]
> Hi everyone,
> 
> I run the Kraken2 for my samples after installed standard database, however, it gave me an error that does not contain the necessary file taxo.k2d
> 
> I reinstalled the database several time but still got the same error. I have no idea what's wrong with it.
> 
> your help is appreciated

问题解决了吗？我的也出现这种情况了，明明那个文件在那里
