### ISSUE TITLE
Gzip Error with Kraken2 database build

### ISSUE THREAD

**Issue by cm0109** [DerrickWood/kraken2#515]
Getting the following error when trying to build standard or custom Kraken2 databases. 
```
kraken2-build --download-taxonomy --db k2db_2021 --use-ftp
Downloading nucleotide gb accession to taxon map... done.
Downloading nucleotide wgs accession to taxon map... done.
Downloaded accession to taxon map(s)
Downloading taxonomy tree data... done.
Uncompressing taxonomy data...
gzip: nucl_gb.accession2taxid.gz: invalid compressed data--format violated
```
Seems like the downloads are somehow corrupted, and gzip cannot unzip them.  I am on Kraken version 2.1.2 (installed via bioconda). Same error when trying `kraken2-build --standard --db k2db_2021 --use-ftp`. 
I have tried with and without --ftp (without gives me rsync error). 

Any help would be much appreciated, thanks!

**Comment by fingoff** [comment]
Hi, having made these changes when I run : $ kraken-build --standard --db db_standard I still get the same error.
