### ISSUE TITLE
rsync_from_ncbi.pl: unexpected FTP path (new server?)

### ISSUE THREAD

**Issue by biolougy** [DerrickWood/kraken2#516]
Hello

I am using version 2.1.1 which seemed to have resolved this problem and worked a week ago. Due to an error on my part I am now rebuilding the kraken database and receiving this error message. 

rsync_from_ncbi.pl: unexpected FTP path (new server?)

I am trying to download bacteria, fungi, archaea, protozoa and UniVec-Core libraries using

kraken2-build --download-library bacteria --db <mydb>

but only UniVec_Core is downloading any sequences.

In addition, in the past one of my main bacteria of interest has been listed in the assembly_summary file, but not in the library.fna.

Any help is much appreciated.

**Comment by JiaoBingke** [comment]
I used version 2.1.2 and also encountered the FTP error. I changed the  rsync_from_ncbi.pl script as described in https://github.com/DerrickWood/kraken2/issues/226#issuecomment-942104929 and it worked.

**Comment by biolougy** [comment]
I have seen this solution, but I don't know where to change the script. I am using kraken2 as a module on an hpc

**Comment by biolougy** [comment]
Thanks. Now sorted by my admin.
