### ISSUE TITLE
Missing taxo.k2d with nr database

### ISSUE THREAD

**Issue by Ahmed-Shibl** [DerrickWood/kraken2#528]
Hello,

I tried to download and build the nr database using the below command:

`kraken2-build --protein --download-library nr --db nr --threads 60`

This is the output I got: 

```
Downloading nr database from server... done.
Uncompressing nr database...done.
Parsing nr FASTA file...done.
Masking low-complexity regions of downloaded library... done.
(kraken2) [aduae371-lap:~/miniconda3/envs/kraken2]$
```

When I tried running the classification command:
`kraken2 --db ~/miniconda3/envs/kraken2/nr --paired --classified-out F3_nr_cseqs#.fq ~/EP_metagenomes/F3_R1_trimmed.fastq.gz ~/EP_metagenomes/F3_R2_trimmed.fastq.gz --report ~/miniconda3/envs/kraken2/Epulos/F3_nr_report.txt --output ~/miniconda3/envs/kraken2/Epulos/F3_nr_output.txt --threads 60`

I got the error that taxo.k2d cannot be found:

`kraken2: database ("~/miniconda3/envs/kraken2/nr") does not contain necessary file taxo.k2d`

Any ideas on how to get the nr database working without having to go through the download again? (took ~16 hours)

Thanks!

**Comment by jenniferlu717** [comment]
Please download the taxonomy first before building:

`kraken2-build --download-taxonomy --db nr`

**Comment by Ahmed-Shibl** [comment]
Thanks @jenniferlu717 , so I now I did the following:
1)first step:
`kraken2-build --download-taxonomy --db nr
`
2)second step
`kraken2-build --protein --download-library nr --db nr --threads 60`

I have `/taxonomy` and `/library `directories but the command `kraken2-inspect --db ~/miniconda3/envs/kraken2/nr | head -5` gives me the same error: 

`kraken2: database ("~/miniconda3/envs/kraken2/nr") does not contain necessary file taxo.k2d`
