### ISSUE TITLE
--confidence option sometimes does not work

### ISSUE THREAD

**Issue by withered-leaf** [DerrickWood/kraken2#53]
Hi:
I found some outputs that should not appeared in the kraken2 file with the option --confidence.
My kraken2 database was built as "kraken2-build --download-library bacteria --db $DBNAME".
My code just like this: 
kraken2 --db $DB --threads=24 --gzip-compressed --confidence 0.1 --report $OUT/$name/${name}.report $IN/$file > $OUT/$name/${name}.kraken2
However, there are many rows like following in the [name].kraken2 file:
C       A00159:188:H5MTCDSXX:1:1239:30517:26569 1365647 150     0:37 1:27 2:5 1365647:5 0:42
C       A00159:188:H5MTCDSXX:1:1414:6099:6261   1365647 150     0:36 1:27 2:5 1365647:5 0:43
C       A00159:188:H5MTCDSXX:1:1424:4408:20055  1365647 150     0:50 9606:5 0:25 28384:5 1:25 2:5 1365647:1
The fraction C/Q=5/(37+27+5+5+42)=5/116=0.043.  This number is less than my cutoff 0.1.  So,these sequences should be defined as Unclassified. 
I found this situation mostly happen with the sequence classified to taxonmy id 1365647.  Does this number affect the parameters? 
How to deal with this problem?

**Comment by jenniferlu717** [comment]
I think the confidence score itself does not take into account the kmers that are unclassified, but rather just considers the one that are to make sure their tree is appropriately scored. I'll talk to Derrick about changing this however.

**Comment by withered-leaf** [comment]
> I think the confidence score itself does not take into account the kmers that are unclassified, but rather just considers the one that are to make sure their tree is appropriately scored. I'll talk to Derrick about changing this however.

thanks for your reply.
In fact, the confidence score indeed count the kmers that are unclassifed, at least in most cases. This is why I said this confidence option SOMETIMES does not work. 
For example, there are also many rows in my kraken2 file like following:
U       A00164:202:HCTKJDMXX:1:1127:8730:29011  0       150     9606:5 0:111
U       A00164:202:HCTKJDMXX:1:1131:18909:2895  0       150     0:14 367110:5 0:3 9606:5 0:89
The score C/Q < my threshold 0.1， so they are defined as Unclassified correctly. 

In fact, Kraken's operating manual in the official website has described the usage of this option. It will take the kmers unclassified into account in theory. 
So, it's so weird for what I found as mentioned previously.
I just want to know how it happened.

**Comment by DerrickWood** [comment]
This should be fixed as of https://github.com/DerrickWood/kraken2/commit/fb4522ca415525e4c0f3096e4f35bcad0adae3e5 . I have run a few tests on it and seen a slight improvement in PPV when using the confidence scoring. @withered-leaf please let me know if the changes in that commit resolve the problem for you, and thanks for bringing this issue to my attention.

**Comment by withered-leaf** [comment]
The latest fix indeed solved my problem!
I have run the same code again and the issues that mentioned before was disappeared. 
Thank you very much for your job! @DerrickWood .
I'm appreciated that this software did great help to me.
