### ISSUE TITLE
Adding new genomes to a preexisting db

### ISSUE THREAD

**Issue by valentinavan** [DerrickWood/kraken2#538]
Hi, can someone please check if these following steps are correct?

I am trying to add to my plants kraken2 db ("plant_original") few taxa genomes that I have downloaded from the NCBI website (alnus_glutinosa_GCA_003254965.1.fna, carpinus_fangiana_GCA_006937295.1.fna etc..).

```
for file in *.fna   
    do
        kraken2-build --add-to-library $file --db PATH/kraken/plant_original
    done    
```
Masking low-complexity regions of new file... done. Added "alnus_glutinosa_GCA_003254965.1.fna" to library (PATH/kraken/plant_original)
Masking low-complexity regions of new file... done.
Added "carpinus_fangiana_GCA_006937295.1.fna" to library (PATH/kraken/plant_original)
Masking low-complexity regions of new file... done.

`kraken2-build --build --db ~/kraken/plant_original`

Creating sequence ID to taxonomy ID map (step 1)...
Sequence ID to taxonomy ID map already present, skipping map creation.
Estimating required capacity (step 2)...
Estimated hash table requirement: 73390180936 bytes Capacity estimation complete. [1h53m11.000s]
Building database files (step 3)... Hash table already present, skipping database file build. Database construction complete. [Total: 1h53m11.000s]

Then, I run kraken with one of my sample against this new updated plants db (I did not change the name of the db, is still called plant_original):

`kraken2 --db PATH/kraken/plant_original --threads 8 --confidence 0.1 --report PATH/SB0new_report.txt PATH/SB0.fastq.gz --report-zero-counts --output PATH/SB0new_taxa.txt
`

The new kraken2 report is exactly the same as the old one and it did not find any hit to these new added taxa.

Previously, I did a blastn alignment of these sample’s reads with these exact same taxa (I created a small db with alnus_glutinosa_GCA_003254965.1.fna, carpinus_fangiana_GCA_006937295.1.fna etc..) and blastn could find some hits. So I was expecting that Kraken2 would have found these matches too.

Are these steps wrong or am I making some conceptual mistake?

I appreciate your help.

Thanks

**Comment by valentinavan** [comment]
Fixed. 

I figured out that I cannot add taxa to a pre-build Kraken2 database (like plant, nt, bacteria etc) . 
I thus created a new database, only containing the taxa I wanted.

**Comment by freixas84** [comment]
> Fixed.
> 
> I figured out that I cannot add taxa to a pre-build Kraken2 database (like plant, nt, bacteria etc) . I thus created a new database, only containing the taxa I wanted.

Thanks, I was about to ask the same thing. Quick question, do you if I can add taxa to the new database you created using add-to-library function?

**Comment by valentinavan** [comment]
Hi, 

I have not tried this because I got stuck and could not create a custom database. See this post: https://github.com/DerrickWood/kraken2/issues/542
Let me know how you go.
