### ISSUE TITLE
taxo.k2d missing after standard database building

### ISSUE THREAD

**Issue by Beuret** [DerrickWood/kraken2#54]

**Comment by Beuret** [comment]
Dear Derrick,

I just installed kranken2 on LinuxMint and after building "the standard database" and trying to run an analysis i got the message that the taxo.2dk is missing (actually all three 2dk files), how to solve that issue?

Cheers
Christian

**Comment by DerrickWood** [comment]
It sounds like the build of the standard database didn't complete successfully. What output did you see from the `kraken2-build --standard` command? Also, if you use the command `ls -l $DBNAME` (replacing `$DBNAME` with your database directory name), what output is shown there?

**Comment by sankadinesh** [comment]
Hii there
I am also getting same error 
I have re-downloaded the databases using kraken2-build --standard 

Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 281 projects (424 sequences, 713.49 Mbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library... done.
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 12506 projects (26482 sequences, 49.92 Gbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library... done.
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 7954 projects (10229 sequences, 265.30 Mbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library... done.
rsync: failed to connect to ftp.ncbi.nlm.nih.gov (130.14.250.13): Connection refused (111)
rsync: failed to connect to ftp.ncbi.nlm.nih.gov (2607:f220:41e:250::7): Network is unreachable (101)
rsync error: error in socket IO (code 10) at clientserver.c(128) [Receiver=3.1.0]
Error downloading assembly summary file for human, exiting.
krishnan@elogin05:~/KIRK> /home/NCAOR/krishnan/KIRK/kraken2-build --standard  --threads 12 --db KRKDB
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 281 projects (424 sequences, 713.49 Mbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library... done.
rsync: failed to connect to ftp.ncbi.nlm.nih.gov (130.14.250.13): Connection refused (111)
rsync: failed to connect to ftp.ncbi.nlm.nih.gov (2607:f220:41e:250::11): Network is unreachable (101)
rsync error: error in socket IO (code 10) at clientserver.c(128) [Receiver=3.1.0]
Error downloading assembly summary file for bacteria, exiting.
krishnan@elogin05:~/KIRK> /home/NCAOR/krishnan/KIRK/kraken2-build --standard  --threads 24 --db KRKDB
rsync: failed to connect to ftp.ncbi.nlm.nih.gov (130.14.250.13): Connection refused (111)
rsync: failed to connect to ftp.ncbi.nlm.nih.gov (2607:f220:41e:250::11): Network is unreachable (101)
rsync error: error in socket IO (code 10) at clientserver.c(128) [Receiver=3.1.0]
Error downloading assembly summary file for archaea, exiting.
krishnan@elogin05:~/KIRK> /home/NCAOR/krishnan/KIRK/kraken2-build --standard  --threads 24 --db KRKDB
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 281 projects (424 sequences, 713.49 Mbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library... done.
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 12506 projects (26482 sequences, 49.92 Gbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library... done.
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 7954 projects (10229 sequences, 265.30 Mbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library... done.
mv: replace 'assembly_summary.txt', overriding mode 0440 (r--r-----)? 
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 1 project (594 sequences, 3.26 Gbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Downloading UniVec_Core data from FTP...ERROR: The remote path must start with a module name not a /
rsync error: error starting client-server protocol (code 5) at main.c(1650) [Receiver=3.1.0]

After completion I tried to run a analysis I got error 
**kraken2: database (pathname) does not contain necessary file taxo.k2d**
**ls -l** of the db shows **only library and taxonomy files**

**Comment by Beuret** [comment]
Dear Derrick,
Everything fine withing the protocol till the last line:
Downloaded taxonomy tree data
Uncompressing taxonomy data... done.
Untarring taxonomy tree data... done.
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 281 projects (424 sequences, 713.49 Mbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library...done.
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 12506 projects (26482 sequences, 49.92 Gbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library...done.
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 7954 projects (10229 sequences, 265.30 Mbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library...done.
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 1 project (594 sequences, 3.26 Gbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Downloading UniVec_Core data from FTP...done.
Adding taxonomy ID of 28384 to all sequences...done.
Masking low-complexity regions of downloaded library...done.
Creating sequence ID to taxonomy ID map (step 1)...
Sequence ID to taxonomy ID map complete. [0.212s]
Estimating required capacity (step 2)...
/usr/bin/KRAKEN2/build_kraken2_db.sh: line 98: estimate_capacity: command not found
xargs: cat: terminated by signal 13

**Comment by Beuret** [comment]
and 

ls_bio@HP-Z820-Workstation /mnt/nfs/bio/db/Kraken $ ls -l Standard051018
total 1616
drwxr-xr-x 7 nobody 4294967294      77 Oct  5 11:27 library
-rw-r--r-- 1 nobody 4294967294 1648567 Oct  5 11:27 seqid2taxid.map
drwxr-xr-x 2 nobody 4294967294    4096 Oct  5 11:27 taxonomy
ls_bio@HP-Z820-Workstation /mnt/nfs/bio/db/Kraken $

**Comment by Beuret** [comment]
and

I change nothing and i re-build the standard database....and it worked!

**Comment by DerrickWood** [comment]
@Beuret I'm a little surprised by the error in your first set of output - that seems to indicate that something got moved and so the `estimate_capacity` program wasn't found. But if you've managed to now get it working, perhaps some setting on your system was changed.

It's important to note that if the database build has a failure message at the end (e.g., `xargs: cat: terminated by signal 13`, `rsync error: error starting client-server protocol (code 5) at main.c(1650) [Receiver=3.1.0]`), then the build likely failed and something will need to be done to fix that. It could be a system or network configuration error, depending on what the error message is.

@sankadinesh Your error appears to be related to the UniVec_Core download, which should have been fixed as of the https://github.com/DerrickWood/kraken2/commit/bc14b1318f44359d6aa0a0b6e014bbe91a3a8fcc commit.

**Comment by agofton** [comment]
Hi Derrick,

The same error as @Beuret is also happening on my linux machine - everything works fine until build_db, and it exits with error: `xargs: cat: terminated by signal 13`

original command was: `kraken2-build --standard --db home/k2/k2-std-db --threads 20`

Cheers,

**Comment by agofton** [comment]
Hi Derrick,

A simila error as @Beuret is also happening on my linux machine - everything works fine until build_db.
`$ kraken2-build --standard --db home/k2/k2-std-db --threads 20`
`Downloading taxonomy tree data... done.`
`Uncompressing taxonomy data... done.`
`Untarring taxonomy tree data... done.`
`Step 1/2: Performing rsync file transfer of requested files`
`Rsync file transfer complete.`
`Step 2/2: Assigning taxonomic IDs to sequences`
`All files processed, cleaning up extra sequence files... done, library complete.`
`Masking low-complexity regions of downloaded library... done.`
`Step 1/2: Performing rsync file transfer of requested files`
`Rsync file transfer complete.`
`Step 2/2: Assigning taxonomic IDs to sequences`
`All files processed, cleaning up extra sequence files... done, library complete.`
`Masking low-complexity regions of downloaded library... done.`
`Step 1/2: Performing rsync file transfer of requested files`
`Rsync file transfer complete.`
`Step 2/2: Assigning taxonomic IDs to sequences`
`All files processed, cleaning up extra sequence files... done, library complete.`
`Masking low-complexity regions of downloaded library... done.`
`Step 1/2: Performing rsync file transfer of requested files`
`Rsync file transfer complete.`
`Step 2/2: Assigning taxonomic IDs to sequences`
`All files processed, cleaning up extra sequence files... done, library complete.`
`Downloading UniVec_Core data from server... done.`
`Adding taxonomy ID of 28384 to all sequences... done.`
`Masking low-complexity regions of downloaded library... done.`
`Creating sequence ID to taxonomy ID map (step 1)...`
`Sequence ID to taxonomy ID map complete. [0.104s]`
`Estimating required capacity (step 2)...`
`Estimated hash table requirement: 34776748616 bytes`
`Capacity estimation complete. [8m19.431s]`
`Building database files (step 3)...`
`build_db: OMP only wants you to use 1 threads`
`xargs: cat: terminated by signal 13`

`$ l kraken2-std-db/`
`total 1636`
`drwxr-sr-x  4 gof005 736436    4096 Oct 17 15:14 ./`
`drwxrwsr-x 14 root   736436    4096 Oct 17 10:57 ../`
`drwxr-sr-x  7 gof005 736436    4096 Oct 17 15:14 library/`
`-rw-r--r--  1 gof005 736436 1658311 Oct 17 15:14 seqid2taxid.map`
`drwxr-sr-x  2 gof005 736436    4096 Oct 17 15:14 taxonomy/`

Cheers,

**Comment by sarjopp** [comment]
Like Beurat, I did the DB build, got the "taxo.k2d not found" error. Inspired by Beurat, I re-ran the build command to the same target destination, and this time I got the 3 *.k2d files. Why???

**Comment by MChiaraC** [comment]
I am experiencing the same error, did anybody manage to fix it?

**Comment by darwinbandoy** [comment]
I am experiencing the same issue with kraken 2.

I ran a batch file of 8 genomes and it was ok for the first three, however for the rest I got an error message **database does not contain necessary file taxo.k2d.** 

I am sure it must be there as the first three genomes were appropriately identified- but I get error message after kraken rans into fourth genome onwards.

**Comment by msnyderman** [comment]
I did:
kraken2-build --standard --threads 24 --db download-taxonomy
and that appeared to work as I got the message:
Database construction complete. [Total: 43m39.729s]

I don't think I was able to "clean" successfully.

I have been trying use Kraken and get the error message:
kraken2: database ("/home/mcs/refs/kraken2/standard") does not contain necessary file taxo.k2d

Is there any remedy for this?
Thank you
Michael Snyderman

**Comment by AndreaClausenLind** [comment]
I have the same problem, but for building a custom database. I don't get any errors upon running kraken2-build and listing the contents of my database directory I do have a visible taxo.k2d file there. However I still get the same error as others mentioned above. Do you have any I de of how this can be solved? I tried to re-run the command but it did not help.

After adding a taxonomy directory and building a library for genomes of interest in the database directory destination, I ran:
kraken2-build --threads 20 --build --db $KRAKENDBPATH/DB_1

I get the error:
kraken2: database ('$KRAKENDBPATH/DB_1') does not contain necessary file taxo.k2d

**Comment by pe-se** [comment]
Hi, I have a similar error - 
after compiling the library, i have these files/directories (ls -l krakendb2): 
library
seqid2taxid.map
taxonomy

then I ran
kraken2-build --build --threads 32 --db krakendb2

but got there:
Found 19101/19101 targets, searched through 634710872 accession IDs, search complete.
build_db: OMP only wants you to use 1 threads
xargs: cat: terminated by signal 13

and 
kraken2-inspect --db krakendb2 | head -10
 gives me 
kraken2-inspect: database ("./krakendb2") does not contain necessary file taxo.k2d

Any help on this please?
Thank you!

**Comment by msnyderman** [comment]
?Hi

I was in over my head and gave up.

I am looking for virus in cancer so I built my own reference cancer database and am using BWA and Kallisto.  Apparently Kallisto is good for more tasks like working with human genes.

Michael Snyderman


________________________________

**Comment by jenniferlu717** [comment]
@msnyderman Did you run `kraken2-build --download-taxonomy --db DB` before building the standard database?

@pe-se It seems like your system does not have more than 1 thread and so you cannot use the `--threads 32` option.

If you continue to have problems, please create a new issue.

**Comment by unalibun** [comment]
Hi, 
I am experiencing the same error in two different servers, I tried changing the https: in the rsync files, and I followed all the recommendations but still not working. Any Solution? Best
