### ISSUE TITLE
Error in downloading taxonomy 

### ISSUE THREAD

**Issue by mars188** [DerrickWood/kraken2#540]
Hello, 

I tried to download the taxonomy and archaea library with the following code:

`kraken2-build --download-taxonomy --db db_archaea`
But get the following error:
`rsync error: error in rsync protocol data stream (code 12) at io.c(764) [receiver=3.0.9]`
`rsync: connection unexpectedly closed (47 bytes received so far) [generator]`

And for archaea library:

`kraken2-build --download-library archaea --db db_archaea/`

`rsync: read error: Connection timed out (110)
rsync error: error in rsync protocol data stream (code 12) at io.c(764) [receiver=3.0.9]
rsync: connection unexpectedly closed (39 bytes received so far) [generator]
`

It worked fine couple of months ago but now I get this error. Please help!

**Comment by ap1438** [comment]
Try with  --use-ftp flag at the end of the command.

**Comment by mars188** [comment]
Ok it worked fine with taxonomy download. Thank you so much

But when I try to download the library I get the following error. 

`kraken2-build --download-library archaea --db db_archaea/`

`rsync_from_ncbi.pl: unexpected FTP path (new server?) for https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/762/265/GCF_000762265.1_ASM76226v1`

Any thoughts on it, please?

**Comment by mars188** [comment]
Ok, I just tried it another day and it just worked for me. I think it may be some ftp issue with NCBI.

Many thanks and cheers!
