### ISSUE TITLE
Kraken error Combine and Shuffle command not found 

### ISSUE THREAD

**Issue by mathavanpu** [DerrickWood/kraken2#554]
While I running metawrap Kraken, I got these following error message 
I followed this workflow from the link mentioned below
https://github.com/bxlab/metaWRAP/blob/master/Usage_tutorial.md
Step 3: Run Kraken module on both reads and the assembly
(metawrap_prokka) [suresh@node4 metawrap_binning]$ metawrap kraken -o KRAKEN -t 96 -s 1000000 Kat-B_1.fastq Kat-B_2.fastq
metawrap kraken -o KRAKEN -t 96 -s 1000000 Kat-B_1.fastq Kat-B_2.fastq

#########################################################################################################
                                       RUNNING KRAKEN ON ALL FILES                                         
##########################################################################################################
------------------------------------------------------------------------------------------------------------------------
            Now processing Kat-B_1.fastq and Kat-B_2.fastq with 96 threads          
------------------------------------------------------------------------------------------------------------------------
                                  subsampling down to 1000000 reads...                                     
------------------------------------------------------------------------------------------------------------------------

**/apps_940/miniconda/envs/metawrap_prokka/bin/metawrap-modules/kraken.sh: line 123:  #combine: command not found**
**/apps_940/miniconda/envs/metawrap_prokka/bin/metawrap-modules/kraken.sh: line 124:  #shuffle: command not found**

**Comment by jenniferlu717** [comment]
this seems to be a metawrap issue and not a kraken issue? We are not involved in the metawrap scripts
