### ISSUE TITLE
How to continue downloading with kraken2-build download-library after terminal was accidentaly closed?

### ISSUE THREAD

**Issue by freixas84** [DerrickWood/kraken2#556]
I don't want to download again all downloaded libraries so is there a way to continue downloading remaining libraries?

**Comment by Nana7m1** [comment]
I have no idea with your issue.
But I have another way to prevent this situation.
You can try to use '**screen**', create an new terminal and start your download.
Then detach this terminal, download can be continued even if your terminal was closed.

I hope this method can help you, have a good day.
