### ISSUE TITLE
Issues with database not containing the taxo.k2d file 

### ISSUE THREAD

**Issue by AngryBotanist** [DerrickWood/kraken2#563]
So I've redownloaded the database multiple times, made sure to download the taxonomy first before downloading the database, but I continue to get the same issue. I'm not sure if this is an issue with the fix I used for the NCBI issue, but I'm not sure what to do now. Below is the code I used and the error message that popped up. 

(Kraken) [AB-Kraken2]$ kraken2-build --download-taxonomy --db Try1
Downloading nucleotide gb accession to taxon map... done.
Downloading nucleotide wgs accession to taxon map... done.
Downloaded accession to taxon map(s)
Downloading taxonomy tree data... done.
Uncompressing taxonomy data... done.
Untarring taxonomy tree data... done.
(Kraken) [AB-Kraken2]$ kraken2-build --download-library bacteria --db Try1
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 29372 projects (69219 sequences, 122.27 Gbp)... done.[B^[[B
All files processed, cleaning up extra sequence files... done, library complete.
                
Masking low-complexity regions of downloaded library... done.
(Kraken) [AB- Kraken2]$ kraken2 --paired --classified-out cseqs#.fq G822-KH01_1D_MW_S14_R1_001.fastq G822-KH01_1D_MW_S14_R2_001.fastq --db Try1
kraken2: database ("/storage/home/mga55/scratch/Kraken2/Try1") does not contain necessary file taxo.k2d

Any advice or ideas that anyone has would be incredibly helpful, thanks!

**Comment by omrctnr** [comment]
Hello, how did you fix it?

 Could you please share it with me?
