### ISSUE TITLE
Kraken2 bacteria library masking warnings

### ISSUE THREAD

**Issue by Lamm-a** [DerrickWood/kraken2#564]
I am trying to build the bacteria database using the following:

`perl /home/people/robmur/robmur/programmes/kraken2/kraken2-build --download-library bacteria --db /home/people/robmur/robmur/programmes/kraken2/db -t 40`

and I am getting this in my `STDERR`:

```
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library...FASTA-Reader: Start of first data line in seq is about 100% ambiguous nucleotides (shouldn't be over 40%)
FASTA-Reader: Start of first data line in seq is about 100% ambiguous nucleotides (shouldn't be over 40%)
FASTA-Reader: Start of first data line in seq is about 100% ambiguous nucleotides (shouldn't be over 40%)
FASTA-Reader: Start of first data line in seq is about 100% ambiguous nucleotides (shouldn't be over 40%)
```

It seems everything runs fine until the softmasking stage. Is this warning expected or am i doing something wrong?

Also, the database located [here](https://benlangmead.github.io/aws-indexes/k2). Can we just download the straight to out pc and avoid the `kraken build` process?

**Comment by jenniferlu717** [comment]
@sanderdebacker has answered this issue so I will close this for now.
