### ISSUE TITLE
Bracken vs Kraken

### ISSUE THREAD

**Issue by tuttigiuperterra** [DerrickWood/kraken2#566]
Hi!
I've used kraken on a fastq resulted from a metagenomic sequencing to classify the content of the sample.
The report output I got is a table with:
1)Percentage of fragments covered by the clade rooted at this taxon
2)Number of fragments covered by the clade rooted at this taxon
3)Number of fragments assigned directly to this taxon
4)A rank code
5)NCBI taxonomic ID number
6)Indented scientific name

but than I've found Bracken and its description says "Bracken is a highly accurate statistical method that computes the abundance of species in DNA sequences from a metagenomics sample. Kraken classifies reads to the best matching location in the taxonomic tree, but does not estimate abundances of species"
But In the report of Kraken I have the abundance of the species in the first column.

I don't get if I should refer to the abundance in the bracken output file or in the first column of the Kraken report file? Doesn't they represent the same thing?

Thank you for your help

**Comment by xu-j1234566** [comment]
I have the same problem. Do you solve it?

**Comment by jenniferlu717** [comment]
@tuttigiuperterra @xu-j1234566 

Broadly, Kraken is a classification tool while Bracken is abundance estimation. This means that Kraken gives you the most specific taxonomic assignment it can. 

For example, if 10 reads are found in two different Bacillus species (like Bacillus anthracis and Bacillus cereus), then Kraken will assign them to the Bacillus genus, but will not give you a species assignment.

50%        10         10               G             1386            Bacillus
0%           0            0               S              1392            Bacillus anthracis 
0%           0            0               S              1396            Bacillus cereus  

 
Bracken then is a post-processing script for Kraken, which will take any reads assigned further up the taxonomy from the species level and some statistical bayesian information to redistribute the reads to give reads per species. 

I hope this makes sense.
