### ISSUE TITLE
what(): 'database_1917': File truncated

### ISSUE THREAD

**Issue by jhcuarta** [DerrickWood/kraken2#569]
Hi
I'm having the following issue using kraken

terminate called after throwing an instance of 'jellyfish::compacted_hash::ErrorReading'
what(): 'database_1917': File truncated
/home/jason/Documents/kraken-master/build_kraken_db.sh: line 96: 1497144 Aborted (core dumped) jellyfish merge -o database.jdb.tmp database_*

Although I modified build_kraken_db.sh script line 82, by adding an -s 10000000 tag to overcome line's 87 mv error: argument list too long
jellyfish count -m $KRAKEN_KMER_LEN -s $KRAKEN_HASH_SIZE -C -t $KRAKEN_THREAD_CT
-o database /dev/fd/0 -s 10000000

https://github.com/DerrickWood/kraken/issues/153#issue-886325404

**Comment by jenniferlu717** [comment]
This is a kraken1 issue and unfortunately, we no longer support kraken 1. Kraken2 does not use jellyfish for kmer counting. 

This could be an issue caused by updates in jellyfish that we did not account for in the kraken code as we stopped updating kraken 1.
