### ISSUE TITLE
kraken2-build - db name unbound variable

### ISSUE THREAD

**Issue by jacodela** [DerrickWood/kraken2#57]
Hello,

I'm using `kraken2  2.0.7_beta pl526h2d50403_0 bioconda`. When I try to download the NCBI taxonomy:

```
kraken2-build --download-taxonomy --db /tmp/global2/jdelacuesta/K2_progenomes/Kraken
```
 I get the following error

```
/ebio/abt3_projects/software/miniconda3_gt4.4/envs/metacompass/libexec/download_taxonomy.sh: line 13: KRAKEN_DB_NAME: unbound variable
```

This happens regardless of whether I use absolute or relative paths with  `--db`. This also happens when I run `kraken2-build --add-to-library`

**Comment by jacodela** [comment]
An update

I followed the instructions to set [environmental variables](http://ccb.jhu.edu/software/kraken/MANUAL.html#kraken-2-environment-variables), yet none worked. I had to declare the following variable to make the download taxonomy command work

`export KRAKEN_DB_NAME="/tmp/global2/jdelacuesta/K2_progenomes/Kraken"`

However, when I try to run  

`bash -c "source activate metacompass; kraken2-build --add-to-library /tmp/global2/jdelacuesta/K2_progenomes/added_genomes/V11_RL001.fna --db /tmp/global2/jdelacuesta/K2_progenomes/Kraken`

it shows the following error

`Use of uninitialized value $ENV{"KRAKEN_DIR"} in concatenation (.) or string at /ebio/abt3_projects/software/miniconda3_gt4.4/envs/metacompass/libexec/scan_fasta_file.pl line 22.`

I have to declare the following to make the add command work

`export KRAKEN_DIR="/ebio/abt3_projects/software/miniconda3_gt4.4/envs/metacompass/libexec"`.

Yet when I try to build the database 

`kraken2-build --build --threads 20 --db /tmp/global2/jdelacuesta/K2_progenomes/Kraken`

I get the following 

```
Creating sequence ID to taxonomy ID map (step 1)...
No preliminary seqid/taxid mapping files found, aborting.
```
I checked that the `DB_PATH/library/added/prelim_map.txt` file exists and it is non-empty before running the build command, but once I execute it, the file becomes empty. Likewise, the `DB_PATH/taxonomy/prelim_map.txt` and other files in the same directory are empty.

**Comment by DerrickWood** [comment]
Is it possible that you've installed Kraken 1 over a Kraken 2 installation? The variable names you're referencing aren't in the Kraken 2 source code.

**Comment by jacodela** [comment]
Indeed, I had installed `Kraken2` over a `Kraken1` install. I uninstalled both and then installed `Bracken2`, which installs `Kraken` and the problem was solved. 

Thanks!
