### ISSUE TITLE
Is there a way to make custom k2d files?  

### ISSUE THREAD

**Issue by babramso** [DerrickWood/kraken2#570]
This is more of a question than issue.  Can I produce my own k2d database files somehow as I'd like to add additional genomes to the database that do not have a NCBI taxID or the taxIDs are incorrectly ordered in the taxonomy tree.

Thanks

**Comment by watsonar** [comment]
You can make your own database with Struo2 :) https://github.com/leylabmpi/Struo2

**Comment by babramso** [comment]
Thank you!
