### ISSUE TITLE
Unclassified + root fragments vs total sum of fragments assigned to taxa

### ISSUE THREAD

**Issue by ac-simpson** [DerrickWood/kraken2#573]
Hi,
This isn't so much a bug, as a question about number of fragments in results. 

As far as I understand, when running against a nucleotide database, the number of fragments at the clade roots for 'unclassified' and 'root' (in the second results column) should roughly add up to the number of paired-end reads that passed quality filtering. And this is indeed the case: in a test I did, I had ~6 million fragments/paired end reads for one sample, ~8 million fragments/ paired end reads for the other. This fragment number is doubled when using a protein database as apparently the paired reads are counted separately, but it still adds up almost exactly.

However, when I add up the total sum of fragments assigned to taxa (the entire third column), this number is NOT the same as the total number of fragments in unclassified+root, i.e. total number of paired end reads. There are about half a million fragments missing (I checked two separate samples and found around 500,000 fragments missing from one and 800,000 fragments missing from another). Since for 'unclassified' reads the number of fragments assigned to clade root and the number of fragments assigned to taxa are identical, presumably some reads are not assigned to any taxa, but are also not counted under the 'root' row. So, what happened to those fragments? I am noticing the same kind of discrepancy when using a protein database, with differences of about 600,000 and 900,000 fragments for the same two samples (dividing in half to account for the different way in which paired-end reads are treated here).

I'd like to know, when calculating non-nested percentages for each row, A) whether unclassified+root fragments from column 2 should be considered the total number of fragments, or B) whether the sum of column 3 should be considered the total number of fragments (and where are the lost fragments?). Or, of course, C) there is some kind of fundamental misunderstanding on my part here.

If anyone has insight here I'd appreciate it.
Cheers,
Anna

**Comment by jenniferlu717** [comment]
What database are you using and what command lines? 

Also, paired end reads should be counted as 1 but you need to include the `--paired` parameter

**Comment by ac-simpson** [comment]
This ended up being a problem with the way I was parsing the results - turns out some entries that had commas in the S3 description (host information, etc), and I was saving as a csv after parsing. This caused some lines to wrap around and mess with the fragment counts. After accounting for this issue, everything adds up correctly.
