### ISSUE TITLE
Problems with Taxonomy IDs

### ISSUE THREAD

**Issue by manuelsmendoza** [DerrickWood/kraken2#575]
Hi Derrick,

I was analyzing bacteriome samples using 16S gene sequencing data and SILVA database. After obtaining the .report file I checked the taxids in the NCBI database and they don't correspond to the same taxon. For example, taxid 45409 was assigned to Lachnospiraceae by kraken2 and the same taxid resulted as Feline immunodeficiency virus at NCBI. The same for 45422 assigned to Blautia by kraken2 and to Hemitaxonus sasayamensis by NCBI. So my question is why the same taxid is assigned to different taxons? Is SILVA database using taxids different than those from NCBI??Why?
Thank you in advance!
Regards,

**Comment by nick-youngblut** [comment]
It would be helpful to provide a taxdump for silva or point to the location of a 3rd party taxdump in the Kraken2 manual downloads page: https://ccb.jhu.edu/software/kraken2/index.shtml?t=downloads

That would also warn users that taxids differ, depending on the database (e.g., Silva vs kraken2-default)

**Comment by nick-youngblut** [comment]
Also, the README.md for `16S_Silva138_20200326.tgz` states that it includes a `seqid2taxid.map` file, but that file is not in the tarball
