### ISSUE TITLE
kraken2 command not found 

### ISSUE THREAD

**Issue by adec37** [DerrickWood/kraken2#597]
Hi! I am running the following code: 

for i in /users/a/d/adecola/bin/Trimmomatic-0.39/trimmed_reads/merged_reads/*_merged.fastq
do
SAMPLE=$(echo${i} | sed "s/_merged\.fastq//")
echo ${SAMPLE}_merged.fastq

kraken2 --use-names --db /users/a/d/adecola/anaconda3/envs/kraken2/database_custom --output /users/a/d/adecola/anaconda3/kraken2/krakenoutput/${SAMPLE}_k2.out --report /users/a/d/adecola/anaconda3/envs/kraken2/report/${SAMPLE} --fastq-input

done

When I run this code I get the following error: 
/var/spool/slurm/d/job597733/slurm_script: line 26: echo/users/a/d/adecola/bin/Trimmomatic-0.39/trimmed_reads/merged_reads/AD01_R1_merged.fastq: No such file or directory
_merged.fastq
/var/spool/slurm/d/job597733/slurm_script: line 29: kraken2: command not found

I'm not sure why it says "no such file or directory" as it states the file that it found.. I'm also not sure why the kraken2 command is not found as I was previously successful in creating a custom database. Any help is appreciated! The reads I am trying to analyze are in a separate directory from my kraken2 folder.

**Comment by agalianese** [comment]
Did you add kraken2 to your path?
