### ISSUE TITLE
Is size of minimizer table equal to 8*(4)^M bytes, where M is minimizer length? If so, this is based on which database and what all genomes?

### ISSUE THREAD

**Issue by harisankarsadasivan** [DerrickWood/kraken2#60]

**Comment by harisankarsadasivan** [comment]
I know that Kraken 2 had M=31, if so, what is the actual formula as it seems unrealistic to use previous formula. I just want to know the minimizer table size

**Comment by jenniferlu717** [comment]
Some database sizes are listed in the manual and other database sizes are listed on the downloads page: http://ccb.jhu.edu/software/kraken2/index.shtml?t=downloads 

Database sizes should be based on the number of genomes, the number of unique kmers within the genome and the number of spaced seeds used to mask out parts of the minimizers/kmers. Currently (as of April 2020), the default database (default kmer/minimizer/spaced seed parameters) with Refseq bacteria, archaea, viruses, plasmids, , vectors and human yields a database size of about 45Gb currently.
