### ISSUE TITLE
restrict search to list of taxonid (i.e., Bacteria only) with Kraken?

### ISSUE THREAD

**Issue by freixas84** [DerrickWood/kraken2#608]
Hello Everyone,
I just need a faster way to fish out all bacteria reads from metagenomic WGS samples and I thought of Kraken2 and the --classified-out flag but is there a way to restrict the search to bacteria only in the NT database?
Thanks in advance!

**Comment by jenniferlu717** [comment]
You can make a bacterial only database or you can use the extract_kraken_reads.py script here: https://github.com/jenniferlu717/KrakenTools to extract out bacterial clade reads.
