### ISSUE TITLE
about kraken2 --report

### ISSUE THREAD

**Issue by jwsbio** [DerrickWood/kraken2#61]
Dear all:
Many thanks for this outstanding tool. When I tried to use kraken2, the report funciton always results in problems after classification. Sometimes, it asked me to attach database path. Sometimes, it shows unrecognized file format. Because I was used to kraken1, it is unclear what the problem --report had caused in kraken version2. No matter what I tried, I never successfully got the report file. Any suggestion?

Thanks again

**Comment by jenniferlu717** [comment]
As compared to kraken1, kraken 2 generates the report during classification. It does not work like the kraken-report command.

In other words, specify the report option when you run the classification:
`kraken2 --db $MYDB --report $MYSAMPLE.kreport2 $MYSAMPLE.fasta > $MYSAMPLE.kraken2`
