### ISSUE TITLE
Unable to build NCBI nt database 

### ISSUE THREAD

**Issue by camilagazolla** [DerrickWood/kraken2#615]
Hello,

I have been trying to build the NCBI nt database with the following:

```
$ kraken2-build --download-library nt --db kraken_nt --threads 50 --use-ftp --fast-build
Downloading nt database from server... done.
Uncompressing nt database...done.
Parsing nt FASTA file...done.
Masking low-complexity regions of downloaded library... done.
```

However, I am getting the following afterward:

`kraken2: database ("kraken_nt/") does not contain necessary file taxo.k2d
`

The requested file is, in fact, not present in the directory. However, any error messages come after the building part...

Any idea why I am unable to construct the db properly?

My system specifications are
CPU(s): 52
Available RAM: 348 GB

Thank you!  :)

**Comment by nicolo-tellini** [comment]
Hi @camilagazolla ,

did u download the taxonomy before?

`kraken2-build --download-taxonomy --db kraken_nt`

and are `--download-library nt` and `--fast-build` compatible with the same command, I first download the library:

`kraken2-build --download-library nt --threads x --db y` 

and only after I build the database 

`kraken2-build --build --db y --threads x`

`taxo.k2d` should be generated with the `--build` command and it is at the same path level of the directory library and taxonomy.

best,

Nic

**Comment by nicolo-tellini** [comment]
Hi @camilagazolla ,

I forgot, I am building the nt database right now and it is taking more than 400GB of RAM.
  `Estimated hash table requirement: 457562994100 bytes (457GB)`
is maybe a RAM limit ?

best,

Nic

**Comment by camilagazolla** [comment]
Thank you, Nic! The RAM seems to be the issue!

**Comment by ckeeling** [comment]
Hello @camilagazolla and @nicolo-tellini 

Were you successful in building this database? If so, how long did it take? So far I am about 48 h in with 502G and 32 cpus with the no-masking tag turned on.

```bash
kraken2-build --download-taxonomy --db nt-nm # Completed in 7 minutes
kraken2-build --download-library nt --no-masking --db nt-nm # Completed in 8 h with 8G and one cpu
kraken2-build --build --db nt-nm --threads 32 # Still going after 48 h
```

Did you do a fast-build?

Thanks for sharing your experiences,
Chris

**Comment by nicolo-tellini** [comment]
Hello @ckeeling ,

My steps were a bit different, I run whit default options (so I performed the masking) and I run the building with fast-build 20 threads. 
I have also to say that probably the server was a bit crowded in alternate periods. 
At the end took my around 10/11 days. 

`
Creating sequence ID to taxonomy ID map (step 1)...
Sequence ID to taxonomy ID map complete. [1h40m37.890s]
Estimating required capacity (step 2)...
Estimated hash table requirement: 457081649736 bytes
Capacity estimation complete. [7h8m19.402s]
Building database files (step 3)...
Database files completed. [226h25m13.360s]
Database construction complete. [Total: 235h14m12.544s]
`
U are welcome,

Nic

**Comment by ckeeling** [comment]
Ouch, that's a long time!

Thanks @nicolo-tellini
