### ISSUE TITLE
Can't build custom database

### ISSUE THREAD

**Issue by AleMancon** [DerrickWood/kraken2#62]
Hello.
I can't finilize my database. I downloaded taxonomy and library using:

$/kraken2-build --download-taxonomy --skip-maps --db $Bacteria

$/kraken2-build --download-library bacteria --db $Bacteria

Running --build --db $Bacteria the program returns me:

Creating sequence ID to taxonomy ID map (step 1)...
No preliminary seqid/taxid mapping files found, aborting.

The prelim_map.txt file is empty.

Has the library been created or have I to use --add-to-library? The library subdirectory contain fna.gz files: how to add them?

**Comment by AleMancon** [comment]
I fixed the problem: sequences had been downloaded, but not added to library.

**Comment by fjptwenger** [comment]
@AleMancon hi ,can you explain in detail how to solve this problem, I also encounter this problem at present

**Comment by Solenyalyl** [comment]
dear author ,how to add?
