### ISSUE TITLE
paired and unaired reads, still need to concatenate with x delimiter?

### ISSUE THREAD

**Issue by jessmewald** [DerrickWood/kraken2#625]
Hi there,

I see several closed issues where folks ask about running paired and unpaired reads together in Kraken2. I want to perform this action because I have paired reads that passed QC as well as orphaned reads from that same sample that I would like to analyze simultaneously. 

I see the responses to past issues suggest concatenating the paired reads with a delimiter (x or n) and then concatenating the delimited paired file with the orphaned reads to form a single file for input to kraken2. I wonder if this is still the case because the current manual states the following:

"Paired reads: Kraken 2 provides an enhancement over Kraken 1 in its handling of paired read data. Rather than needing to concatenate the pairs together with an N character between the reads, Kraken 2 is able to process the mates individually while still recognizing the pairing information."

If it is still the case, that the best way to analyze a file with both paired and orphaned reads in it would be to concatenate the paired reads with a delimiter, my question is: does the delimiter need to be applied between the each individual paired read and its mate as in the toy example below? And does this need to be performed on input fasta rather than fastq?

`>fastaR1xR2`
`AAAATTTTGGGGGAAACCCxAAAATTTTGGGGGAAACCC`

Thank you for any help you can offer!

**Comment by jenniferlu717** [comment]
If you are combining paired and unpaired read data, I would still concatenate with x for paired reads. I believe the change in paired reads for Kraken 2 is only applicable when working with only paired files.
