### ISSUE TITLE
Building nt database taking very long time--Database build checkpointing and resume?

### ISSUE THREAD

**Issue by ckeeling** [DerrickWood/kraken2#632]
Hello,

I have been trying to build the nt database.

```bash
kraken2-build --download-taxonomy --db nt # Took less than 10 minutes
kraken2-build --download-library nt --db nt --threads 1 # Took 3 days with 1 cpu and 8 G memory
kraken2-build --build --db nt --threads 32 # With 502 G memory, it is still going after 12 days. Based on top, it is using 88% of the memory and all 32 cpus fully.
# stdout says...
Creating sequence ID to taxonomy ID map (step 1)...
Sequence ID to taxonomy ID map complete. [12m19.314s]
Estimating required capacity (step 2)...
Estimated hash table requirement: 471345479680 bytes
Capacity estimation complete. [3h52m31.722s]
Building database files (step 3)...
```

Nothing new has been written to disk since the first day. How long should we expect before it finishes? It seems building nt and nr has created several issues: e.g. [https://github.com/DerrickWood/kraken2/issues/315](url), [https://github.com/DerrickWood/kraken2/issues/534](url), [https://github.com/DerrickWood/kraken2/issues/560](url).

Is there a possibility to have checkpointing and resume abilities? I'm running up into my wall time of 14 days. Must we use the --fast-build flag for nt and nr? If so, how long should we expect this to take? 

Thanks,

Chris

**Comment by ckeeling** [comment]
An update:
14 days ended without it finishing. I then tried the --fast-build flag, and step 3 finished successfully in just less than 23 hours with identical resources. Yea!

Perhaps a suggestion that the manual could provide some suggestions on when to use the --fast-build flag. Without this flag, would the nt build actually finish, or is there an issue when trying to build such big databases without the flag?

Cheers,
Chris

**Comment by Sabrin2020** [comment]
@jenniferlu717 same question failed due to timed-out after 15 days. What are the cons of using --fast?

**Comment by MeriamOs** [comment]
@ckeeling may I ask what your prelim_map.txt file looks like? 

I have got a segmentation issue when I download the nt library file. The library.fna file downloaded and uncompressed fine, but then in the parsing step it said that there was a segmentation fault.

**Comment by ckeeling** [comment]
Hi @MeriamOs 

In the end, KRAKEN wasn't doing what I wanted it to do for me so I have already deleted the files. However, here's what I've gleaned from my notes and scripts. When I say "within x h/day" below, that is the wall time I gave my slurm script. It may have finished significantly before that in some cases.

I downloaded the taxonomy with 1 cpu and 8Gb within 1 h:
```bash
kraken2-2.1.2/bin/kraken2-build --download-taxonomy --threads 1 --db nt-fast
```

I downloaded nt with 1 cpu and 8Gb within 6 h:
```bash
kraken2-2.1.2/bin/kraken2-build --download-library nt --db nt-fast --threads 1
```

I then built the database with 32 cpu and 502 Gb within 2 days:
```bash
kraken2-2.1.2/bin/kraken2-build --build --db nt-fast --fast-build --threads 32
```

And then ran KRAKEN with 32 cpu and 502 G within 1 day:
```bash
kraken2-2.1.2/bin/kraken2 --db nt-fast --threads 32 --use-names --report kraken.report --report-minimizer-data --unclassified-out unclassified-out.fa --classified-out classified-out.fa --output kraken.output assembly.fa
```

Hope that helps a little in your troubleshooting,

Cheers,
Chris
