### ISSUE TITLE
Host Read Filtering Efficiency

### ISSUE THREAD

**Issue by shigdon** [DerrickWood/kraken2#64]
Hello,

I am analyzing RNAseq reads from human tissue samples that were generated from libraries prepared with RNA isolation protocols aiming to acquire both microbial and human RNA.

My first aim was to split PE fastq reads into "human" and "not-human" PE read files by classifying input read pairs with a Kraken2-human database made with the following three commands:

`kraken2-build --download-taxonomy --db kraken2_human`
`kraken2-build --download-library human --db kraken2_human`
`kraken2-build --build --threads 24 --db kraken2_human`

After building this library, I used kraken2 to split the input PE-fastq reads with the `--classified-out` and `--unclassified-out` options.

The resulting split read pairs (`human_1.fq` `human_2.fq` `not.human_1.fq` `not.human_2.fq`) were output, where the "human" read pairs were much larger than the "not.human" read pairs, and I proceeded to classify the "not.human" read pairs using the **standard** kraken2 database.

I classified the "not.human" fastq read pairs from 11 samples in total. Of these 11, classification reports for 5 samples exhibited a large proportion of the "not.human" reads being classified as *Homo sapien*.

I note that low-complexity read masking was carried out during the DB build process for both the **human** and **standard** kraken2 databases.

Has this ever been encountered before, and if so is there any indication as to why/how this may have occurred?

Thank you for your time and consideration.

**Comment by rwst** [comment]
There is one piece of information missing: did you set any confidence value? The default confidence value is 0 which would (!) mean in your case that any k-mer (34 bases wide in Kraken I believe) that is classified as human will bin your read into the `classified-out` slot, so the unclassifieds should not contain any reads with such k-mers. It is possible the specialized human db differs from the one in the standard installation. A good test would be to classify the unclassifieds (from human db) not with standard db but again with human db. If you don't get the same result then the human part of the standard db differs from the human db.

**Comment by shigdon** [comment]
Thanks Ralf!

Your suggested experiment is a great idea. I tried it out and sure enough, I got zero reads classified as human when specifying the human database I used originally to filter out the human reads from the fastq inputs rather than the standard kraken2 DB.

This means that the library content is different for the human reads between the two.

I've been grappling with where to go from here. I don't want to have human read carryover into the "non.human" read bin.

 My thought is to try building the a krakenDB with the components of the kraken2 standard DB, but without using the `--standard`` flag and to pull the libraries individually by following the kraken2 **Custom Database** steps.

**Comment by rwst** [comment]
> Does this mean that a confidence value of 0 has the highest specificity?

Yes, the negatives with confidence 0 are true negatives.

> My thought is to try building the a krakenDB with the components of the kraken2 standard DB, but without using the `--standard`` flag and to pull the libraries individually by following the kraken2 **Custom Database** steps.

That is what I've come to myself, as well.

Note the human positives may be false for several reasons: conserved orthologs, lateral gene transfer (e.g. bacterium to primitive eukaryote, conserved, example 23S rRNA), repeats, and last but not least, human contamination of RefSeq genomes (used by Kraken).

**Comment by jenniferlu717** [comment]
For short reads, we use bowtie2 to align to human/filter out host reads. For long reads, we use minimap2. 

However, if you do want to use a kraken database, download/build the human database using the `--no-masking` option and it should help.
