### ISSUE TITLE
  kraken2-inspect  dump_table: unable to allocate hash table memory

### ISSUE THREAD

**Issue by Sabrin2020** [DerrickWood/kraken2#656]
Can you please help me figure out if there is a problem with my custom kraken database?

 `kraken2-inspect --db kraken.NCBI.nt | head -5`
Failed attempt to allocate 569289122376bytes;
you may not have enough free memory to load this database.
If your computer has enough RAM, perhaps reducing memory usage from
other programs could help you load this database?
dump_table: unable to allocate hash table memory

**Comment by jenniferlu717** [comment]
You do not have enough RAM to load the database. The database itself seems to be fine?
