### ISSUE TITLE
unable to install "install_kraken2.sh"

### ISSUE THREAD

**Issue by Pisto94** [DerrickWood/kraken2#667]
Greetings to everyone.

I created a virtual machine (linux mint) to install kraken2 on my windows pc. 
I gave 8 GB ram, 200GB hard disk and 4 cores.

During the installation process, I encountered an error in the following passage:
./install_kraken2.sh $KRAKEN2_DIR

I have replaced $KRAKEN2_DIR with my directory but the process is blocked with this message:

make: entering in directory «/home/users/Desktop/kraken2-2.1.2/src»
g++ -fopenmp -Wall -std=c++11 -O3 -DLINEAR_PROBING   -c -o estimate_capacity.o estimate_capacity.cc
make: g++: such file or directory not existing
make: *** [<incorporated>: estimate_capacity.o] Error 127
make: get out from directory «/home/users/Desktop/kraken2-2.1.2/src»

Is this a size problem? What i did wrong?

Thank you in advance, I am new in linux/bash

**Comment by alexlegresley** [comment]
Have you installed the GCC compiler in Linux Mint? If not, `sudo apt update && sudo apt install build-essential` should install the necessary compiler and toolchains.

**Comment by Pisto94** [comment]
Hi Alex, thank you for the response. Unfortunately the problem was not about the installation of GCC compiler but was about the RAM space available. 
In other words, it was a simple size problem and with > 30 GB it runs.
