### ISSUE TITLE
kraken2-build does not follow symlinks

### ISSUE THREAD

**Issue by wallacelab** [DerrickWood/kraken2#67]
When building a few different kraken databases, it is very useful & space-efficient to symlink the libraries instead of having to copy them each time. However, the current kraken2-build does not allow for this since the list_sequence_files() function in build_kraken2_db.sh (line 35) uses find without the -L argument to follow links.

I created a fork of build_kraken2_db.sh with the -L option added. (It's in the fork at https://github.com/wallacelab/kraken2). I assume you can just merge these, or just add the 2 characters yourself. I am not aware of any problems this would create (unless users create their own infinite loop of symlinks, but that's on their heads), so this seems like a useful feature to add to the main branch. Please add it for future releases.

Thank you.

**Comment by jenniferlu717** [comment]
I'm not sure if this is an issue still. I have been able to use symlinks (ln -s) to make different databases based on the same library files. If you still have any problems, please open a new issue.

**Comment by cdiener** [comment]
I just got hit by this. It will definitely ignore *directories* that are symlinks (the fasta files themselves can be symlinks).  

```bash
la library/
total 680K
drwxrws--- 3 o_diener dienerlab 174 Apr 24 10:33 .
drwxrws--- 3 o_diener dienerlab  51 Apr 10 23:30 ..
drwxrws--- 2 o_diener dienerlab 52K Apr 10 23:31 added
lrwxrwx--- 1 o_diener dienerlab  98 Apr 10 23:30 archaea -> /home/isilon/dienerlab/2025_medi_db/work/a0/9a439e9c57b183401d95383b036d3b/medi_db/library/archaea
lrwxrwx--- 1 o_diener dienerlab  99 Apr 10 23:30 bacteria -> /home/isilon/dienerlab/2025_medi_db/work/c1/1c92e4ddcccfddbfab970b027c809c/medi_db/library/bacteria
lrwxrwx--- 1 o_diener dienerlab  96 Apr 10 23:30 human -> /home/isilon/dienerlab/2025_medi_db/work/f0/5d7f37bdc6b5983e1f71f4d36aecfc/medi_db/library/human
lrwxrwx--- 1 o_diener dienerlab  98 Apr 10 23:30 plasmid -> /home/isilon/dienerlab/2025_medi_db/work/e5/ac5fae01f2a6a6556cbdf58a1d4588/medi_db/library/plasmid
lrwxrwx--- 1 o_diener dienerlab 102 Apr 10 23:30 UniVec_Core -> /home/isilon/dienerlab/2025_medi_db/work/57/4eef7f132c19965b577e36665e4f15/medi_db/library/UniVec_Core
lrwxrwx--- 1 o_diener dienerlab  96 Apr 10 23:30 viral -> /home/isilon/dienerlab/2025_medi_db/work/eb/00737981ce4f87dfe5908b581ea46a/medi_db/library/viral
```

Without the `-L`:

```bash
$ find library/ '(' -name '*.fna' -o -name '*.faa' ')' -print0
# [...] only the added folder (no symlink)
library/added/S90JjyKhTZ.fnalibrary/added/0c_ewUe4lC.fnalibrary/added/cFaISqWDj7.fnalibrary/added/w8D1kiemk5.fnalibrary/added/_sDT4RmpuW.fnalibrary/added/pJIgOflk7k.fnalibrary/added/TNPRDT2wG6.fna
```

With the `-L` flag:

```bash
library/viral/library.fnalibrary/UniVec_Core/library.fnalibrary/plasmid/library.fna
# [...]
library/bacteria/library.fnalibrary/archaea/library.fna
```
