### ISSUE TITLE
Not able to download bacterial library

### ISSUE THREAD

**Issue by self-Shubham** [DerrickWood/kraken2#671]
I am using the following commands
(bsc_metagenome) gmpl@GMPL:/media/gmpl/Data_Raw/MYDB$ kraken2-build --download-library bacteria --db db_bacteria
Error- 
Step 1/2: Performing rsync file transfer of requested files
rsync: [receiver] read error: Connection timed out (110)
rsync error: error in socket IO (code 10) at io.c(806) [receiver=3.2.7]
rsync: connection unexpectedly closed (6108286 bytes received so far) [generator]
rsync error: error in rsync protocol data stream (code 12) at io.c(231) [generator=3.2.7]
rsync_from_ncbi.pl: rsync error, exiting: 3072

**Comment by self-Shubham** [comment]
Hello @jenniferlu717 ma'am!!
Can you please help me to solve the above issue?

**Comment by self-Shubham** [comment]
Solved.

**Comment by derekstein** [comment]
How was this solved!!

**Comment by AzizHN** [comment]
How was that solved please!
