### ISSUE TITLE
Question about Paired reads

### ISSUE THREAD

**Issue by gc26762524** [DerrickWood/kraken2#68]
I had the paired reads analysis with length 140bp in Kraken2, but I wonder why only 106 bp reads were considered for Kmers classification such as below. Is there any way I could increase the length?

U       ST-E00600:212:HFFN7ALXX:1:1101:17164:1282       0       140|140 0:106 |:| 0:106
U       ST-E00600:212:HFFN7ALXX:1:1101:26928:1282       0       140|140 0:106 |:| 0:106
C       ST-E00600:212:HFFN7ALXX:1:1101:7193:1360        213115  140|140 28221:3 2:5 28221:2 2:7 119060:7 2:5 0:16 562:5 2:20 0:28 2:8 |:| 194924:1 2:2 194924:5 2:11 213115:6 2:1 21
3115:10 194924:21 28221:2 194924:2 2:2 28221:3 2:23 0:17
U       ST-E00600:212:HFFN7ALXX:1:1101:18747:1360       0       140|140 0:106 |:| 0:106
U       ST-E00600:212:HFFN7ALXX:1:1101:20735:1360       0       140|140 0:106 |:| 0:106
C       ST-E00600:212:HFFN7ALXX:1:1101:18041:1548       171549  140|140 171549:106 |:| 171549:106

Also, I use Bracken for abundance estimation. Should I use 106-mers or 140-mers for Kmer distribution analysis? 

Thanks a lot!
Cheng

**Comment by jenniferlu717** [comment]
140bp reads only have 106, 35mers. That is why the output file lists 106.
