### ISSUE TITLE
Question about build custom database

### ISSUE THREAD

**Issue by jingzhejiang** [DerrickWood/kraken2#69]
Hi,

I am trying to use viral protein sequences obtained from NCBI Identical Protein Groups to build custom database (IPG_viral_protein).

hyperlink of IPG_viral_protein was set as below:
ubuntu@ip-172-31-2-109:~/db/kraken2/library/IPG_viral_protein$ ll
total 12
drwxrwxr-x 3 ubuntu ubuntu 4096 Nov 26 05:59 ./
drwxrwxr-x 9 ubuntu ubuntu 4096 Nov 26 05:58 ../
drwxrwxr-x 3 ubuntu ubuntu 4096 Nov 26 05:59 library/
lrwxrwxrwx 1 ubuntu ubuntu   11 Nov 26 05:58 taxonomy -> ../taxonomy/

And I also added prot.accession2taxid (from NCBI ftp) to the taxonomy directory
When I run the script:
kraken2-build --add-to-library sequence.fasta --db IPG_viral_protein --threads 4

it is stopped at: 
scan_fasta_file.pl: unable to determine taxonomy ID for sequence 2209404D

I further checked the sequence:
>2209404D RL4 gene [Human adenovirus 41]
MVTPLLLLVCLPIIYASTTFAAVSHLDTDCLPALLTYLIFTSVCCTAICSIATFFVAIFQ
TADYLYVRVAYYRHHPQYRNHEVAALLCLS

Is that mean the taxonomy file in kraken2 can't recognize the sequence ID or the taxonomy name (Human adenovirus 41)?

How to solve this problem?
Thank you!

Ginger

**Comment by jenniferlu717** [comment]
kraken2 did not find a taxonomy ID for the seqid `2209404D`. It typically is looking in the taxonomy/*accession2taxid.map files for the seqids. 

For any seqid, if you know the taxid, you can just append `seqid taxid` to the seqid2taxid.map file (separated by a tab)
