### ISSUE TITLE
No output while waiting to load DB ?

### ISSUE THREAD

**Issue by tseemann** [DerrickWood/kraken2#7]
I managed to build the standard DB, and it worked flawlessy - nice work!
The rsync is a great addition to the process.
The DB hash file was ~32GB.

When i ran the first kraken2 test, it took about 30 seconds before it printed anything to the screen, and i wasn't sure if it was working or not (top showed classify running with 40% of 1 CPU only).

Could you have a --verbose option, or just print something to STDERR at the start?
To pacify premature CTRL-C people like me?

**Comment by DerrickWood** [comment]
Sure, that's a fair ask - I'm doing most of my test work on systems where that startup is fast enough that I've never paid attention to the lack of immediate output. STDERR message now added in https://github.com/DerrickWood/kraken2/commit/ab5fa2cd27837e361535f81fdbabbfac8fc08d62
