### ISSUE TITLE
protein and nucleotide db in same directory

### ISSUE THREAD

**Issue by tolot27** [DerrickWood/kraken2#70]
Is it save to have both protein and nucleotide database in the same directory? The individual library files  have the extension `.faa` or `.fna`. Only `prelim_map.txt` contains both accession sets.

**Comment by tolot27** [comment]
The `manifest.txt` files also differ but are only necessary for the download. Maybe, they could be renamed into `manifest_faa.txt' and `manifest_fna.txt` or something similar.

**Comment by jenniferlu717** [comment]
Given that the database files all are `taxo.k2d, hash.k2d, opts.k2d` all have the same extension, they cannot be in the same folder. You can create a symbolic link `ln -s` to reuse the files shared by the dbs.
