### ISSUE TITLE
Add Full Taxonomy to Standard Output

### ISSUE THREAD

**Issue by cazzlewazzle89** [DerrickWood/kraken2#71]
My question relates to slightly editing the standard Kraken output format. I haven't been able to find an answer in the manual or --help.

Is there a flag or utility script that I am missing that would allow me to replace the taxonomy name (third column) with its full taxonomic information, preferably in mpa format? I think it would be similar to the kraken-translate script in the original package.

I am using the following command:

`kraken2 sample_1.fastq sample_2.fastq --paired --report sample.kreport --use-mpa-style --report-zero-counts --use-names --threads 10 --db /data/shared/kraken2_db/ --output sample.kraken`

Any advice would be appreciated.
All the best,
Calum

**Comment by microbialman** [comment]
For anyone else wanting to get the full mpa style names from the standard Kraken2 output (not using report mode), I have made a quick script (translateKraken2.py) that acts similar to kraken-translate from kraken 1. 

It relies on [Taxonkit](https://github.com/shenwei356/taxonkit) and takes the standard output from Kraken2 (without use-names) and returns a tab delimited file with the full taxonomic name for each read.

Its in the scripts folder [here](https://github.com/microbialman/MetaSequencing/blob/master/scripts/translateKraken2.py)

**Comment by cazzlewazzle89** [comment]
I forgot to reply to this.
It is perfect, thank you :)
