### ISSUE TITLE
Combining paired end reads and unpaired into one file

### ISSUE THREAD

**Issue by gkarthik** [DerrickWood/kraken2#72]
Hello,

I'm trying to concatenate paired and unpaired reads into one file for Kraken to avoid reloading the database into memory. I know in kraken1 you could use 'N' to concatenate paired end reads. Is that the same for Kraken2 as well? I now about the --paired option but in interest of speed I'd prefer concatenating them into one file. Please let me know!

Thanks,
Karthik

**Comment by jenniferlu717** [comment]
I believe that kraken2 uses x instead of N. You can concatenate them using x or N, either will work and kraken2 can still classify them properly.
