### ISSUE TITLE
Could not build the fungi database

### ISSUE THREAD

**Issue by huang1997yu** [DerrickWood/kraken2#727]
When I run the following code：
DBNAME=/home/hxy/Metagenome/db/kraken/4quan
kraken2-build --download-library fungi --threads 24 --db ${DBNAME}

The following error occurs：
Step 1/2: Performing rsync file transfer of requested files
rsync: read error: Connection reset by peer (104)
rsync error: error in socket IO (code 10) at io.c(785) [receiver=3.1.3]
rsync: connection unexpectedly closed (15600 bytes received so far) [generator]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [generator=3.1.3]
rsync_from_ncbi.pl: rsync error, exiting: 3072

**Comment by huang1997yu** [comment]
But I managed to build databases of bacteria, viral, archaea, and protozoa using the same code.

**Comment by nicolo-tellini** [comment]
Hello @huang1997yu ,

did you try the option `--use-ftp` this avoid using rsync.

best,

nic

**Comment by huang1997yu** [comment]
> 你好 ，
> 
> 您是否尝试过该选项，这应该是绕过 rsync 问题的替代方法。`--use-ftp`
> 
> 最好
> 
> 网卡

This is so cool! Your suggestion solved my problem. Thank you so much!
