### ISSUE TITLE
Making a new database 

### ISSUE THREAD

**Issue by Fazizzz** [DerrickWood/kraken2#73]
Hi guys, 

I started using meta-genomic data and Kraken2 a few months ago and find myself needing to create a new database for nematodes. I was wondering if you could set me on the right path with regards to how I should go about making this new database which could work with Kraken2. I want to either make a brand new database against which I could run my meta-genomic samples against or add the nematodes I want into an existing kraken database I have. 

would I download the genome samples from NCBI 
https://www.ncbi.nlm.nih.gov/genome/350?genome_assembly_id=352931

and then put them as a file in my virtual machine and run:
  for file in chr*.fa
do
    kraken2-build --add-to-library $file --db $DBNAME
done

I would appreciate your help and any clarifications you can provide because I am still new to computation and Kraken2.

-Faizan

**Comment by jenniferlu717** [comment]
Sorry for the extremely late reply. Your initial instincts are correct. If there are specific genomes in mind, I would suggest downloading them and adding them as you describe. 

However, please note that complete genomes have the best chance of providing accurate results. Any draft genome has the probability of having contamination and therefore yielding false positives.
