### ISSUE TITLE
Kraken2 Bacteria database missing certain taxa

### ISSUE THREAD

**Issue by CompBioML** [DerrickWood/kraken2#733]
I created a custom bacterial database using the guide on github and tested it on a random set of reads from Blautia caecimuris and their were no matches. I checked out the full report and discovered its not even in its taxonomy. To double check if I made an error, I checked out the pre-made databases on https://github.com/BenLangmead/aws-indexes and found the same taxa was missing in its index. Their are multiple RefSeq sequences, so I was wondering why it wasn't present. Any help would be appreciated, thanks!

**Comment by palatinate** [comment]
`next unless grep {$asm_level eq $_} ("Complete Genome", "Chromosome");`

Only species with assembly level 'Complete Genome' or  'Chromosome' are included in the database.

**Comment by CompBioML** [comment]
> 

Yep this seems to be the solution, appreciate the help!
