### ISSUE TITLE
Kraken-build

### ISSUE THREAD

**Issue by drs357** [DerrickWood/kraken2#746]
Hello,

I downloaded the bacteria library and am trying to build the library:

 kraken2-build --build --db Bacteria

When I use the command with the downloaded library, I get the error:

Can't find taxonomy/ subdirectory in database directory, exiting.

The database is there, I do not know what the problem is. 

thanks

**Comment by utkinaira** [comment]
Hi @drs357, 

I am facing the same issue, do you mind sharing how did you solve this?
Thanks!

Irina
