### ISSUE TITLE
Fasta file Extraction from classified read by kraken2

### ISSUE THREAD

**Issue by khoriba** [DerrickWood/kraken2#75]
Hello,
I'd like to use blast to confirm classified reads by kraken2. So I need the fasta file which is extracted from kraken2 result. I could get the all unclassified reads after kraken2 analysis by using "--unclassified-out" option. But I couldn't get the fasta file classified as a specific bacterium or taxonomic group.  How can I get that?

**Comment by rwst** [comment]
My solution is to use `--use-names` and `--classified-out file1.fasta` and save the kraken output (which goes to stdout) to a second file. Then a small BioPython script processes both files and spits out a fasta file with the specific hits that can then be blasted.

**Comment by khoriba** [comment]
Thank you for your reply.
Can anyone use "a small BioPython script"?

**Comment by jenniferlu717** [comment]
I developed `extract_kraken_reads.py` https://github.com/jenniferlu717/KrakenTools for extracting/analyzing kraken classified reads.
