### ISSUE TITLE
./install_kraken2.sh: No such file or directory

### ISSUE THREAD

**Issue by hollie9** [DerrickWood/kraken2#750]
I am trying to install kraken2 but every time i use the command i just get 'No such file or directory'. Do I need to install a file from somewhere to make this command work?

**Comment by nataliaglazman** [comment]
Yes, you need to download the latest release from the Kraken2 page (link: https://github.com/DerrickWood/kraken2/releases), and extract the zip file you download. The install_kraken2.sh script is there.
