### ISSUE TITLE
standard protein database, viral seqeunces

### ISSUE THREAD

**Issue by amanzanom** [DerrickWood/kraken2#751]
in kraken 2.1.3 on a SLURM cluster I am getting the following (already thrice) when building. Looks like a specific problem when attempting to downlaod viral database. This did not happen with the nucleotide build.

Step 0/2: performing rsync dry run (only protein d/l requires this)...
Rsync dry run complete, removing any non-existent files from manifest.
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library... done.
Step 0/2: performing rsync dry run (only protein d/l requires this)...
Rsync dry run complete, removing any non-existent files from manifest.
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library... done.
Step 0/2: performing rsync dry run (only protein d/l requires this)...
Rsync dry run complete, removing any non-existent files from manifest.
Step 1/2: Performing rsync file transfer of requested files
rsync: link_stat "/all/GCF/000/848/305/GCF_000848305.1_ViralProj14662/GCF_000848305.1_ViralProj14662_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/850/605/GCF_000850605.1_ViralProj14772/GCF_000850605.1_ViralProj14772_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/856/425/GCF_000856425.1_ViralProj15000/GCF_000856425.1_ViralProj15000_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/878/955/GCF_000878955.1_ViralProj28115/GCF_000878955.1_ViralProj28115_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/881/635/GCF_000881635.1_ViralProj32241/GCF_000881635.1_ViralProj32241_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/003/032/965/GCF_003032965.1_ASM303296v1/GCF_003032965.1_ASM303296v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/899/295/GCF_000899295.1_ViralProj176433/GCF_000899295.1_ViralProj176433_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/848/145/GCF_000848145.1_ViralProj14629/GCF_000848145.1_ViralProj14629_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/018/594/885/GCF_018594885.1_ASM1859488v1/GCF_018594885.1_ASM1859488v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/843/865/GCF_000843865.1_ViralProj14433/GCF_000843865.1_ViralProj14433_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/905/367/645/GCF_905367645.1_PkV-RF01/GCF_905367645.1_PkV-RF01_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/884/515/GCF_000884515.1_ViralProj42701/GCF_000884515.1_ViralProj42701_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/895/995/GCF_000895995.1_ViralProj88123/GCF_000895995.1_ViralProj88123_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/002/833/705/GCF_002833705.1_ASM283370v1/GCF_002833705.1_ASM283370v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/850/865/GCF_000850865.1_ViralProj14826/GCF_000850865.1_ViralProj14826_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/018/594/855/GCF_018594855.1_ASM1859485v1/GCF_018594855.1_ASM1859485v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/001/441/155/GCF_001441155.1_ViralProj301300/GCF_001441155.1_ViralProj301300_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/837/585/GCF_000837585.1_ViralProj14184/GCF_000837585.1_ViralProj14184_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/892/815/GCF_000892815.1_ViralProj67961/GCF_000892815.1_ViralProj67961_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/001/689/875/GCF_001689875.1_ViralProj329637/GCF_001689875.1_ViralProj329637_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/849/805/GCF_000849805.1_ViralProj14623/GCF_000849805.1_ViralProj14623_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/018/583/075/GCF_018583075.1_ASM1858307v1/GCF_018583075.1_ASM1858307v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/852/105/GCF_000852105.1_ViralProj14784/GCF_000852105.1_ViralProj14784_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/845/885/GCF_000845885.1_ViralProj14502/GCF_000845885.1_ViralProj14502_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/002/830/445/GCF_002830445.1_ASM283044v1/GCF_002830445.1_ASM283044v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/910/735/GCF_000910735.1_ViralProj214366/GCF_000910735.1_ViralProj214366_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/003/032/945/GCF_003032945.1_ASM303294v1/GCF_003032945.1_ASM303294v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/846/085/GCF_000846085.1_ViralProj14557/GCF_000846085.1_ViralProj14557_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/002/818/015/GCF_002818015.1_ASM281801v1/GCF_002818015.1_ASM281801v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/854/585/GCF_000854585.1_ViralProj14967/GCF_000854585.1_ViralProj14967_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/023/142/015/GCF_023142015.1_ASM2314201v1/GCF_023142015.1_ASM2314201v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/839/285/GCF_000839285.1_ViralProj14194/GCF_000839285.1_ViralProj14194_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/852/865/GCF_000852865.1_ViralProj14773/GCF_000852865.1_ViralProj14773_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/001/429/975/GCF_001429975.1_ViralProj300244/GCF_001429975.1_ViralProj300244_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/839/825/GCF_000839825.1_ViralProj14126/GCF_000839825.1_ViralProj14126_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/872/525/GCF_000872525.1_ViralProj28683/GCF_000872525.1_ViralProj28683_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/002/986/195/GCF_002986195.1_ASM298619v1/GCF_002986195.1_ASM298619v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/001/271/055/GCF_001271055.1_ViralProj293051/GCF_001271055.1_ViralProj293051_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/013/087/435/GCF_013087435.1_ASM1308743v1/GCF_013087435.1_ASM1308743v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/857/145/GCF_000857145.1_ViralProj15162/GCF_000857145.1_ViralProj15162_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/018/584/775/GCF_018584775.1_ASM1858477v1/GCF_018584775.1_ASM1858477v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/002/830/425/GCF_002830425.1_ASM283042v1/GCF_002830425.1_ASM283042v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/844/685/GCF_000844685.1_ViralProj14432/GCF_000844685.1_ViralProj14432_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/926/275/GCF_000926275.1_ViralProj263035/GCF_000926275.1_ViralProj263035_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/002/830/465/GCF_002830465.1_ASM283046v1/GCF_002830465.1_ASM283046v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/881/835/GCF_000881835.1_ViralProj32817/GCF_000881835.1_ViralProj32817_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/840/265/GCF_000840265.1_ViralProj14208/GCF_000840265.1_ViralProj14208_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/839/165/GCF_000839165.1_ViralProj14170/GCF_000839165.1_ViralProj14170_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/002/986/205/GCF_002986205.1_ASM298620v1/GCF_002986205.1_ASM298620v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/852/785/GCF_000852785.1_ViralProj14757/GCF_000852785.1_ViralProj14757_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/922/435/GCF_000922435.1_ViralProj259986/GCF_000922435.1_ViralProj259986_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/002/817/355/GCF_002817355.1_ASM281735v1/GCF_002817355.1_ASM281735v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/853/885/GCF_000853885.1_ViralProj14964/GCF_000853885.1_ViralProj14964_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/924/235/GCF_000924235.1_ViralProj260752/GCF_000924235.1_ViralProj260752_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/018/547/955/GCF_018547955.1_ASM1854795v1/GCF_018547955.1_ASM1854795v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/856/305/GCF_000856305.1_ViralProj14974/GCF_000856305.1_ViralProj14974_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/003/032/935/GCF_003032935.1_ASM303293v1/GCF_003032935.1_ASM303293v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/854/625/GCF_000854625.1_ViralProj14976/GCF_000854625.1_ViralProj14976_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/899/115/GCF_000899115.1_ViralProj173051/GCF_000899115.1_ViralProj173051_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/866/945/GCF_000866945.1_ViralProj16320/GCF_000866945.1_ViralProj16320_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/841/025/GCF_000841025.1_ViralProj14201/GCF_000841025.1_ViralProj14201_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/856/285/GCF_000856285.1_ViralProj14970/GCF_000856285.1_ViralProj14970_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/883/615/GCF_000883615.1_ViralProj34737/GCF_000883615.1_ViralProj34737_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/918/435/GCF_000918435.1_ViralProj240235/GCF_000918435.1_ViralProj240235_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/846/845/GCF_000846845.1_ViralProj14525/GCF_000846845.1_ViralProj14525_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/906/555/GCF_000906555.1_ViralProj186953/GCF_000906555.1_ViralProj186953_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/003/032/975/GCF_003032975.1_ASM303297v1/GCF_003032975.1_ASM303297v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/001/430/395/GCF_001430395.1_ViralProj300245/GCF_001430395.1_ViralProj300245_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/002/824/145/GCF_002824145.1_ASM282414v1/GCF_002824145.1_ASM282414v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/023/120/325/GCF_023120325.1_ASM2312032v1/GCF_023120325.1_ASM2312032v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/003/260/955/GCF_003260955.1_ASM326095v1/GCF_003260955.1_ASM326095v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/002/988/015/GCF_002988015.1_ASM298801v1/GCF_002988015.1_ASM298801v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/002/830/485/GCF_002830485.1_ASM283048v1/GCF_002830485.1_ASM283048v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/003/032/995/GCF_003032995.1_ASM303299v1/GCF_003032995.1_ASM303299v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/857/205/GCF_000857205.1_ViralMultiSegProj15175/GCF_000857205.1_ViralMultiSegProj15175_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/894/135/GCF_000894135.1_ViralProj80873/GCF_000894135.1_ViralProj80873_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/002/818/175/GCF_002818175.1_ASM281817v1/GCF_002818175.1_ASM281817v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/866/125/GCF_000866125.1_ViralProj16312/GCF_000866125.1_ViralProj16312_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/845/525/GCF_000845525.1_ViralProj14429/GCF_000845525.1_ViralProj14429_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/852/905/GCF_000852905.1_ViralProj14782/GCF_000852905.1_ViralProj14782_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/023/147/665/GCF_023147665.1_ASM2314766v1/GCF_023147665.1_ASM2314766v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/018/594/865/GCF_018594865.1_ASM1859486v1/GCF_018594865.1_ASM1859486v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/853/905/GCF_000853905.1_ViralProj14968/GCF_000853905.1_ViralProj14968_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/001/271/215/GCF_001271215.1_ViralProj293052/GCF_001271215.1_ViralProj293052_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/003/032/895/GCF_003032895.1_ASM303289v1/GCF_003032895.1_ASM303289v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/021/461/725/GCF_021461725.1_ASM2146172v1/GCF_021461725.1_ASM2146172v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/002/830/505/GCF_002830505.1_ASM283050v1/GCF_002830505.1_ASM283050v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/893/775/GCF_000893775.1_ViralProj70005/GCF_000893775.1_ViralProj70005_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/836/845/GCF_000836845.1_ViralProj14021/GCF_000836845.1_ViralProj14021_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/013/087/265/GCF_013087265.1_ASM1308726v1/GCF_013087265.1_ASM1308726v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/002/986/165/GCF_002986165.1_ASM298616v1/GCF_002986165.1_ASM298616v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/854/565/GCF_000854565.1_ViralProj14963/GCF_000854565.1_ViralProj14963_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/900/473/875/GCF_900473875.1_DIV-1/GCF_900473875.1_DIV-1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/847/785/GCF_000847785.1_ViralProj14720/GCF_000847785.1_ViralProj14720_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/889/915/GCF_000889915.1_ViralProj48423/GCF_000889915.1_ViralProj48423_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/023/156/365/GCF_023156365.1_ASM2315636v1/GCF_023156365.1_ASM2315636v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/846/765/GCF_000846765.1_ViralProj14503/GCF_000846765.1_ViralProj14503_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/883/995/GCF_000883995.1_ViralProj38541/GCF_000883995.1_ViralProj38541_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/846/405/GCF_000846405.1_ViralProj14430/GCF_000846405.1_ViralProj14430_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/003/028/895/GCF_003028895.1_ASM302889v1/GCF_003028895.1_ASM302889v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/029/884/875/GCF_029884875.1_ASM2988487v1/GCF_029884875.1_ASM2988487v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/003/032/955/GCF_003032955.1_ASM303295v1/GCF_003032955.1_ASM303295v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/853/625/GCF_000853625.1_ViralProj14908/GCF_000853625.1_ViralProj14908_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/855/385/GCF_000855385.1_ViralProj14969/GCF_000855385.1_ViralProj14969_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/852/825/GCF_000852825.1_ViralProj14765/GCF_000852825.1_ViralProj14765_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/909/495/GCF_000909495.1_ViralProj210930/GCF_000909495.1_ViralProj210930_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/002/354/965/GCF_002354965.1_Squirrelpox_virus_strain_BerSQPV_complete_genome/GCF_002354965.1_Squirrelpox_virus_strain_BerSQPV_complete_genome_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/840/125/GCF_000840125.1_ViralProj14189/GCF_000840125.1_ViralProj14189_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/002/817/675/GCF_002817675.1_ASM281767v1/GCF_002817675.1_ASM281767v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/843/845/GCF_000843845.1_ViralProj14428/GCF_000843845.1_ViralProj14428_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/023/122/795/GCF_023122795.1_ASM2312279v1/GCF_023122795.1_ASM2312279v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/850/525/GCF_000850525.1_ViralProj14756/GCF_000850525.1_ViralProj14756_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/909/455/GCF_000909455.1_ViralProj209726/GCF_000909455.1_ViralProj209726_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/850/565/GCF_000850565.1_ViralProj14764/GCF_000850565.1_ViralProj14764_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/840/025/GCF_000840025.1_ViralProj14169/GCF_000840025.1_ViralProj14169_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/001/586/925/GCF_001586925.1_ViralProj314396/GCF_001586925.1_ViralProj314396_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/844/225/GCF_000844225.1_ViralProj14511/GCF_000844225.1_ViralProj14511_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/855/365/GCF_000855365.1_ViralProj14965/GCF_000855365.1_ViralProj14965_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/002/866/945/GCF_002866945.1_ASM286694v1/GCF_002866945.1_ASM286694v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/002/354/945/GCF_002354945.1_ViralProj400090/GCF_002354945.1_ViralProj400090_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/002/830/405/GCF_002830405.1_ASM283040v1/GCF_002830405.1_ASM283040v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/845/045/GCF_000845045.1_ViralProj14506/GCF_000845045.1_ViralProj14506_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/018/586/945/GCF_018586945.1_ASM1858694v1/GCF_018586945.1_ASM1858694v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/914/955/GCF_000914955.1_ViralProj229823/GCF_000914955.1_ViralProj229823_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/003/047/555/GCF_003047555.1_ASM304755v1/GCF_003047555.1_ASM304755v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/855/405/GCF_000855405.1_ViralProj14973/GCF_000855405.1_ViralProj14973_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/008/800/755/GCF_008800755.1_ASM880075v1/GCF_008800755.1_ASM880075v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/849/865/GCF_000849865.1_ViralProj14637/GCF_000849865.1_ViralProj14637_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/001/045/345/GCF_001045345.1_ViralProj288492/GCF_001045345.1_ViralProj288492_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/002/823/965/GCF_002823965.1_ASM282396v1/GCF_002823965.1_ASM282396v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/002/820/405/GCF_002820405.1_ASM282040v1/GCF_002820405.1_ASM282040v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/844/205/GCF_000844205.1_ViralProj14501/GCF_000844205.1_ViralProj14501_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/847/065/GCF_000847065.1_ViralProj14568/GCF_000847065.1_ViralProj14568_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/854/605/GCF_000854605.1_ViralProj14971/GCF_000854605.1_ViralProj14971_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/029/884/885/GCF_029884885.1_ASM2988488v1/GCF_029884885.1_ASM2988488v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/003/032/985/GCF_003032985.1_ASM303298v1/GCF_003032985.1_ASM303298v1_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/856/265/GCF_000856265.1_ViralProj14966/GCF_000856265.1_ViralProj14966_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/851/325/GCF_000851325.1_ViralProj14783/GCF_000851325.1_ViralProj14783_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/848/345/GCF_000848345.1_ViralProj14670/GCF_000848345.1_ViralProj14670_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/858/105/GCF_000858105.1_ViralProj15161/GCF_000858105.1_ViralProj15161_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/001/689/795/GCF_001689795.1_ViralProj328874/GCF_001689795.1_ViralProj328874_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync: link_stat "/all/GCF/000/925/215/GCF_000925215.2_ViralProj263030/GCF_000925215.2_ViralProj263030_protein.faa.gz" (in genomes) failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1670) [generator=3.1.3]
rsync_from_ncbi.pl: rsync error, exiting: 5888

**Comment by jenniferlu717** [comment]
It happens when NCBI does not update the assembly_summary.txt file when they rename/move any sequences in the ftp site. This error resolves when the file is updated. I just downloaded the standard database and it does not have this error anymore.

**Comment by AlexSartori** [comment]
Can this error be made non-blocking or bypassed somehow? I've been unable to build a database for several days now, and I'm willing to accept a number of missing sequences.
