### ISSUE TITLE
Some species missed in download database

### ISSUE THREAD

**Issue by boyanboyue** [DerrickWood/kraken2#758]
HI,
I have downloaded Standard database from [web](https://benlangmead.github.io/aws-indexes/k2) .And then I analyse a file,when I was checking the answer I find that some bacterias were missed.
I have used the `--report-zero-counts` option but still not find some species such as Mesomycoplasma hyorhinis(taxid = 2100).
Could someone tell me why?
Thank you so much.

**Comment by jenniferlu717** [comment]
What do you mean by missing bacteria? It could be that they just were not detected in your sample

**Comment by SimonHegele** [comment]
If you click on the .txt in the inspect column and search for your species you will not find it. Not sure why it is not included but it might be possible to manually add species if there are not too many of them.

**Comment by boyanboyue** [comment]
> What do you mean by missing bacteria? It could be that they just were not detected in your sample

OK,I got it ,thank you very much

**Comment by boyanboyue** [comment]
> If you click on the .txt in the inspect column and search for your species you will not find it. Not sure why it is not included but it might be possible to manually add species if there are not too many of them.
Yes,I also found the same thing,thanks a lot
