### ISSUE TITLE
nt Database question

### ISSUE THREAD

**Issue by 1023011930** [DerrickWood/kraken2#764]
Dear sir or madam, I am downloading the index from "https://benlangmead.github.io/aws-indexes/k2".
I noticed that there is a newer nt Database (400+ GB), so I am downloading "k2_nt_20230502.tar.gz", and I was wondering how to build the db with kraken2-build after downloading this file, as I understand it. In my understanding, there is no "k2_nt_20230502" option in "--download-library TYPE", only "nt".
![image](https://github.com/DerrickWood/kraken2/assets/89200805/28dd680b-7af7-42c0-8f1f-9f71eb5a1013)
I'd appreciate it if you could answer my questions.

**Comment by jenniferlu717** [comment]
If you download any index from the aws-indexes, you do not need to rebuild the database. The databases provided are already built. You can run kraken2 directly with those databases.

**Comment by 1023011930** [comment]
Thanks for your reply, unfortunately I got an EOF error when I unzipped the file again, probably because the downloaded file was incomplete.
Maybe "wget" is not a good way to download large files!
