### ISSUE TITLE
How does Kraken2 handle ambiguities

### ISSUE THREAD

**Issue by Simon602** [DerrickWood/kraken2#766]
Dear all,

I'm seeking assistance with the following question: 
How does Kraken2 handle gaps and ambiguities in the sequence? If there are ambiguities, such as R, Y, K, M, in the sequences, does Kraken2 automatically resolve them, or is manual removal necessary? 
Your insights would be greatly appreciated

**Comment by jenniferlu717** [comment]
Do you mean with protein sequences? I believe Kraken2 only takes in DNA sequences and ignores any kmers containing non DNA nucleotides (ACGT)

**Comment by Simon602** [comment]
In DNA sequences, if we encounter sequences containing ambiguous nucleotides (such as R, Y, K, M, ...), does Kraken2 automatically resolve them
Thanks for your reply
