### ISSUE TITLE
New release for confidence score bug

### ISSUE THREAD

**Issue by Takadonet** [DerrickWood/kraken2#78]
Wishing to update the bioconda [recipe ](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/kraken2)to include the recent confidence score bug that was fixed last commit. Our plans is to create a Galaxy wrapper on the public [toolshed ](https://toolshed.g2.bx.psu.edu/)as well.

**Comment by jenniferlu717** [comment]
I'm not really sure what this issue refers to but the conda recipe is not being maintained by us at the current moment. From what I do know, others are working on updating the conda recipe. Given the age of this issue, I will close this for now.
