### ISSUE TITLE
problem with building RDP special database for kraken2

### ISSUE THREAD

**Issue by mars188** [DerrickWood/kraken2#786]
Hello, 

I tried to build/download RDP database for kraken2 with the following command:
`kraken2-build --db RDP/ --special rdp --threads 24`

Here is the error that I have been getting since last two days:

--2024-01-09 16:33:28--  http://rdp.cme.msu.edu//download//current_Bacteria_unaligned.fa.gz
Resolving rdp.cme.msu.edu (rdp.cme.msu.edu)... 35.8.164.79
Connecting to rdp.cme.msu.edu (rdp.cme.msu.edu)|35.8.164.79|:80... failed: Connection timed out.
Retrying.

It keeps retrying for several times and then just gives up without any download.

I will really appreciate any help. Many thanks!

**Comment by jenniferlu717** [comment]
Unfortunately, RDP is no longer being supported as a database and we relied on those files to allow creation of the Kraken RDP database. 

We do have prebuilt versions here: https://benlangmead.github.io/aws-indexes/k2

**Comment by mars188** [comment]
Thanks for your prompt reply. I tried the prebuilt Kraken RDP database, but it doesn't assign taxonomy abundance at the Species level. Is that how database was built or something wrong with my data?

I get Species level abundance if I use Kraken Greengenes database but I am more interested in RDP for this analysis as it seems to be more curated. Any thoughts about it please?
