### ISSUE TITLE
What is the difference between paired reads or single reads with kraken2 annotation 

### ISSUE THREAD

**Issue by timeresistance1996** [DerrickWood/kraken2#787]
For paired reads, is there reads merge before annotation or any operation difference with the single reads?

**Comment by jenniferlu717** [comment]
For paired reads, Kraken concatenates each pair but placed an "x" inbetween


There is no kmer matching in the overlap but the overall read assignment is now based on kmers from both mates.

**Comment by timeresistance1996** [comment]
Understood, thank you for the reply!
