### ISSUE TITLE
paired-end data: only half reads classified

### ISSUE THREAD

**Issue by nicolo-tellini** [DerrickWood/kraken2#789]
Hello,

I am running _kraken2_ across illumina paired-end fastqs.
My fastqs have 9 millions each. In the _kraken2_ report, I get 9 millions _Number of raw reads_, while I expect to see twice as there are 2 fastqs of 9 millions reads each. 
Is that correct ?

I'm using _Kraken version 2.0.9-beta_

Here the command line I am running:

`kraken2 --threads 10 --memory-mapping --quick --paired --gzip-compressed -db ../../DB --report ./outputs/$i.report --output ./outputs/$i --unclassified-out ./outputs/${i}#.unc --classified-out ./outputs/${i}#.cla ./seq/${i}_1.fq.gz ./seq/${i}_2.fq.gz`

thanks 

nic

**Comment by 2061574124** [comment]
> Hello,
> 
> I am running _kraken2_ across illumina paired-end fastqs. My fastqs have 9 millions each. In the _kraken2_ report, I get 9 millions _Number of raw reads_, while I expect to see twice as there are 2 fastqs of 9 millions reads each. Is that correct ?
> 
> I'm using _Kraken version 2.0.9-beta_
> 
> Here the command line I am running:
> 
> `kraken2 --threads 10 --memory-mapping --quick --paired --gzip-compressed -db ../../DB --report ./outputs/$i.report --output ./outputs/$i --unclassified-out ./outputs/${i}#.unc --classified-out ./outputs/${i}#.cla ./seq/${i}_1.fq.gz ./seq/${i}_2.fq.gz`
> 
> thanks
> 
> nic

hello, May I ask if you have resolved the paired-end seq with kraken2 issue?

**Comment by jenniferlu717** [comment]
Kraken2 (and all other versions of Kraken) concatenates paired reads before classifying them so yes, 9 million is expected for your instance @nicolo-tellini

**Comment by 2061574124** [comment]
> Kraken2 (and all other versions of Kraken) concatenates paired reads before classifying them so yes, 9 million is expected for your instance @nicolo-tellini

"for ((i=871;i<=871;i++)); do kraken2 --paired ，./Sample${i}Unmapped.out.mate1.gz /Sample${i}Unmapped.out.mate2.gz --db /home/dell/database/k2_pluspf --threads 5 --output ./Sample${i} -report ./Sample${i}.report --use-mpa-style --report-zero-counts --classified-out cseqs#.fq ./Sample${i}classified_1.fastq.gz ./Sample${i}classified_2.fastq.gz --use-names --unclassified-out cseqs#.fq ./Sample${i}unclassified_1.fastq.gz ./Sample${i}unclassified_2.fastq.gz; done
gzip: ./Sample871classified_2.fastq.gz: No such file or directory
gzip: ./Sample871unclassified_2.fastq.gz: No such file or directory
gzip: gzip: ./Sample871unclassified_1.fastq.gz: No such file or directory
./Sample871classified_1.fastq.gz: No such file or directory"

hello, this is my code, and the unclassified-out fastq just Sample871unclassified_1.fastq.gz and classified-out fastq just Sample871classified_1.fastq.gz. and i just wonder how to gain the _1.fastq and _2.fastq for classified and unclassified.
thx

**Comment by nicolo-tellini** [comment]
Dear @2061574124 

`gzip: ./Sample871classified_2.fastq.gz: No such file or directory`

it means that the file `Sample871classified_2.fastq.gz` is not in the directory from which you are running the command,  I guess you should fix the path to your file.

best

nic
