### ISSUE TITLE
--special silva : No such file ‘tax_slv_ssu_nr_132.acc_taxid

### ISSUE THREAD

**Issue by tseemann** [DerrickWood/kraken2#8]
First file was ok, but I don't think the second one exists?

This looks like it might be it?  without the 'nr' ?

ftp://ftp.arb-silva.de//release_132/Exports/taxonomy/tax_slv_ssu_132.acc_taxid

```
kraken2-build  --db silva --threads 36 --special silva

--2018-06-28 14:48:38--  ftp://ftp.arb-silva.de//release_132/Exports/SILVA_132_SSURef_Nr99_tax_silva.fasta.gz
           => ‘SILVA_132_SSURef_Nr99_tax_silva.fasta.gz’
SILVA_132_SSURef_Nr99_ta 100%[=================================>] 229.21M   102KB/s    in 36m 10s
2018-06-28 15:24:52 (108 KB/s) - ‘SILVA_132_SSURef_Nr99_tax_silva.fasta.gz’ saved [240343558]

--2018-06-28 15:24:59--  ftp://ftp.arb-silva.de//release_132/Exports/taxonomy/tax_slv_ssu_nr_132.acc_taxid
           => ‘tax_slv_ssu_nr_132.acc_taxid’
==> PASV ... done.    ==> RETR tax_slv_ssu_nr_132.acc_taxid ...
No such file ‘tax_slv_ssu_nr_132.acc_taxid’.
```

**Comment by DerrickWood** [comment]
Yeah, that looks to be the right file, thanks. I'm sure I tested that download at least a few times - I guess it moved? Or I hallucinated it working? Either way, fixed in https://github.com/DerrickWood/kraken2/commit/376dcb0b7b1d9ebcd4e0113d1d908280578aeb82

**Comment by tseemann** [comment]
SILVA is very confusing - i'm sure it was them not you.
