### ISSUE TITLE
Use limited RAM to run a kraken2 analyse with nt databse.

### ISSUE THREAD

**Issue by boyanboyue** [DerrickWood/kraken2#823]
HI,I want to run an analyse by kraken2 with prepared nt Database index files.The haxi file is about 704Gb.
But I can't run it with 140G RAM machine,I know it's not enough.
I have known that `--memory-mapping` option maybe helpfull,but my /dev/shm dictionary is also not enough.
Can anyone tell me any methods to run the analyse with least RAM and how much hardware resources it may be used.
Please give me some suggestions about using kraken2 with nt database to analyse.

**Comment by salzberg** [comment]
You can run KrakenUniq instead using any size DB you want, with a --preload-size option. We published this in bioRxiv and an open CS journal:
  https://joss.theoj.org/papers/10.21105/joss.04908
However note that KrakenUniq uses a different DB format from Kraken2. We have compatible databases on the AWS site linked by Jen above. I've run it successfully with a 430GB database on my 16GB RAM laptop.

**Comment by boyanboyue** [comment]
OK,I will have a try.Thanks a lot for all your reply.

**Comment by ChillarAnand** [comment]
We can increase the swap size and run kraken2 with limited RAM (even with 4GB). However, it will be slow.

I wrote a detailed guide on the same at https://avilpage.com/2024/07/mastering-kraken2-initial-runs.html
