### ISSUE TITLE
building a protein database whitout downloading it

### ISSUE THREAD

**Issue by lalalagartija** [DerrickWood/kraken2#83]
Hi,

I am trying to build a protein database but I already have the standard database downloaded. Can I use the same library to construct the corresponding protein library ?  

Thank you,

**Comment by lalalagartija** [comment]
My additional question would be : is it possible to use Kraken for the taxonomy of my ORFs ? I see that it can do translated search but what about searching without translating (because it is already done) ? 

Thank you very much

**Comment by jenniferlu717** [comment]
For your first question, no. You will have to download the standard libraries using the --protein switch. Kraken2, when building, is looking for protein sequences in the library. 

Then, during classification, it will translate the reads using all 6 reading frames and classify from there. 

I don't think that the code currently can classify protein sequences themselves. It is expecting either DNA or RNA sequences.
