### ISSUE TITLE
Kraken2 does not add to the custom library *every* downloaded sequence

### ISSUE THREAD

**Issue by LeandroD94** [DerrickWood/kraken2#844]
Hi!

I'm trying to build a custom database using also the 18S and 28S sequences (downloaded from SILVA) to better classify the protozoa (which are under-represented in RefSeq). I was able to build and use the custom database without errors, however, from a deeper inspection look like I'm NOT succeeding in adding ONLY CERTAIN sequences as the following one (written below).

What is the issue which is causing this "silent inconvenience"?

Thank you,
Leandro

>seq|kraken:taxid|77619 Vorticella_microstoma                                                                                                                ACAUGGAUAACCGUGACAAAUUACAGCUAAUACAUGCAGUCAGACCUGGUCCAAGGGUCGUAAUUAUUAGUAUUAAACCAUUUCCGAAAGGAGUGUGAUGAAUCAUAAUAAUCGAACGAAUCGCCUGGUGUGCGAUAAAUCAUUCAAGUUUCUGCCCUAUCAGCUUUGGAUGGUAGUGUAUUGGACUACCAUGGCAGUCACGGGUAACGGAGAAUUAGGGUUCGAUUCCGGAGAGGGAGCCUGAGAAACGGCUACCACAUCUACGGAAGGCAGCAGGAGCGAAAAUUGCCCAAUCCCGACACGGGGAGGCAGUGACGAGAAAUAACAACUCUUGGUUAUUCUAAGAAGUGUAAUGAGGAUAAUUUAAAACCCUUACCGAAAGCAAUUGGAGGGCAAGUCUGGUGCCAGCAGCCGCGGUAAUUCCAGCUCCAAUAGCGUAUAUUAAAGUUGUUGCAGUUAAAAAGCUCGUAGUUGAAAUUCUGGCUGAUCGAUCCUCGAGCUCUGUAGCCGAGGACUCGUCAGUCAUCCGCUUGCAAAUAUAUGUUCGCCUUUAACCGGGUGGCUAUAUGAGUAAGCAAUUUACCUUGAGAAAAACAGAGUGUUCCAGGCAGGUUUGUCCGGAAUGCAUUAGCAUGGAAUAAUAGAAUAUGACUGAAGUCGAUUUAUUGGUUUGAGGCUUUAGUAAUGAUUAAUAGGAACAGUCGGGGGCAUUGGUACUUGUCAGUCAGAGGUGAAAUUCUAGGAUUUGACAAAGACUAACAAAUGCGAAAGCAUUUGCCAAGGAUGUUUUCAUUAAUCAAGAACGAAAGUUAGGGGAUCAAAGACGAUCAGAUACCGUCCUAGUCUUAACUAUAAACUAUACCGACUCGGAUUCAGAUGAAUCAUAAAGUUCAUUUGGGACCGUAGGAGAAAUCAAAGUUUUUGGGUUCUGGGGGAAGUAUGGUCGCAAGGCUGAAACUUAAAGGAAUUGACGGUUUUGCACCACCAUGGAGUGGAGUCUGCGGCUUAAUUUGACUCAACACUGGGAAACUCAUCAGGGCAAGAAGAUUGUAGGAUUGACAGAUUGAGAGUUCUUUCUUGAUUGGUCUAGUGGUGGUGCAUGGCCGUUCUUAGUUGGUGGAGUGAUUUGUCUGGUUAAUUCCGUUAACGAACGAGACCUUAACCUGCUAACUAGUACACCGAUGACAAAUCGGCGUUACUUCUUAGAGGGACUAUGUGAUGUAAUCACAUGGAAGUUUGAGGCAAUAACAGGUCUGUGAUGCCCUUAGAUGUCCUGAGCUGCACGCGUACUACAAUGGUGCUUUCAACGAGCUUUUCCUGAUCCGAAAGGAUUUGGGUAAUCUUUUUAGUGAGCACCGUGCUUGGGAUUGAUCUUUGUAAUUAUGGAUCAUGAACUAGGAAUUCCUAGUAAGCACGGGUCAUCAGCCCGUGCUGAUUACGUCCCUGCAAAAUGUACACACCGCCCGUCGCUAUUACCGAUUGAGUGUAAAGGUGAACCUUCUCGAUAGUGUCACCGCUAGAAAUUAAGUAAACCUUGCACU

**Comment by jenniferlu717** [comment]
Where are you getting these sequences and what command lines are you using to add/build these? I suspect it has to do with the fact that these are RNA sequences and not DNA

**Comment by LeandroD94** [comment]
Hi jennifer!

I get the sequences from the SILVA database (then rRNA) and formatted the headers (with NCBI ID) as requested by kraken2... And you are right, looks like just changing the U in T before adding the sequence is enough to include also these missing sequences in the database!

Thank you,
Leandro

**Comment by jenniferlu717** [comment]
Oh i would be careful about translating this. You need to convert RNA to DNA, so not just U --> T but also C --> G etc

**Comment by LeandroD94** [comment]
If I convert the C in G (then the complementary strand), shouldn't I convert the U in A then? At this regard, then do you suggest to use the complementary sequences of those rRNA sequences downloaded by SILVA?

Leandro

**Comment by jenniferlu717** [comment]
I would use the complement yes. So yes U to A, C to G, G to C and A to T

Johns Hopkins Hospital
Department of Pathology, Microbiology
Staff Scientist/Bioinformatician, Simner Lab
240-449-7437
________________________________

**Comment by LeandroD94** [comment]
Then I will translate them, thank you for your time!

Leandro
