### ISSUE TITLE
error in 16S silva database?

### ISSUE THREAD

**Issue by josmos** [DerrickWood/kraken2#85]
I am testing kraken2 for a 16S pipeline and I was using the kraken2-build --special silva command to build the database.
I realized the result visualizations made with krona are completely distinct as compared to qiime - silva, and qiime - greengenes.
Testing the kraken-full database gives similar results like qiime.

Krona is using the Taxonomic IDs from NCBI to map the query IDs to the taxonomy. The Taxonomic IDs of the Silva Database differ from NCBI.

I can provide the test files and results if needed.

**Comment by ropolomx** [comment]
Hi @josmos. I am a Kraken2 user, and I am also interested in 16S profiling with this tool. Did you have an opportunity to look further into this? I have not visualized Kraken2 results with Krona yet, but I have used another tool called Pavian (https://github.com/fbreitwieser/pavian). It was created by @fbreitwieser, who also worked on the development of taxonomic classifiers such as [centrifuge](https://github.com/infphilo/centrifuge) or [krakenuniq](https://github.com/fbreitwieser/krakenuniq). Kraken2 16S results look fine to me when I use Pavian for visualization. That being said, I'd be curious about trying out Krona for this purpose.

**Comment by josmos** [comment]
Hi, i moved from the standard approach (using Kronatools _ktImportTaxonomy_) to ktImportText, building the input file from the kraken.report file. I hope this helpls.

**Comment by jenniferlu717** [comment]
Pavian is very useful for visualization of the results. 
However, if you want to get a Krona file from the kraken report, I would use kreport2krona.py that I developed here: https://github.com/jenniferlu717/KrakenTools
