### ISSUE TITLE
`k2mask` is only single-threaded even with `--threads` and `OMP_NUM_THREADS` set properly

### ISSUE THREAD

**Issue by hermidalc** [DerrickWood/kraken2#855]
During `kraken2-build --download-library` in the masking low-complexity seqs step, `k2mask` always appears to be single-threaded even though I've specified `--threads n` and `OMP_NUM_THREADS = n` in my environment before running. Do you know why this is happening?

**Comment by ChillarAnand** [comment]
Looks like only `--build` step is using threads. All other steps seem to be single thread.

**Comment by hermidalc** [comment]
> Looks like only `--build` step is using threads. All other steps seem to be single thread.

Yep the `k2` wrapper script that was added in v2.1.3 is never called when you run `kraken2-build --download-library`, it runs `download_genomic_library.sh` which spawns `mask_low_complexity.sh` which seems to have older `k2mask` spawning code that is only single-threaded!

https://github.com/DerrickWood/kraken2/blob/v2.1.3/scripts/mask_low_complexity.sh

**Comment by ChillarAnand** [comment]
I just found `k2`. I think this meant to be used as a independent script.

Can you try this?

```
$ k2 download-library --db viral --library viral
```

**Comment by ChillarAnand** [comment]
> `-threads 4` 

Not sure why this is hardcoded. Shouldn't this be configurable?

**Comment by hermidalc** [comment]
> I just found `k2`. I think this meant to be used as a independent script.
> 
> Can you try this?
> 
> ```
> $ k2 download-library --db viral --library viral
> ```

The problem is in the bioconda `kraken2` package none of these independent scripts are in the $PATH, only the binaries in the manual `kraken2`, `kraken2-build`, `kraken2-inspect`, etc. I'm building a pipeline that is intended for others to use and to be reproducible so conda is a must.

**Comment by hermidalc** [comment]
> > `-threads 4`
> 
> Not sure why this is hardcoded. Shouldn't this be configurable?

It's fixed in master but not yet available

https://github.com/DerrickWood/kraken2/blob/4cbdc5fac92d0a19d76ce68d6633d7ff794a1587/scripts/k2#L476-L487
