### ISSUE TITLE
Unable to install Kraken 2 and bracken on my Mac using conda

### ISSUE THREAD

**Issue by chrissy005** [DerrickWood/kraken2#860]
Hello,

While I am able to install bowtie2, KrakenTools and samtools just as it is described in the Nature Protocols paper, I am unable to install Kraken2 and Bracken

I used the following code and get the following output:

$ conda install -c conda-forge -c bioconda kraken2 bracken
Channels:
 - conda-forge
 - bioconda
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides requested kraken2
  - nothing provides kraken needed by bracken-1.0.0-1

Could not solve for environment specs
The following packages are incompatible
├─ bracken is not installable because it requires
│  └─ kraken, which does not exist (perhaps a missing channel);
└─ kraken2 does not exist (perhaps a typo or a missing channel).

Also, do you recommend that I can run the microbiome analysis protocol described in the paper on my MacBook Pro or on a HPC?

**Comment by ChillarAnand** [comment]
kraken2 doesn't have official arm64 support yet.

However you can use brew to install kraken2 on M1(apple silicon) macs.

```
$ brew install brewsci/bio/kraken2
```

More details at https://avilpage.com/2024/07/mastering-kraken2-initial-runs.html

**Comment by chrissy005** [comment]
Thank you, this works
