### ISSUE TITLE
How to build "plasmid" database? 

### ISSUE THREAD

**Issue by khoriba** [DerrickWood/kraken2#88]
Hello
I'd like to build the "plasmid" database.  I downloaded "plasmid" library using `--download-library TYPE` option. Then I commanded `kraken2-build --build --db ${DBNAME}` and built this database. However, I got the following output.

> Creating sequence ID to taxonomy ID map (step 1)...         
Accession to taxid map files are required to build this DB. 
Run 'kraken2-build --db kplmdb/ --download-taxonomy' again? 

So I followed the instructions.

> $ kraken2-build --db ${DBNAME}  --download-taxonomy
Downloading nucleotide est accession to taxon map... done.            
Downloading nucleotide gb accession to taxon map... done.             
Downloading nucleotide gss accession to taxon map... done.            
Downloading nucleotide wgs accession to taxon map... done.            
Downloaded accession to taxon map(s)                                  
Downloading taxonomy tree data... done.                               
Uncompressing taxonomy data... done.                                  
Untarring taxonomy tree data... done. 

I built it again, but it is the same output.

>  Creating sequence ID to taxonomy ID map (step 1)...         
Accession to taxid map files are required to build this DB. 
Run 'kraken2-build --db kplmdb/ --download-taxonomy' again? 

Can you please tell me the cause of this error, and how to resolve it?

**Comment by jenniferlu717** [comment]
It is looking for *accession2taxid.map files in the taxonomy folder. Are those files there? 

I didn't have any problems with it running these commands in this order:
`kraken2-build --download-taxonomy --db .
Downloading nucleotide gb accession to taxon map... done.
Downloading nucleotide wgs accession to taxon map... done.
Downloaded accession to taxon map(s)
Downloading taxonomy tree data... done.
Uncompressing taxonomy data... done.
Untarring taxonomy tree data... done.
kraken2-build --download-library plasmid --db .
Downloading plasmid files from FTP... done.
kraken2-build --build --db .`
