### ISSUE TITLE
Massive increase in vector classifications with custom database

### ISSUE THREAD

**Issue by andrewjmc** [DerrickWood/kraken2#92]
I have run kraken2 through Anaconda with the standard database. I needed to add fungi, so I made a custom database as per the manual (comprising bacteria, archaea, human, viruses, fungi and UniVec_Core).

Strangely, the number of reads assigned to "other sequences" has increased massively with the custom database:

```
From:
  0.01	408	408	R1	28384	  other sequences
To:
 40.90	1771252	1771252	R1	28384	  other sequences
```

And these appear to have mostly been "stolen" from Homo sapiens.

```
From:
 61.97	2683593	2683593	S	9606	                                                              Homo sapiens
To:
 15.40	666679	666679	S	9606	                                                              Homo sapiens
```

As far as I understand the standard database also includes UniVec_Core, so I am surprised at this major change in assignment.

A quick scan at some previously human reads is helpful:

```
from:
C       NB551065:160:HNCCFBGX5:1:11101:23576:1110       Homo sapiens (taxid 9606)       151|151 1:2 28384:5 0:65 9606:1 0:7 9606:37 |:| 9606:117
to:
C       NB551065:160:HNCCFBGX5:1:11101:23576:1110       other sequences (taxid 28384)   151|151 1:2 28384:5 0:110 |:| 0:117
```

So the human matches for 38 kmers from pair 1 and all kmers from pair 2 seem to have disappeared. I have confirmed that the same size human database files are present in the library folder of each database.

Any clues welcome!

Thanks,

Andrew

**Comment by andrewjmc** [comment]
I'm still puzzled by the behaviour above. I can't understand why human k-mers have been lost when adding fungi to the database.

Could this be expected behaviour because of loss of minimisers when adding fungi?

**Comment by DerrickWood** [comment]
It appears that various sequences in your newest database did not actually get incorporated into the hash table. Without being able to see the file structure or examine the files, it's hard to see exactly what happened. But the full dropout of hits in the example you gave would suggest that at least one of the human reference sequences didn't make it into the hash table. I would check the `seqid2taxid.map` file in the database directory to see if indeed you have all the human (taxid 9606) sequences you're expecting to.

**Comment by andrewjmc** [comment]
I have just checked. I have 594 human entries in the `seqid2taxid.map` file, which agrees with the 594 entries in the `Homo_sapiens/library.fna` file, which is 3.1Gb as seems appropriate.

I will try building the standard database then adding fungi, as per the suggestions in https://github.com/DerrickWood/kraken2/issues/106.

**Comment by andrewjmc** [comment]
I have now rebuilt the standard database, and then also standard+fungi. Appears to be behaving exactly as I would hope now. Something must have gone wrong in my earlier build from scratch.

Many thanks for your help,

Andrew
