### ISSUE TITLE
special db greengenes 13_8?

### ISSUE THREAD

**Issue by pedrocr83** [DerrickWood/kraken2#94]
Hi there,

I have found the current version of greengenes 13_5 used to be insufficient when comparing a fecal sample to the special GG db kraken. Just to provide an example there's no escherichia coli on the 13_5 taxonomy but there is on the 13_8.

I've looked to the perl scripts in creating the DB and the issue of changing the version seems very fixable except for the fact that we can't wget the same files on the ftp site due to the fact that they don't exist.

I wanted to mention this so everyone is aware and/or experiencing similar issues.

I'm gonna see if i can find a solution in creating the taxonomy file with the new version...

**Comment by pedrocr83** [comment]
UPDATE: The 13_8 taxonomy version contains only updates to the existing taxa information present in 13_5. I've merged them together and  have updated the 16S_gg_installation script to accept the new version locally. And even improved it by adding new taxa along with new ids to the 13_8 version (e.g 16s from species that aren't in that version but have been added on refseq on ncbi)

**Comment by hurleyLi** [comment]
> UPDATE: The 13_8 taxonomy version contains only updates to the existing taxa information present in 13_5. I've merged them together and have updated the 16S_gg_installation script to accept the new version locally. And even improved it by adding new taxa along with new ids to the 13_8 version (e.g 16s from species that aren't in that version but have been added on refseq on ncbi)

Hi, could you please share your 13_8 database or the script you mentioned? Thanks
