### ISSUE TITLE
separate dustmasking from downloading?

### ISSUE THREAD

**Issue by JCSzamosi** [DerrickWood/kraken2#95]
Is it possible to download the databases using `kraken2-build --download-library` with the `--no-masking` option to reduce CPU use during the downloading step, and then mask the sequences during (or before) the `--build` step? I would like to have masked sequences, but I need the downloading step to be low-CPU because of how my institution's clusters are set up.

**Comment by jenniferlu717** [comment]
At the moment, the best I can say is to run the masking step manually prior to building:

`for file in library/*
do 
dustmasker -in $file -outfmt fasta | sed -e '/^>/!s/[a-z]/x/g' > "$file.tmp"
mv "$file.tmp" $file
touch "$file.masked"
done`
