### ISSUE TITLE
How to find sequence hits to a given taxon

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [DerrickWood/kraken2#96]
I have a metaphlan style output, which I can make into a species abundance table, but how can I find reads matched to particular taxa? From the name, I can look up the TaxID on NCBI but some species can have any one of dozens of different TaxIDs. Is there a type of output that will give me the taxID and the name? and a way of finding the hits to it?

Other taxa appear to not be present in the --classified-out fasta files, e.g. my output shows Colletotrichum orchidophilum, TaxID 1209926 , but grep for that ID in the fasta hits file shows nothing. That species can only have one TaxID. What is going on?

I need to check the hits because I am getting a huge overestimation of the number of species (>100) from a library (same DNA) that only had 4 or 5 taxa from ITS.

Thanks. T.

**Comment by mgalac** [comment]
I'm having a similar issue with related the taxid found in the output from --classified-out. The taxids in that fastq aren't in the report and the ones in the report aren't in the fastq. I can't find any documentation on how these taxids related to one another.

**Comment by ellisrichardj** [comment]
I've just discovered the same issue as @mgalac 
For example, the standard output gives:
C	NODE_846251_length_89_cov_2.000000	1763	119	13734:Q
but in the --classified-out the same sequence is labelled as:
>NODE_846251_length_89_cov_2.000000 kraken:taxid|13734

Taxid 13734 is actually a African softshell turtle, which seems a bit strange as I'm only using the minikraken2_v1 database (refseq bacteria, archaea, and viral only)!  The 1763 taxid in the third column of the standard output is correct.  So where does the number in column 5 come from and why is it being used as the taxid?

**Comment by ellisrichardj** [comment]
Just seen that this has been fixed #44 in the 2.0.8-beta relaese
