### ISSUE TITLE
libstdc++.so.6 PROBLEM

### ISSUE THREAD

**Issue by BioRB** [DerrickWood/kraken2#98]
I'M TRYING TO BULID A CUSTOM DATABASE AND DOING THE COMMAND:
 `./kraken_dir/kraken2-build --build --db ./database_1`
I GET THIS ERROR:
`estimate_capacity: /usr/lib64/libstdc++.so.6: version GLIBCXX_3.4.20 not found (required by estimate_capacity)
estimate_capacity: /usr/lib64/libstdc++.so.6: version GLIBCXX_3.4.21 not found (required by estimate_capacity)
xargs: cat: terminated by signal 13`

Since I'M WORKING ON A SERVER AND I'M NOT A SUPERUSER I CANNOT UPDATE libstdc++.so.6 AND LOOKING IN MINICONDA I HAVE libstdc++.so.6 IN SEVERAL OTHERS PATHS ( MAYBE WITH THE GOOD VERSION) BUT I DON'T KNOW HOW TO CHANGE THE PATH THAT KRAKEN USE AS LIBRARY PATH. I'VE TRYED ALSO CHANGING THE LIBRARY PATH BUT DIDN'T WORKED.
ANY SUGGESTION?

**Comment by arrusus** [comment]
solved by doing:
export LD_LIBRARY_PATH of="/path/of/another/copy/of/ libstdc++.so.6/in/miniconda/folder//:$LD_LIBRARY_PATH"

**Comment by karoraw1** [comment]
previous response worked like a charm!

the specific command for installation (into my conda environment `base2`) was: 
`conda install -n base2 -c anaconda libgcc=7.2.0`

the specific export command that I added right before kraken2-build was:
`export LD_LIBRARY_PATH="~/scratch/miniconda2/envs/base2/lib:$LD_LIBRARY_PATH"`
